apiVersion: ENC[AES256_GCM,data:N+c=,iv:nPWCcoJrh88IrYYDAF7QXXKHK3mbwVYfQHUBc+mOTuE=,tag:xJ05g0o5uaKzpH6POimiZg==,type:str]
kind: ENC[AES256_GCM,data:/ywOlt2w,iv:iKQsU2BBx6NL12GnXfoMehg9yZBAowloeOq2WlfO/mw=,tag:opFt/qgksBGLhNJv6C/aew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4tyiXhWabGnaZwdkVA==,iv:GyLCl636WG17JDG0uIf2wrsL3noRpIckDOLa5r1KL2Q=,tag:LW1yAfUFxRxJTL69qw1e+Q==,type:str]
    namespace: ENC[AES256_GCM,data:pcBM,iv:4p4iljz9x9MsGi5D5N4ALFTODIA5KgSsv0qgBp7tKTE=,tag:2uv62wdQ8QUE4B0jSSXs6A==,type:str]
type: ENC[AES256_GCM,data:WlW8PFpf,iv:7O1iMJY5dyE7K+RP9lTeIwprNJSHctXDkeya0tgCcAk=,tag:1d7SI26Gw4vNlk5va+2u+g==,type:str]
stringData:
    #ENC[AES256_GCM,data:yb7zyUQHnhYvoHGQnKBmnFxnFlk8o02KpKkWryIYCiDVukC5gJtFGGlVD+TbOZ0ywQEawJFipcJEYMofu5gScMrRSBXsh4C6,iv:Xo8I6I89XILtJDBQthxobG8Od1GMcicA0jJo6Hj33RA=,tag:8wrK8s5wRkRFhXJm6QIuLA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6Wm6qQQHNJeFs9eAUfYWdUJn0ks=,iv:NcvANsQZAfgwvZ/r4Zis1zkJWEAEPb5JeupDZxc+950=,tag:GERMSMtLR3ffp1nlL71IWQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BtH48EEp0yvyjRoQwhqJBIrGsQ8aUWEhNlmetHJxKciJxYMEXpHl8A==,iv:ElwK5SIKu/BQuuoefNAHZt07nfw9S5om+Bxx0Tmk14Y=,tag:bU+OAA4vSj0t8Z6bFTfT+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Vjd1OURtb280M2JxOWxY
            ZUdkTUZadUtXR2kwUXd6RkxEdzhHTmFIdTFzCkl6cmNERmFsa2FydkR1WFhNcW9r
            SEo5c2dId1NQQlB2RXRRRm03WTU4ZUkKLS0tIE1ON29YVmZ4NThVMkkzTmxVV1Ro
            QlRqd1B4V05ya2NpcDVGaVRmZ2dOaDgKjd9iqBoXapJp/2Swwhpmq9fJ2Sas9YG4
            Fv2+CZwg1YLHoEAqYnreLatHDAu1w1SrPGoY5uZ1OLhUCzJVwmMoSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdGcvR2h6T09oQVk2ZmZO
            QzNwNHJIQk9NR0svb1lyWnZwWFRpaXE1UFU0Ck05eG5qRTM1K2ltb2ZqN2xrWit1
            ZCt6VU1YVXdhTWo0OWk5TlBoMmJBTGsKLS0tIDVNblB2QTRacWFUZXFVY1VWQkRE
            cDJRNTl2andlN1FDTHVZQzF6b2JzNVEKBJ1ZKRS4WW0R7uk2L+9nsBHe6DwhVnNY
            NM28rEr+Ce2IS+aSLAGWZFSRFxLGJu46vxuk0lZwJuV8jc20rMv6jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-03T08:10:23Z"
    mac: ENC[AES256_GCM,data:3rzuA7ksUW87LEQfISwNCQ6dpd2uDYgqvdBY5I7Gl9BKh5GY6TxkjFJS5tv+c0rxSI1QAGWZZ1EhFa+v8fqz66V0LrctstJKCx5c725AixiX21Q0pTLHli1PQqHwYcMwhKCnn1RaCXWGeSjpRK+4K5huDAad7fy4dPM3JVEoxqY=,iv:PrAEY9eZeja+YJJjCS4V1Z3BhT97TqSRn2RW/T/qLwk=,tag:9KLFWdskZrm9eF70jC9tgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
