apiVersion: ENC[AES256_GCM,data:eOE=,iv:qmG5UF0mD6BfCe7UGxH3Y50CZf2X99W+Sj07ZCAXU0Q=,tag:HSwsHN2NcgKlEHRXK9o9Gw==,type:str]
kind: ENC[AES256_GCM,data:BTcRa0+s,iv:koEPa201BwVRgM8fpYwS8WFR8VZ0Ony+ggprPPqXFtk=,tag:+TS+DAGKcXU4+H/8G/cU/Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BVVYbW2mk4BSuyXgHg==,iv:PTLkDUxW6Pne3DivPv/2EeAk+eP+U7DegHwzuDDM8Kc=,tag:6SSkqAILehU2/tvpX0T6OA==,type:str]
    namespace: ENC[AES256_GCM,data:aixJ,iv:gxYmsaShpqXkh9oX6VJGs5BGeWeGJ6D23K6P95id35o=,tag:o6Jje0SWjrbgIe+FYeZVfw==,type:str]
type: ENC[AES256_GCM,data:5Br06kUP,iv:VLolzaTERUB1ytwBUQGIk9RubrLrblxzT5RKjvqJQVo=,tag:nKAu7Fkmr3mVJL7GIHsL/Q==,type:str]
stringData:
    #ENC[AES256_GCM,data:GFq39/Y0bd/PPgxdHiRw0JCTxMrbCVISI9rto6th5vYUlPjHcArNpi5RIJOY35NOWfOpARwpldZkdbxU28AljgTG7dh8RacQ,iv:HvB3b2Kn/aeGZS1QMyVYzcehtdVVeLPqTWwHQ0u5zv4=,tag:zlRkO4OkMXrbQ/EJfAqowQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gTzXir7AAMo=,iv:Xhj7V7okOWQDoXwvHUc8dunRF4caWUfuqJVRVYk2AVU=,tag:EnHm9I2rj7rhMjjVoAh4sA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iJmrzh2F3z0=,iv:3omiqhigsMn+O4zcCTa3s79jxHUrwzOM2Yenv54QoZI=,tag:AdM/NCH9G/wXJbbl851kYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ3UrL1FmWjMzeGJ3ald5
            RHJJK1RRaVJxelNmdUREU2VhNnZQU2JpdlJJCm01UTNPQlV2RXJjRld0dlcwUDJJ
            MTI0bXNjN0pPQWdGWCtTNVRwY3hBT3cKLS0tIE5BcFBFYjgzcldsVW5vYmtFbThw
            MDFhOU10cnRIaVhvYTJLSTNMcUpzMGcK+sOGo0YkXfBRi+DTVHwp3xr1tOWGsJ6r
            T1qX/R5zkTfBuvhxEXwxw7ti1mHEJgXO8CqtUxKl9HgyUA9rm944FQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T07:21:11Z"
    mac: ENC[AES256_GCM,data:56O9keaxCCy6V6vFdvW7NO/C66tZBT7gHbYxjqWKiZVNvu4qXOUs3akGU/SAeoj480MsLdLRIDLDZnMDlxeWpU1lMhE/1x4hGODGPEQJgZJvfmol7SS1LgYQDBsO7FJmVeFG+vcShsvMzUPWq43eHwDI/AG/sES2rdeJugmZ+fI=,iv:H/9LMbWO/21gDhL1h7UDEFBOW9SopEWWbFvERKVfMME=,tag:FOa1pttN9q/FD0wmE1Q/oQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
