#ENC[AES256_GCM,data:wUDxgDwnhRNqHSg9zM+5ZUS9i6ovuSWeUvPS9uPdPvixlvwS8wB0H2Q26rF6Aw==,iv:yAuoyfd7OiZ0f1ptDBHfD8jYlcCO4QIqo7PJqBL6ljc=,tag:ldwSxga8aumYZ89FUCRLwA==,type:comment]
#ENC[AES256_GCM,data:p6khCNuAeTpu2RpYMVBjSZaay7WFs0DJAajjIbjPk9Xny9m6+sJHvFXHtgazpbYDA2t0fgZPHw5q3832AM6fliGIKE6sNhxy3J1HXF6z/2xqtWs=,iv:1T/FZITWO/5DHt9o/jMhiBofxYvQIuJijg61eaihnWc=,tag:N2RK3owWEapdAyOW6rr/fA==,type:comment]
#ENC[AES256_GCM,data:X9bOZplmCqqGtaOJ1gSzrA==,iv:7WIYdRXPI7OLEAO9moJUviBzUZCXioSWQSMFwh6Tny8=,tag:xw1wTMcbxaEakcxoPpOp3Q==,type:comment]
#ENC[AES256_GCM,data:fxKu64PoWN5bYKaE9tVcrKBu3ASd/xaWNKxqf2LA173KjagKs5Tcj5hK5epN2vn8TO2vuXm+D5hYNJDqrw9/Bdxibz1b/Gz4l6G6Awu6g0hZNXOh,iv:yaTteOf21M2G9cjOMm61n5ydjV5b82p7bORznBGR618=,tag:wa64xLEHuoIEjO8oxBXx1Q==,type:comment]
#ENC[AES256_GCM,data:harbKSmfnNN9TB8atWgbyVvccGb1AiOS1OWi2KueYMCnHa6GhrRSem5dBI+OJ+MlpIyrQS1oeJllaStrEfIJXdgAel1shPnQhHfQ23xaTyY=,iv:bNX6+t/euwUMhPrNdrbaNNca8o7WFEXk8ZajQORx6qQ=,tag:6Np1s91ZD7rx6DlfXS00jg==,type:comment]
#ENC[AES256_GCM,data:MpxHQObdI1LAJbZCFf+av/nUqviXSr5ZL/2pPHgb1ZdZPPR92lTyREbvMahdRvKbhKxONTl4onJ9TWb0eE4=,iv:76pVtqJM5t/tvA5MVVm9p+FNY5wJGKbLIbo/69ScXT4=,tag:sdxhzlleFmjjxlh+EokHtQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:uUw=,iv:jH4qNqP/QY2FWTCIbTb9g2wNO9uDdYQGUMAdELnD8kc=,tag:fWF6dHAaL3h+pkuS+oqqZQ==,type:str]
kind: ENC[AES256_GCM,data:FOhLBemR,iv:g5y/G7uMbHvak8JqpqOA1T/yl7lWYyYHrhT1WTUQ0xM=,tag:KRfNz8uJH1JkIOubko3Xyw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bfMR03bZsKKKsku2wqaZVVuOgSs+GSwY,iv:FbJROEGX3n0w84X8kIhH35M51Oc9Nh2/HBlGlfjKBHo=,tag:oawcyNkRByuAMGG+o11QrQ==,type:str]
    namespace: ENC[AES256_GCM,data:qjKW,iv:2VAkYBViCkAwbGclsXIWkZDDRbUeRzkxxOeAPDJGUlo=,tag:jTL8eb5PImVZKKDzLqMegQ==,type:str]
type: ENC[AES256_GCM,data:Z5ivowR+N/Og7etvA4mZlLFe0eHgLOY/,iv:EfixmGO/MFGY5KDHVV5uRkbzL5bckcjwBrDnfYKXQiI=,tag:Y8yzyYYIMbhDcr9ygGGREg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Z1zt,iv:Eb5phaAjcCTSg8NkcLe3LEudbbyGmsjgwK73OAynK5A=,tag:R/hGstVnkaum0XDjo8ADAA==,type:str]
    password: ENC[AES256_GCM,data:eRLl9+RqrhF4TOCqxiMpdtPddOE9UZsVMo+mtZhu,iv:8xrNS71uycOuAQTCsWlsPgt2xbmRqsbJsQPGMFxxo6Y=,tag:APTbjuIDzvVVYg7iORJG5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM0UyYThjM05ON1F6dERi
            K3JyR0RWcC9XdElkWmV4enpkUllHeVh0MndNCjV3dG4vNis4OWdWQ0wxOE43Vkc2
            WWE3UE45NUdSRlJGM0JPNzR6cWdJSE0KLS0tIHRtWjNSWXlrd0xaS2g3QjRrTThE
            YzM0ZEczbFVHQk9JYjJGSkxLelhEcmsK/1fEUKxK3RuTI78NyVGmlFLmnvVHGCtr
            Yzq0Dgu5MZkLnTtJ20iKHtf4t4NT1hC/4V6kHTOjQDAuyC+nzRu36w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-02T21:10:06Z"
    mac: ENC[AES256_GCM,data:fqB3TZMOMRjv9P0InJnLiavSn11CZu7LVFVfA+eAxNMydsRsYk8cseRXEmkp1FO0UV6CKujSlG2QHs7TYIw0N0n8gFQtIPtVhKZTJDAxGubtfaCNSJRNPYBbo2OLmxvjXxpJn1oZ0cnLDPvs8bAAj6zgEXg8HuKxh6PSOwZAuBE=,iv:YdtC+s+0w+QDXMAfncK2SqFWkaBA+x/+vixxdb5//2I=,tag:FY1ghJBYmrMcuXmDstjapw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:IOQ=,iv:uDRtnn2GqRfw0DRintw0xqcSH68s4RNrYQSKonA4sAI=,tag:iWvsuMq5V5Jp/T9yCTP5qw==,type:str]
kind: ENC[AES256_GCM,data:BRVCvIGl,iv:RKvjW3UemeSVJRjDL/K3eo7IFP8tcl2+gfxX9YaM3yg=,tag:OpbRpvu3B5F/R+hTmy5tjg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CDtNXQk1+6YteYhh856S,iv:1Ox7pkOggNYcnpl/RY2Ms+0dx/yB0JMypZjxpm1D/6M=,tag:fi0RcZctHtRKaB294lbxEg==,type:str]
    namespace: ENC[AES256_GCM,data:R6V8,iv:l6827DiGelyB9KE7v5pFVM7lCivJdsELw1X7fddPuuw=,tag:qR3rcbZzUvbnscJXwbkEgg==,type:str]
type: ENC[AES256_GCM,data:MbrcybdB,iv:54w3giSLEDS2h038bkVx0RngV01SxjJE89vR0MFzseY=,tag:E+K3UfgvU4h3CNSNBprD3g==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:VukkS3eq7SCeicN38R4qCUshW6LhMTKn5WvaYau1,iv:Obrd4XdJLDRJ0JThqNqgSmYQ8KsXG0uiHOk2URS5ta4=,tag:D6QwdEWbyoI17MvgqsDrXg==,type:str]
    #ENC[AES256_GCM,data:rm91noX50RZFjqvqJAFmwpjXdh/obUUnW3eC15K9awy0XYAlSBYMz3iGAKv+2LLOoGeok/Uq62rKFp+V7wQsonRVkqv5xBvucA==,iv:3ZkI3Fc8ddqQ7dobV7oN4JB6cvTjl1XbTKpFjllenX8=,tag:05BIrV5I9pyXmb1hQUz9Dg==,type:comment]
    #ENC[AES256_GCM,data:Xb3qGihuXd1iqb5QP10UBLtQiuyNec3usf4LhrHAUTrnOwk5,iv:ek5LiZlszBjhLUvDlf3zepCDnscsmybBz4GluYGcA8Y=,tag:TLcmFiVIpY422CudHoeF6g==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:qghaJzOlnGEfa5jN98JSN5IBueLCKrHLk77JEsZ21A1hzXckdwYwrthQ3dFS,iv:06b31Jv8WetjPcJ6rOUs6L90l3haPK05cBk3we1JbMg=,tag:bNlgfgcBgqoK5ItErpREZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM0UyYThjM05ON1F6dERi
            K3JyR0RWcC9XdElkWmV4enpkUllHeVh0MndNCjV3dG4vNis4OWdWQ0wxOE43Vkc2
            WWE3UE45NUdSRlJGM0JPNzR6cWdJSE0KLS0tIHRtWjNSWXlrd0xaS2g3QjRrTThE
            YzM0ZEczbFVHQk9JYjJGSkxLelhEcmsK/1fEUKxK3RuTI78NyVGmlFLmnvVHGCtr
            Yzq0Dgu5MZkLnTtJ20iKHtf4t4NT1hC/4V6kHTOjQDAuyC+nzRu36w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-02T21:10:06Z"
    mac: ENC[AES256_GCM,data:fqB3TZMOMRjv9P0InJnLiavSn11CZu7LVFVfA+eAxNMydsRsYk8cseRXEmkp1FO0UV6CKujSlG2QHs7TYIw0N0n8gFQtIPtVhKZTJDAxGubtfaCNSJRNPYBbo2OLmxvjXxpJn1oZ0cnLDPvs8bAAj6zgEXg8HuKxh6PSOwZAuBE=,iv:YdtC+s+0w+QDXMAfncK2SqFWkaBA+x/+vixxdb5//2I=,tag:FY1ghJBYmrMcuXmDstjapw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
