#ENC[AES256_GCM,data:8R4IWhQJCtMwEozVSBNIugRo3OTumVzAtn1XcAqmIXFwta1lArW8IfsEEuaRHFCQ+vp+2+7z,iv:GlQtQda9lpTLqqpXLVB+Jv/a0WEUg9n1GWwXOzfJ++c=,tag:uzZIL6H3uTv8MO6Sa0iuEA==,type:comment]
#ENC[AES256_GCM,data:/r//i5ZBhkZlIYb0+RJzA2XzGMVQJniptTUxYREA+6gpX1ijtlA06Gs9jZEaqa7nOhE9oRgb4W56LIw=,iv:NslFJxXjWFm37jvVYop4HK+zQwsrueu+KS6yxiub0pk=,tag:yVVRWC/KfN6j8yCF+5C9gg==,type:comment]
#ENC[AES256_GCM,data:AXxXexI7GkrjO7dBhahQTEw9RCO4l+2IMGBlyf7gNsm2Djs7cBlSmH6dNb/jspYfsX6xWjOoq5Y=,iv:59mBof8KHSvjWfvaVTo+7ERatklAkEVAhfwP1VR2fK0=,tag:h2mFMo4MwVfVGqVYOniMCA==,type:comment]
#ENC[AES256_GCM,data:a/n5dYUBG3IyO5dTIxl8hAG017UW2N2X2JBy0pXWgPnFsn8kCimcdauQykAxpUjycjZ2s80xUH+276CMuC1LPSAilAAH1IDB+UR7QC7AbQ==,iv:zRkwUtPB5JM6Wce0DbpHzqhJbKkMD1thRs9XgCk5ANs=,tag:do17TT393YfzaH71BGS2bw==,type:comment]
#ENC[AES256_GCM,data:DAgOPvjV6XV3n61xIgcqey2zRfcjBAOihe9FxfHFcZW7H1z9v99FGrU3iVpwVAG/ggiJAEUFIsM1rXGgycF++UQLhW6BDjP4RqTQ5WmxtLHy,iv:fd0M8j2nsGapb5IcDyV2La1lEOizrRnJqPiXidqbblI=,tag:qp51ZrUTJ/KjDRmWEMvHsw==,type:comment]
apiVersion: ENC[AES256_GCM,data:N3Y=,iv:usmQOP8sFBCSitLOBOekiDR20PCwVPqDq8rmhlvzBoU=,tag:eWVtEAsrybf0A9hq1YwQPw==,type:str]
kind: ENC[AES256_GCM,data:npi6JiZR,iv:m8aRbEI0C9zyGkGzTE1MbPSLD2lgVwpfd2LKTiVY0AU=,tag:feziKST3f84dB8QDkvDE/Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2jiIpT4R3ehTg3sxUR5TZFUWRtVnJIYR,iv:Uob8yVpvZnwdwDRG2H/pSmED1kzh+7v6X4bkIkebP9k=,tag:GFwX018tpDlcSPrL9IJSgw==,type:str]
    namespace: ENC[AES256_GCM,data:reuY,iv:ktq9SMbHs0nmEDlBLCBax4x0D4B7b3c/sfg7jj9VCy8=,tag:UTCCYg4VkZbxUZM7900ojg==,type:str]
type: ENC[AES256_GCM,data:sxPkt34I5paMigp/1/+mgHWlvWi5VdKD,iv:uFqgnJNzWpTv6auoqeAsvf/i5adI5jOg4EFD8AKsuEs=,tag:0DE4WP1Ga1Apk/r6uOt9rg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:dYra,iv:zaV3tsLPfKOqsBDjG4nMSHa5Wy1uTw1Sd6dP1f7Mg8Q=,tag:EjtdWE8JegumwqfvWfinFw==,type:str]
    password: ENC[AES256_GCM,data:YuhcsBQ7DcUZJnJFEg1KY97QrZMSA2aAs8Xm0Csc,iv:7oLsVSooNjSGqT2ZnI+Kj7ovOG76/4uZhZZm/JOyZec=,tag:n/vQJQSlL7lHafOZWZowzQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:gGqNV8NQ88pCcn2nYDFXwhMnVDEr01wn5qdTOa76,iv:jbQVIKMZWqunR8YybPREADVYAZQetj/kmRx3gWtLREY=,tag:3PfBKsS804EOHupPXY/ZAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OTg5ZHBNK2RYTEhueGhR
            ak1yOHhUd3hnQ1JSbEp6RDE2L1F4d1pFMmxVCnd3T1dyUHY0YlBRYkZ3aDg5R3pN
            WmV6UTJwc3lTekd0UGhnWjJsaDF6MGMKLS0tIENQVm1LRzhUU0lyNTR3NHhtaFZX
            aTBXUXJSa251UFhwOStIK3FuTEd2d28KSpnTam+gi+Dw9alKFnoy8u37OuJrAW8V
            2vx1rWVrlrLrpf5jjCrx3r7mbuolA3CnOTTRnxuWkrFVHR9U+kQm5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T06:35:07Z"
    mac: ENC[AES256_GCM,data:v20pfQ18BoNL/l7VQXEhrp6K5Il69eKunIKTMlNAtrALw6EaWVwDT2kXcJGv+yI5AxddHzpfqIo/0phtHW2ZPGL4ZXf0rWjoEgBzgaiNbevplQA4+vAPWmMAun5oDLUHHCK2K2E8BLmRaLBDy5GMDaH/hiJ/06rcDCeN0cqjynk=,iv:dOkNBuQ6BJFWkHgJ1TVAEeirbqlqwt8ywcbtb107lD8=,tag:kWWxznhRy9MuomacXvkByQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:vMA=,iv:cEcRG7Cb6BH5YvTyVulQBUyfiNfa/gXG3FZbIov4bhY=,tag:yuQIDizdc1jZVSLgMABMfw==,type:str]
kind: ENC[AES256_GCM,data:tek8oech,iv:FjKPMWv882YUyM3ghST2edNs4w7STuORhtpyTcWZXWU=,tag:SOD2mKWB2ctp5JE7p5HWPg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6EiZmTnesL/l9bbF5HA9,iv:56SCBmFYU/avO1eAWLgQNC1PKXGFJFqN8enuKf7TtCw=,tag:1qE1zMWcGrkF3N5DxdQuig==,type:str]
    namespace: ENC[AES256_GCM,data:XAZb,iv:qIhjQgDwWvrWSA8C1IDgBkU5jBJtnOYcfoNtJyc1dgo=,tag:NgzV02RVHcE/Ayi3MXGTcw==,type:str]
type: ENC[AES256_GCM,data:flWniGAQ,iv:2H0eRTMGeLKpB7ua4Gs2J1uWmEnFdFvfpsZBkhPOvQY=,tag:9biJWNPYCunJrGOMiD6tjg==,type:str]
stringData:
    #ENC[AES256_GCM,data:SoqYTkTf76gtRghbkqIyA1S/ceX8XSE3jT8OsQ9Tx9+eabanIWJmsnmYpgD+p/O9/ODGjr+KcM4/E8f/M8RhENtG/yuvPKXGVA==,iv:6HPT0qLpRe8T8BoDtGFl3JSC5sKjdAlgX9Z78g35SUU=,tag:+Y4K5UzZoO0PHXstAn4fjg==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:dA3ffXpTEM/utMDW8qyVcfCuL0vNV9fwYnGaaEXqCkOZJBfmz6pDMuhLZ8wj,iv:3BNbYL0TG7SjD8RZy/ovp/IILxrj1NI36Gp0iqdZdd8=,tag:378U63P177zHmeTvoshvMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OTg5ZHBNK2RYTEhueGhR
            ak1yOHhUd3hnQ1JSbEp6RDE2L1F4d1pFMmxVCnd3T1dyUHY0YlBRYkZ3aDg5R3pN
            WmV6UTJwc3lTekd0UGhnWjJsaDF6MGMKLS0tIENQVm1LRzhUU0lyNTR3NHhtaFZX
            aTBXUXJSa251UFhwOStIK3FuTEd2d28KSpnTam+gi+Dw9alKFnoy8u37OuJrAW8V
            2vx1rWVrlrLrpf5jjCrx3r7mbuolA3CnOTTRnxuWkrFVHR9U+kQm5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T06:35:07Z"
    mac: ENC[AES256_GCM,data:v20pfQ18BoNL/l7VQXEhrp6K5Il69eKunIKTMlNAtrALw6EaWVwDT2kXcJGv+yI5AxddHzpfqIo/0phtHW2ZPGL4ZXf0rWjoEgBzgaiNbevplQA4+vAPWmMAun5oDLUHHCK2K2E8BLmRaLBDy5GMDaH/hiJ/06rcDCeN0cqjynk=,iv:dOkNBuQ6BJFWkHgJ1TVAEeirbqlqwt8ywcbtb107lD8=,tag:kWWxznhRy9MuomacXvkByQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
