#ENC[AES256_GCM,data:P1+IxlUHok57H1Po5tli1yDi9e2lLwXyi2Vj6vRSdL+QjcT5R4WVrET/YAD1rWdPbOshMHiu,iv:aX1k4Jo60HNusSYv99/61lWxNRRQPft6HHSHP4tditg=,tag:FmywcV3kS9/CBlnrp4533g==,type:comment]
#ENC[AES256_GCM,data:qgns5FBsdnVfqNLOKVqJhJz9/wBVyX8EiObE5WNCa1JWz7T5C29buCcQkFKtp3Kl8bjCbNt6gZ3EfYY=,iv:DfWxjyNDKxKSsrbq1f3aUtHtey8I7L8SudVjJS3+2vY=,tag:noaajHbSVrGteqYKg/fLzw==,type:comment]
#ENC[AES256_GCM,data:P58QTJC6Iy+33BmmsNajdn2/Ont3KuC0PM2MKOHspz04eQhqnq5oUVcL/V/JVvUIIIcoFdIqGSU=,iv:/DGYJtgHMZ2eyhks9/g4bBBTRppuFbABQi7kNPSlids=,tag:iwEOJL0J1LSfz1oDtt4ybg==,type:comment]
#ENC[AES256_GCM,data:dQkWku/pXH40cYs/hDF10yL1AEXESUVLJVSiZODkTstnso2HKtQjLC6H8H/fRj35w0Oes+gI4cu/jl/xN6MVlnRW/ZQhi/AT4e4X1YUGQA==,iv:9fIRTp+73+4qPnULhBnskVzIU/zX62LIH55TPA7y/XY=,tag:Pzc2WGHQNaTSSJkspcOgaw==,type:comment]
#ENC[AES256_GCM,data:aEnph10AngEfiV6G1v69LyjRbpz43gOWhcQIjgu0dIMX3SMEsBECXYbTznKhQOMqxDbui6+D6RT0TfkbSwmUiKbDak6yXQdl2lR+oiBB2usH,iv:KU6IhujiSmu53xJAIxDB1GHoQ4GVwV0x5hqJ8IWnXro=,tag:LYSGuHjpUn0eDB4DmPlivQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:u+c=,iv:Cc2+TUGi7DkGgZklZVR5+K1m1CyfsTm6hXJjaE3spW4=,tag:QEI7KkiLXA9vB/lIFQ1/6Q==,type:str]
kind: ENC[AES256_GCM,data:BpxNxsLH,iv:kKZr0TMXccHjysYLlePI38FNmUEqN43gLELNAiEOI2k=,tag:zKNWEoo1hbVOSVQsmsyEAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iMb5ew6eXKP570sqwwAXiViFNfMHGLKI,iv:kFU0Xi5ZBJC5Eu/RcHvkKIYFsfcO0Hh34bbIuDP94BM=,tag:rvftTX1RgJ4kQ1qn9b3tEQ==,type:str]
    namespace: ENC[AES256_GCM,data:tqWo,iv:JBHX3nhuobASAbj/Ied1nL61RUdZLuJvxwpZKEDr8bk=,tag:4LFg2ulsTlJfzTXpC+VQIQ==,type:str]
type: ENC[AES256_GCM,data:rUpExHduwbuQvSCmxXnjPVyG01P/deNE,iv:5X6qjk2j0ATxdYukIFv7jmfFyUmPOGb6quPQXjXql5Q=,tag:WsF01tFGc9dAXBT4WZpK5g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:zOoe,iv:qf1fpQ6/+kOgY589zUDF/lZun58FPZaPIdRVY7dVPZw=,tag:HoTeifdH0v3+Ym9zWrEdog==,type:str]
    password: ENC[AES256_GCM,data:0vJUUw6DBqswVljqqQ2jXVygTvDvVHoir/vil0WV/5xUDz7hYzrE1v0BQ7z+O/3u,iv:VntyKbfcFhp5/yaVolRc9lTNQDR20hgZ4krmC+N9dcs=,tag:C09zPBA+gm06/mY9H30kuA==,type:str]
    postgres-password: ENC[AES256_GCM,data:3zdNYp+YfVxsB+mTDbvfAEpwZR7veZhQuQrIQzTh5/BcOZfW01FIaMSOg3OgLd7l,iv:nOlypWUc6rhlJSjhDKo/amiFERBNoknfQPJnKVM4tLY=,tag:P7T6jJduCjcPceiuC4Yj/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS0w2M3VHTytjdUpoOFBS
            WWZKYWlQTnRLb0Q0cTQ2V1MzcHh1Y0ppc1g0ClJLcDl5d1psTUJqNEpuVEtYR1FV
            dzBVbTFhakZMam05aFJjQUJMQTRBNEEKLS0tIGMrQm1ZZ1FMY2F5MzAvY3plVG4z
            Vm1NS1I0bXEvVEFhUE1wbWozY2VwdTQKP7Ue+TEfNC4FjQbY3Nx70P7poJUg0QZl
            7k51vujxXldqirS9aot8XdkJD/Hz42L2bMM3bRChZtyMCdW5CFSwQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZWdldjhOMUg2NVlGTVEw
            eUNlcmhiWFpLRmFkYXJQSTBiM041WmU0SzIwClcvVHJkTEZIS0lkam5VTUY1NERh
            cG5VbDR5M2tOei9JWEVvV2EyK2pVc1UKLS0tIHpvdEZyTzRscmZyOVJmTG9MY3Ri
            ajdUODBFcktZdjVhbmtBazN3NmMvdW8KtBtC82qdjR3LAVKYLUfkS7cTAMCgMZ+S
            CS/OOb2egHHZooI1n9o27HJIHfGzbOn/2ikSSPMNCLutjU3wjEE8pA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-03T08:17:16Z"
    mac: ENC[AES256_GCM,data:bGDE//BUMGfjoC8hQeMak54UbJok+IdoI3EyakYO8z1Ki6dWnUNicx1NCgMCV1nUH70Zo5kavwLnz/EPtKf0UcWl6jrVt0ihRNhP2EAB6HgdlRPB6GEulGBkvMhTTRDqY2nK5Pa9AFZ6+fdOTCp9FEU+gQcdDXu0WiICcByD8ko=,iv:xpaLs9qQ8g93rF/s02UcSKGhVasTTVVRFTqERfbbm64=,tag:Vamv4eHvtzZP042lnSbEMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:NS0=,iv:G/vOF52dVP8QkgxlPujVaBlROlYpbflEYK7LEalNp88=,tag:1jFAYFHzpKw17g6loXsJ3Q==,type:str]
kind: ENC[AES256_GCM,data:DxPnB+Py,iv:N5aW59lLNJrsa7Gx7DB0TnAM/b7YYv5k30wSgFj1re4=,tag:hRf/T1Ws5+G3IYzwYq1Tag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qkhA9tsqlxcKPUKlCBgQ,iv:+pJBFb+YF8tZx+L+VC5/mrb1hg8umWvA8CbxtlnMihU=,tag:EZ/w6Z3ZwsdR+MKcCjET4g==,type:str]
    namespace: ENC[AES256_GCM,data:E8Qj,iv:pNYG54g/5w1Os2Tp+6Ro+YMcsWi8zm35gOPN7isabwA=,tag:6kKt7wMb75iwZQ0CzWq+Zg==,type:str]
type: ENC[AES256_GCM,data:PTS9QJTI,iv:T9XvNSInbU/A82VFpxe5AowKNFRgz03ORIGssKDtwK4=,tag:pZ+Vc4rxdIVOD/PJ2gbB0Q==,type:str]
stringData:
    #ENC[AES256_GCM,data:eq2SH4URsA3tyn8eEs9IUo7ir1X6n9YrKIkPKEW5muUlnexDE/GVg3WOgGKps2u0AMzSMvJJLfPOuJ5sU2hm+yTdmj79+57Tng==,iv:9Bk+j/G0YeZY0oILPBXrBbqUM7JS3Z7N6nAC7ti9oBc=,tag:ebuBTb03PspN5GT3rQG6Cg==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:m9hc4/vDvSg1qS4E1z/WaCx7nFEnaFmktBdWJc2KmijjIB0uMdfTmSGO2c8Nc74sJoW4ZBIb+BVtMvq9mV4PLQ==,iv:h/tk9Tyv5hLkh6u9K8fVgu7TjyStK3umSe8tpeaAWJg=,tag:uF9ddM5B9pgAZpwwR/QDPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS0w2M3VHTytjdUpoOFBS
            WWZKYWlQTnRLb0Q0cTQ2V1MzcHh1Y0ppc1g0ClJLcDl5d1psTUJqNEpuVEtYR1FV
            dzBVbTFhakZMam05aFJjQUJMQTRBNEEKLS0tIGMrQm1ZZ1FMY2F5MzAvY3plVG4z
            Vm1NS1I0bXEvVEFhUE1wbWozY2VwdTQKP7Ue+TEfNC4FjQbY3Nx70P7poJUg0QZl
            7k51vujxXldqirS9aot8XdkJD/Hz42L2bMM3bRChZtyMCdW5CFSwQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZWdldjhOMUg2NVlGTVEw
            eUNlcmhiWFpLRmFkYXJQSTBiM041WmU0SzIwClcvVHJkTEZIS0lkam5VTUY1NERh
            cG5VbDR5M2tOei9JWEVvV2EyK2pVc1UKLS0tIHpvdEZyTzRscmZyOVJmTG9MY3Ri
            ajdUODBFcktZdjVhbmtBazN3NmMvdW8KtBtC82qdjR3LAVKYLUfkS7cTAMCgMZ+S
            CS/OOb2egHHZooI1n9o27HJIHfGzbOn/2ikSSPMNCLutjU3wjEE8pA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-03T08:17:16Z"
    mac: ENC[AES256_GCM,data:bGDE//BUMGfjoC8hQeMak54UbJok+IdoI3EyakYO8z1Ki6dWnUNicx1NCgMCV1nUH70Zo5kavwLnz/EPtKf0UcWl6jrVt0ihRNhP2EAB6HgdlRPB6GEulGBkvMhTTRDqY2nK5Pa9AFZ6+fdOTCp9FEU+gQcdDXu0WiICcByD8ko=,iv:xpaLs9qQ8g93rF/s02UcSKGhVasTTVVRFTqERfbbm64=,tag:Vamv4eHvtzZP042lnSbEMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
