apiVersion: valkey.io/v1alpha1
kind: Valkey
metadata:
  name: n8n-valkey
  namespace: n8n
spec:
  replicas: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: tns-csi-fast-nfs
        resources:
          requests:
            storage: 2Gi
