apiVersion: ENC[AES256_GCM,data:H0o=,iv:TBILqIR7Fz0c/NQ1hXDDM+kWqRY2b8xMowMAFNYDV7M=,tag:SmmHmZKDySh0TapfKA2DWA==,type:str]
kind: ENC[AES256_GCM,data:p+gfyFeR,iv:GMbHAO8gyokgoR1kXUBanJ0Cn0GrblDeKUs9cS4tVmA=,tag:KjeSM/e93mL7Cz7v7OqpDg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vLX5JLM+vwSl7TudNgs+lGhrDz/lJBIgVUvQ+fty,iv:IKEkkkkwFFnFfWZ6HDE1IgTpqIlys4YypqJ3Xiy+Vyk=,tag:7bViYWmGa9cyd0QAE1whmg==,type:str]
    namespace: ENC[AES256_GCM,data:DfMwzmd84f0=,iv:TPCXQwl56a3nS+95R5MI2THp91NMg0D2f10VYRXbR10=,tag:CK63VvXvkuVdY9tgd99Fvw==,type:str]
type: ENC[AES256_GCM,data:WmgQTjcY,iv:Cqg4s8hDxX1NZBifNJvCaYWFGHcztkMtMpFwLiKYo58=,tag:K2LiCzVrTPkBAPaIt7PCBA==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:uFh8nx14rFAq4QxMJckKcJH5zuQ=,iv:ZotZEvMkQJBm7O+USLZqmrBk+USyytUSwD7UZwtZSNE=,tag:avrjWJmQ2hGmeUyY0p1u2w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wxziC5RxV1xI/6bjvQAkVaPkwoEqxIVoO7w2NGaBOJ8nHlFXyFMV0A==,iv:+MnciIf0DQ2zwbto7zlgJX/AwKLmANuCBxrtoer8UMg=,tag:NHyXbBCBy37S2l1gYIs2kw==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:lag3Ig==,iv:TeL98nMSGcLqYXum8d9Kbs6rIhTv6IeYhjz8rW4NQWM=,tag:OCSVlneAzSnrmXd65K/u3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SWJUTVJaM2VkakdhR29M
            YW13QXBVNUsxVDFwT3FnMHVUeVlDUHBqTngwCmROVXNaLzUyQUFsWGtBdEU3YXg2
            RERMaElleG41L3Vyckswc0wwakJNUW8KLS0tIEs3K2JqN3lpM3JQbE1pQ3F4bkhH
            eStiQ1g3ZytBNEl0dkNMaTRHcEsyZVUKRKioenNGFqW0p6s77G5RaBJgVocu7ADl
            DT2Kud7s0G2wNjSNSEIBXKihiC25HH+APxbpI9/yLG3VVhBbNPpn/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NmpCWHN2TFlkb1M1ckhl
            RHY0R2o5T3VyaEF0VUo2SWFnYVRWYVBHaWhNCmxURi9PM004RlJwQnpyc09YVm9C
            L2dsLzJ1TWtxaE85RUEwOTlEVFQwaDgKLS0tIHAvODRVY0NkejY3b2p6QW5xWUE2
            TUVSZGkwcHZVQjNiZEVjUm5FRVVZUTgKfKSMs9VtdqlCpE2Ac263Qx78sTMVUhgn
            0aFWEoUkVacQzkPqnJ9K9yvLUpgwappnOxLP5Ellg5WYDp+VRaRaPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWlZBQmZqT29HVlZDUkVl
            L3BBWmx2MlRlbkFrQmZuWTQ4eU91UmdLMjE4Cm5GZktOeXpwOHNoZ29hSkxpVzN2
            VW9ybENEV2VxcWd1RHcyUEV0bkl6MTQKLS0tIGJjVnFBNThOUGY4WHlNdXd0Smgz
            M21BRVlOdmo0Z1p2aHI0MVczT1pKZzQKCREbXnOQrdGADV/5PkXzYZ9pNn504UT/
            C/Oo0AcW9ndutTuvw/qrGyYTgkPMjsgtiZu7OF4UGL6TXnnKjAvCCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-14T22:09:12Z"
    mac: ENC[AES256_GCM,data:Bagg09HjP36KPx8qQ1poZF+Nste6yL1E1BZRi1RdZg1eDQKalZg8x61R6lScfPHy38hn2jECh2CTzbZ0CBYs4Rv/u/6Iz2Ronbx4FuQVSOtQ0siHR2xv18zYGFflv6zWH7anAd1WaYpvWKMKp2FBzVEyhEW1ReF07aBhJ2CYuDI=,iv:be+A6Nrk8qV1RLXhH0n4htbBKssnimBKWYCdsZWAI7Y=,tag:y5CVE+YrUW3hG0m0zVIqnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
