apiVersion: ENC[AES256_GCM,data:xx0=,iv:X2eroo1FQrwialHm/egV+jDaNnXcRb+Q8wui6ajkDnU=,tag:ItVi/w0Xb2/PuJTaJpP24Q==,type:str]
kind: ENC[AES256_GCM,data:OjPmL64N,iv:0ytSfVKwP5cpqB4F9/rW0/pqNanZB002DRJby9TBnh8=,tag:gDckUuFP5Ahe1I3cjHCUtQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:n5myt3iubeONgVSsiiOJ,iv:/sTJ5OgoXnucYSvROFNENqoKg2LgX7fSHvdKg1Uy0/c=,tag:k/ZYssl2rm46lt9orZ04nQ==,type:str]
    namespace: ENC[AES256_GCM,data:wmNsM0W16uI=,iv:XM2+Mj6wLgqevgXO7MyWIxksz0Thg3tlwQcniZqgolc=,tag:EhZ4GzLSJn+rQc8gEbkquQ==,type:str]
type: ENC[AES256_GCM,data:nQBXrq8Y,iv:muT3JVyybcWxfdVB6cKI7NinYD5f1dmsJQuasY5MCcc=,tag:dqTZs+25f2lbV8FYSQEsyA==,type:str]
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:WzuFhEw38Wo+q7mC4NKVbDo3qnESaM2bIJkkTaBfT4Paftf5V7UATHaxFRUXk5Cd7SoH4Dxr8fHK+ZtFvbWCJQ==,iv:UHezldU0yH/GU6Hdn97FPB+QGlGvbNVdxpXnlO7GWBI=,tag:cL3+VSBrSOX2JnIdvTDk4g==,type:str]
    AUTH_AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:iDw+MoZm733KKZ0KVZXlJKY05B0Ypzyin8kdlJ+zIr57TQ5hVl6IrI/7l8+iTk4f25nWlI1mW8GdlJV6suJe5Q==,iv:C1i3cGEqziraVm5rdu2Aa6sluPBpp8vOyJasHAQEX6E=,tag:jskKja2HgSlWqSg7qTnI9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUjVrenczbXc4ZEFlVFQ0
            TzJCYUx0SjcwRE0yUE4vZ3poR1pxSS9vakJzCmNtNkpLaTlrT0NsVzlYcHNtcDdO
            cjZhRnBXMFhleE9TWklFNjg0RC92WGcKLS0tIENSYWszdHdYNEMzWndGc2VtSzBv
            dzgvSDNtd0V4K2pEUndGaGRQUzY5SUUKH5THikExQcivv7Lx5qvTyG4UNHX6uexd
            /EXsIzRrM7gRg9NE/sa+X0qliX+Uc10FP/2sQM3XHc4WGQb2BFHsng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRnNoZExXQi9tanB6RlB6
            YTAxZzlTZFlaZ1JwNFp4YnpqNmF5bHBQSUJnCjEveUZhRkF5eTFBWVA5TGtsNXpx
            cEw1NlFjWFY3VXJaVWZ0UG1NZ0w2bVkKLS0tIG16UzRibjJvN0VIT0tNVFVmbzd5
            YThFZDd2OEErdVFZS2xwTW00bi9uYU0KNgC1yooLmRKACpuU+onZggPEohQ9NfED
            P26OyEtYxhfUm5L+V6jK1T0KqYVsYCmgsamlC6mz+QUOTHVXZmVF4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UXU3N25LV3g1K1V5ZFQx
            Z2dCa214MnI4NGczeTdiVkJrdUN2dHl2T0JvCndRWWNUcCtzdFpYNjNLcHlBb2hy
            WGIvWXJMWEpKUkhWYnh6bW1FRWR3cDAKLS0tIHJ1a1YvSEdvci8venpYZ2RYN0Fa
            MTJqdHBndkJLNEF6T3M0VncrUm9NeW8K6NEcGZ8heag4eYD44bZpXZ+tEE0b2ajp
            c35GDPWOhQ6EyOrvJf2P8Qq0ncoSpz0jiPpbpDEejYHlxBAmgBTzlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-14T10:26:43Z"
    mac: ENC[AES256_GCM,data:ZXODKcuOFgzNnpgGm+pxmv3AqoVf2zI+ibcv+pQkwR7aF8oErmiB4f06REktmlnpNd8o2tqmX9qXhgipwl9L5BhAeBPwjpDnzBSQ9vupeHxpUrPCUlp2mA0Zznwa8ij1IxoEy/KCgXZeAGrYc4ZBn0XlI/0AOofbM1K7A4eyJaM=,iv:eD8LCZ/B8Dpx+aCEzSLOCVy/kRGFsJlmVh/cP9gNIHc=,tag:24HYtZ8WfRc7zYjUGfg6eQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
