apiVersion: ENC[AES256_GCM,data:siA=,iv:+FhJycg2B1v/Mvcx+DcSKsXQOtiS7cu24rbYHluwx94=,tag:IOBWZux/82LeX9pr5+GDEw==,type:str]
kind: ENC[AES256_GCM,data:clVm5Ul8,iv:Szai6meqW4rwFFcvan+xmT57HqfmOjY9/qdnpggWTcQ=,tag:lwpfaNNkH/CY6Z+gOFw6wA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d4glRh/m+/KQVxVqV7VpzxOrAwjDtKUDP1dgXCE=,iv:Eps1xHAOESQt5ZO/fdD3XntGW/QQHVIGW5pw2jingnM=,tag:1RLBP3TqgGU9peaD5xGTpA==,type:str]
    namespace: ENC[AES256_GCM,data:v92OITWGFa8=,iv:SHI7L/NmVGSAcWwkjuAL9MssRG+IrKWpWo1J8+lWJDs=,tag:CYtTfiYeZe7IPhf4MAkgpQ==,type:str]
type: ENC[AES256_GCM,data:HpIPURkb6zpHCqjav848qQ4+QwhfxILG,iv:zT0KrgBf4JhUyHRVtUrHpCtpYOwfs7kUsCvqArlwpSU=,tag:5uAGajc1ENU1LS1VW6/42Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:eJAkVmA1fWk=,iv:lTBIq7yMlp+boK98T+PGzzQSE2KPwN+puedsn8dE7Ds=,tag:q+5ooaAgJ1fho4W6XfV4KQ==,type:str]
    password: ENC[AES256_GCM,data:7U7ZXwZy2ZHCfTGiB8kSlEn23QKZResloM40hB7RmCDYImJzxAbPapjW8MYOvfQH,iv:zpjGu4zkT2XdCp/dZoqbnM6ET80tmes3ur1FlpCw2hc=,tag:SNcbXTrgXQ+44JSi3TINEA==,type:str]
    database: ENC[AES256_GCM,data:Zz3z+i2AleA=,iv:tMUnu1pIHPyn+mOWkVHWaYMi09f7FUBCwkKShY84IN0=,tag:LebIRHg4P14PQEN8uBHSHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d1BDOElTUmNtMk1TeDF5
            ZmlBNytmN1BVQlJZOHBTejhsOG9kaGIyOEhrCnM2Y2ZOMDc0WEJPTEdLQzg4Z0VP
            Qy9uUkYwN3ZBWkxzN1RRbXhTb3N6NGcKLS0tIHdEODU1NUw0U3NuR1MwNWJiaDkx
            UFRHQjJSSkF5Zi8xekZIeC9SYzVRaGcKV7BqwnP5Bqtwi+JhY5rvEyQZj51PC/+J
            icLpi1Sfp6J+MYNze3ZAGRnqCsn/z8ioRxfp1JGzezOowev2Il88Aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Q1FVdzY0Sk9mQ3hjKzRK
            NlVvODI2Y0RQWTlBNXhLMXFHU0x4N1BnRHdnCkYrL092aU1aY0hJMmcwUXJha01L
            Um00bkhrTFZKdWFGL3NJb1l4Vldwd1kKLS0tIE1KbExGSlowWUlqaEJJcDRSeGtD
            ZG9QRlFwVzlBQVRVS0VwYnI3NytaK0kK35W8ReyWEAZHOs8acSi03v38CiXqcVGg
            thfA4rOrhR7SGR8cy6iGIrHHjXyGJckjef/dhah/86NhjJkyArj37g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVUM2UzNuWTJldFhwLzJ1
            RzZub05hcUdWdWN4VjFabDRpRTR6ZHNzT21VCmFoTGxuSG42NnBuMFhMR1YvZmlN
            TTY5aldOMUh5ckdZaWxIaW9SWU4zbFEKLS0tIGtJbTdBOUxUbWFmSFFLcjJXOE9s
            d08vcURiaDFQb1hsa3dRM2NWSkkrSmMKRbRS/EvHPJDfY/t5UADKVZ7cg3n8jl1B
            AAtwVOfFrBzrgOerJdgLAZ9QqWnXY4ovFRhIbs9qbAdcq6wn6OOMgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-14T10:14:05Z"
    mac: ENC[AES256_GCM,data:Di1bjwsSz3DugsUJoeX6FbQNG+w8fFYjJTTFTytdl8GDyeo0/GdyJs7ougja4CB/OPymRjEZVfJ86P9Hg0sX74z/+JTJDKeynztVCxd3upOnE2M/oleIKiRDs8fPd1XnYy1honk992BwnV+482SXBDM6KXs1pkjtxNVD0KBChrk=,iv:+PSC5tJbPMWTQWbtgQZT2jEIMW3lXfv2ngnAk210dLw=,tag:L/FVEGBu4dKg/ve9tOgQIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
