#ENC[AES256_GCM,data:1RbdYNpK8qVTNxu/rEY9N2/lIkJnLzgtr6Ir1oaRGrDqC+70h/hZdfLmaJ4t213ZfySpBqBUKA5Dp7F/o/4jSjd1Jea1oA==,iv:Vu6dDGo2fFPfEfi22/n163Pw8CSeg5tqDXoTpJzA4jA=,tag:+OolkLLAUS2m1qxVyIh3xQ==,type:comment]
#ENC[AES256_GCM,data:fhZdUqqn/oBV+JCt7I3Z9Yc3Hc8ve5kbntm22GOVDR8pFtcYK+mKrwdk/07/R4Fe+rX4gPmweyEa8jd5n6zBBX9c4WUI6pUCrA+KMZ8R,iv:prRzyoNHwzQYeBu0scoXqMxHkHp+eU1Kl3MV69An83s=,tag:SGGx8DboYw+kfrQDqZSSmg==,type:comment]
#ENC[AES256_GCM,data:clPOdrwCFLYBVtSj+gCdWVueGGWsfmPlnXEbNG4uas/runUgleMaEVlWO2lAHoRRJyk7HJkasjC3NlxTnK6OrBH0YARtGpzytPHTTi8=,iv:tQoTxhJyIn7QVfITsIwLCrqJQjju6aDClp0qieo/rBU=,tag:gd3IBG9k0W0yuZ7kqUcOeQ==,type:comment]
#ENC[AES256_GCM,data:DgNWJqW+DcFokYkeA5fWIb6ol8c7opUn7NwneuqpYEwmabWSEDcgAuhc7O6J2Wgjeg==,iv:0FhKv95ujzkVRHyRqV70RzuDiidno8sXFNBPYTZ7M+0=,tag:crO7ri5aQ4Iy2EgvhFIHww==,type:comment]
apiVersion: ENC[AES256_GCM,data:RR4=,iv:rbD1OEu4KU0unOvyFTabXV9FsieEIzEGuisI1EfPoJA=,tag:RrkooNaox1Pv5F5oNaiPoQ==,type:str]
kind: ENC[AES256_GCM,data:tnnVBJUG,iv:DqjIXduz9t7Hlj/4BF55+oA1UG/DGBNybinbADRY10A=,tag:fz9Bir0Y5WOioxY2aSfXSg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:St8iFEzPMPacGfSGSnQHzPIuAXmA1w==,iv:x+xza7fqvDEvIjTAEy7KXuehZk8woOJMTT50+UXKZV8=,tag:Rjuuf7+Fs3bFNtHHcKgvoA==,type:str]
    namespace: ENC[AES256_GCM,data:p8RrYLJqCINXIcnJHHA=,iv:32U9TD0p9YM/NXmcr+I4GbWoN5OwCzXdH/HTaObl1Zc=,tag:DOohaRagrcGkNp51hxi0gw==,type:str]
type: ENC[AES256_GCM,data:laA9HQUy,iv:EfY+iC+hkXrBvo5whMk+tf9UvbH0WRxX3XVU8gtFJaw=,tag:0L9NsS4G5YTdCkP8vqMN6g==,type:str]
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:CgA/2qd+EAIBBb9KuKc0wfjJKvmk35qaExLJwyWKtjTLKGXTpNdParORDIvKYCB/1cE0R04+rQHdd3BzIpaKrFj/tA==,iv:5G9XlVShal+mhx/1SAXUdJxP6ey0sjKS8wgEsE8UMOo=,tag:5ABgx9dFoeIsiQsh0UYj8g==,type:str]
    FIRECRAWL_API_KEY: ENC[AES256_GCM,data:Dvgo0pljeHsyMhmuVMj9BXhnGQ==,iv:EFRYJJdxfLGYGt24XbK1z2bruYA/3IbgzgMX2SbgaqY=,tag:ks4guRgw0zMDXxIAFJzCfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQVdqYW9XTVdiWTBwN3Nq
            T1RKTXBIZDNVTytad1lzaHZJSGZlY25WQkVVClRzNmVhTndIUFFWTXlFeDBOOVFa
            TktTRjg1OUEzcW9CclFHK09USXpaeVEKLS0tIFFNcXVyMFhsQ3N4eVB4b0FCWGUr
            NzV2Y05UQXkvYnV0V0JoV0VQV3AyQ2sK46lR0MAVdrhcdIVunbpcRc9m6YWa4JMH
            2HZseJh8q4acdQKYxnY9UUmiVv9oaZrlrpGTEUr034nQu3LmfygCBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcHpTNDFDTjBGSGIzSHBz
            ZnVVOFFrRW44Zm1paUlkMmZnbkRGT0hmdEUwCjR3Rk51RE5aM2lQZk52N0hjSnNE
            cWtLWUpISUpDSmNXSEpZVStsMGh0TGsKLS0tIEVFL254M3hyRGlOY3Z1WmNwSGQr
            SnNlczdGRGxGbVBmanpmQmVBRUtNRGcK97LbLUpRnzUNMZS50eD5SWjrhUFnYdcq
            8pZ1ErrBqSgRVpkilZKfJ0lNE2nkWi7oOPwplYEy1OXSyYcXsUxiAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-12T10:04:20Z"
    mac: ENC[AES256_GCM,data:/UAUjgWLY3RyeeYcvuGHzVDL0XSPgMxVhTjGR0tZ58LbzpcYRNhKX0J9B8cmNG9kgKWZIzGY/naZFIlu9noLucYJ5JHhxrUR+CXXb4BEFUHEaAQ31bn491AMnm/9VBByK3b3Da3F3um1OGnshHvhv32MxiRUqXyQhhvUfEt2zDI=,iv:jrSNChbKIwHRJ2JL1EflBN4nm8qzmlatnnm2y4ZpPSQ=,tag:kFpy2MvUo90/y+/E76N1ug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
