apiVersion: ENC[AES256_GCM,data:zig=,iv:WypI42gRqt6I8+XRmg13QcJk9zOs47XDFdjMUYZpTb0=,tag:4lOfT6xN5h9r7DkbvSHDBw==,type:str]
kind: ENC[AES256_GCM,data:pqJw0YLZ,iv:GdQ/jbLq/wMVBvswKP2d+Fnw6KjwiuTrAjmt0b8KYWc=,tag://0rf6Dg/EwnJPd6o5zlkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zHN9noTLIoYHaoATnIZg4XVnaA==,iv:narBTKXncKCv2XegAG2CcXoG/yJpoMzGGJPJm0zjBDs=,tag:hCsMckf/ReaPwDhnrtFWqA==,type:str]
    namespace: ENC[AES256_GCM,data:Ecm+v32iXiGo,iv:th35SijbzQicZvUoePqypZ7XvFyXs9ghzxJcr8+yPUM=,tag:ytUNx6RpAxTE+8/3GrIU0Q==,type:str]
type: ENC[AES256_GCM,data:CDZ8Ixbh,iv:uuLDTye481lC197ubGtxYlFTNyT8GHxT9ZruVj0ODEY=,tag:eIM2R69DbdYfIQQJjTPASg==,type:str]
stringData:
    #ENC[AES256_GCM,data:hzaL2zXWmh+pzl6vE0/4mz0nR4WY14LI/BtoIMQChyNv4kBMNKFpJlVM40bvFq3kPLkbF9q6kNJZluqxS8Oe6sU=,iv:XVm5xSI+E3TRfkyqg4p0418wWQYAyQj2Sq5Ph6bpXBs=,tag:8FvFS6drFFqb7AMbCL+PQA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:C+5mt0R0CsNrbpRAp5HN1maMJag=,iv:b5fXWp91l/fULduk32jkmh4pWAAlCz0wslGvuRXlhSY=,tag:SKCWv3y4pRmHUHnQx3wcdw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1bRu/FNKpyXZTdul0SjFQX5fgw8AEANgSpix7PVz1id9G7CUsdIsqQ==,iv:+IS+tBGujtMM2E2gr0+InNkBBvgbXteQ7p6m7tV245U=,tag:jxI8xxgSQXEnP6qhX1F5/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVmxCeWExd05rZW95dncv
            dlo2NU94MFdQSzMxTnYyazh0N2FlUWh3WTM4CnNmUStCSkVvc0lzbXd5UW5SUWJx
            cFE4TWtaRWRQT3JCTUhLbXdJUkR0QUUKLS0tIFZXYkIxaThuR3ppckFWSllZaE1o
            MnVVREpEWjVha0M1bWdiVVdmeXE2L0EKUJMxQrCsNevyGoCYcJc6lzf08TJcVPiN
            d2q7ZneSghWtuLKs8sJEALqEJqeNyiMBYKgNCSsK4ZfVkMPk9d6U9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T06:21:57Z"
    mac: ENC[AES256_GCM,data:4UzGCEdnLviJ/LXl+gjSusSX0dF6lBdQAQp8KboQTju5f1nahBwBCkwp4scsNt4f5Od+GqSE7lGj6eRIifg6mtwnXxRw19L8MqsvWO109nbkwGOTmSg28rjbxBwjJYsTA8QM2fCr3zy7kNzo6grXlAf15q2ubPkq36hNI769UxE=,iv:3zTJscLhqjv1Ndv6CRaS3MyTaCF02OuEMhG6GH+5TXY=,tag:78e/kCnXBBvwXNuOhbEMvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
