apiVersion: ENC[AES256_GCM,data:Lqg=,iv:esly/xQZM7l5T2dnme219BOkJJY8pFPmFDp3LKehYxs=,tag:1FEXaCEHhEsE/7UlisvtVA==,type:str]
kind: ENC[AES256_GCM,data:tmN5D3gA,iv:9/PQxjc1Jo6r1iy99VidJRydksi0H9uhyVyTkfqADaw=,tag:Bmp8LjnWe++QZv4zQiJFWQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JiTmqjS1SCehAEAHCeoMEczPmg==,iv:q6BvPNN77EOfRq8Wu/7nafOdpKy/he92j0l9Yu9pl3M=,tag:ocebk1TuFo33LSG/k2f7rg==,type:str]
    namespace: ENC[AES256_GCM,data:C6srvMJinhe4,iv:KX15RCG4UkRMN8RVKwwyukVsvLMqRmLO2meGdLQNDCU=,tag:XFkHHvjIBd01lR9NLgnszQ==,type:str]
type: ENC[AES256_GCM,data:jIKs0mrZ,iv:9UX7Jnmv4iPRWmBUinJcRACq8GhDZajOopfTi2ujTl4=,tag:TNnxXaIo7GqCDePIgzTSyQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:D1dvS3Z18+1ZjPpEAfcgMIptLdmGP99Rgn6bko9F6ao0+b2Bxi4xQMWBorUME2e/flYz+LeA6V7aKlWn93mlk8DLYKqRWQ5f,iv:vcJI9qYuKYiD1eDZxrAfJuOhoX6ql7WL+DH+PBVMPrQ=,tag:fUXH4e9s2fYG7LbVVg18qg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zaf5EJUkadID5f30LMWY6AfBB4g=,iv:3zSTli+L34MjzGZyjbpmHts+oCKRstA07fPnYtLk9Sw=,tag:EE8kMAcgL593Xcwb7imadA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3kalkD7g9hX+Y7pFRCXVrJYQCBXCklgHWg17AFzr4tJK+pnN2aqD7g==,iv:C20cD/xNZ35Y1qhePV2Q6HwQF9LHbxlSPfcSWS3LhYw=,tag:e67RCDSx2fMCt1FHEnPS8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYzNtaHVxT0xHUTBhY3ox
            bFNRaWgxelpvLzE0OEQrUmJyZExoYi9LZ0F3CnI0SjVqOXdxQldwSGx5U2lpM2hL
            d2lQSmZ6cWpOdjY1RCtZWEpCKzVFU2cKLS0tIE10akpjL2Y4Znp2MW9FQmxHWnBJ
            YW1oN3BPcVRIUlF1M2tXaVI1dGk3R0kKpqYD+Bx4UOk9JhY+0PjlqLCMplG5RfME
            kLexrsJ/8+HuFfxNAPd1bGfLa/qqme63a9Lx5uJxLVmjmaHojmG8NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T08:10:23Z"
    mac: ENC[AES256_GCM,data:T1OWx+LgAiQA+A+zy2zC7DQS1GxE347HRvR561FZnooVrcJqPv7h8RynFPV4NQxq6RgO5tVuiwbH+2O7wDZYUzmm3Ig/Ge6VL1znNvlqgtfDVvI3PbZ9VDEiN/qczqFi8YSdPdoAmXIkgCWLkfeZ7Ac/3H/egelHeNS6GIXkue4=,iv:Z9VJpP/VSEBhMxLbZWmArKQzH4rXwWx15ubFtHlv1Vo=,tag:rADo5UcenG+B/FHNiqpTcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
