apiVersion: ENC[AES256_GCM,data:WmA=,iv:cAXA/zmfhGy1FzdeCc/xQZmE51HXaOIR3NJyiO6xqaA=,tag:cbEYom2NIojKQ2ljtT3DOA==,type:str]
kind: ENC[AES256_GCM,data:wr8+F/bW,iv:vKHJFJEI+GA86W1EArMWWvnTavKXRYu8OAV1F/c/shs=,tag:fvwO425D9kQas71/DsohVQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kzAer/T/yEbOrTtfpJSXgRs8Mw==,iv:k/5uYC2j0Ux80hMelzoazMWGYTtPG1NVOtBWrWMw0zw=,tag:rDUPcL9oPybXi3hr8z07IQ==,type:str]
    namespace: ENC[AES256_GCM,data:czR1LkQmGcaM,iv:f3w/0Yh5oUN7PEAlHYy3ZqD36eRxAoP4BC+vd+dn0gs=,tag:KFTcQ0yRSEJOrXFskyCAIw==,type:str]
type: ENC[AES256_GCM,data:1obca2QD,iv:k8/dtVEeX2PTr3pvZ0hubHPSC5fy1vx1MkNfei7k2/c=,tag:iaFFsjBmRxtwtXbf5fJM9Q==,type:str]
stringData:
    #ENC[AES256_GCM,data:bsp6cS5Ex3DCBo/Bt4ZAlo5URMg8GpDUbaTAPE4JQNVgJto1Mat/f6PTeV4Qf2qNYlp37I/mpdNZqFSmcrAL25JBrGc4kL4C8ehdDw==,iv:ECYMBhBfQB7T36b/s4JnxBxgYtMqRK6cxuywn20K4JM=,tag:qkzxRwQUf4vDXdET9OGKnA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MnFO8m4iciQ=,iv:NmxNmthB0cC6YFdC0PXkixKBR/NVK5/VRFPn/uhEDnA=,tag:0+AUGGNHLn9TqPTrd57GPA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7QUTyMgvfD4=,iv:C10AJk1r5cKEpNslITfrF1BNbUR7pKT/iaXYW0xOoeA=,tag:kwaJFC3gWBcUjyodl4lWwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWUhwSi95dE1COGZXZnZV
            MHhLMHpiQU5sZ0IxU1RnMjhLcUpTQnI1Y0NnCjhLS2lCVTF5YytPTzY3aG9sa1ZM
            NitXV3JFY1VYdENWQkxvMUh5dTdMK1EKLS0tIGRxYkJBOHFROUZmbnRPaGZ4YW50
            TSs1NzlBNkJWbHlDb01EcUI0MElqa28KAy2Pv9VrF95s5Hq+RD50/iSI9E2xVMKS
            QIEBk+FT/HF5HQLOBbUHIF3xRaAGl45b02VPuOZXYIGvuFvz3RPKWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T08:00:15Z"
    mac: ENC[AES256_GCM,data:eNKMXvg1m/OE6zhHZuEbAahVMM/ZzNhYBP0CAOtL75SY5JB2lGj5vI1vNoHmnI5S5NkWri/dYd3lDhD9/RAvvxryFMUhDNeJQ4tN3zfJJGBckQmbCsFQi/5mCZYsQks6NYU6MEVB90R2lKxtgJsZcoxXeQ1MIQMwTsRuUWL7uA0=,iv:SFpBRDRz8tsxAX8Ng33IgFqMYeoJUwoPRjkAf8nfJP8=,tag:25mQLlSMKWArApQU3Mnumg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
