apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - barman-objectstore.yaml
  - barman-s3.sops.yaml
  - scheduledbackup.yaml
  - valkey.yaml
  - secrets.sops.yaml
  - blueprint.yaml
  - proxy-blueprint.yaml
  - helmrelease.yaml
  - gateway.yaml
  - netbird.yaml
