apiVersion: ENC[AES256_GCM,data:2Xs=,iv:y+pjl1FzFWoaLtlO5D4ZvuVIiwbV28nHGECR5BH7Pa8=,tag:atLiaXferAv1ulUqu+8Hiw==,type:str]
kind: ENC[AES256_GCM,data:YGHOe7UK,iv:x/xGr+MzSJtFJRZlVZ/LIKaiBEHnVndTSrPVnLLk/aY=,tag:Iix4Qfv7y33TeSKbfR4SJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Z3tSXGF8J485dMvBIg7/g0mGV2Iitf5x,iv:wXMDMsSbN4xlMYnEShhGRiVLfRCSx4lhSaif28DBJKQ=,tag:J/ZEICQcYx19gafXKLkTSA==,type:str]
    namespace: ENC[AES256_GCM,data:ggQ3IqeE65gM,iv:ix7c7JlDI+N/SB+BZG5eh8JJNC9M/ByXrJu2LsY1CCU=,tag:LkJHA9ZxcN0BwXPKN/JgnA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Hjv24udNRH7D,iv:2kVgNsKnu+f2u+9vnLOV14/3gL4nr7j2YQ7a1LSx1gs=,tag:+IltoVAkXR/BKv2NNkh9+g==,type:str]
    password: ENC[AES256_GCM,data:GiQ2DZ0Nh7bximYG0bZy41UARw==,iv:VBfcmMtsVQsqxt2qvD7h1sfudlnMnANUOG0/vEY7Cic=,tag:uDn+2YAG2FbcalV0rM8v/Q==,type:str]
    policies: ENC[AES256_GCM,data:ccJnx1f5a4J9SGvAQYUKqA==,iv:FFfTzTd0NOGnwdVCbXS1Re8JeRBBzABbvDbxINzYR2c=,tag:5Fy70AFZaV7GjCyzr7UO0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseFpRcXlodkhEOXpreWxm
            T1p2VUs2RzhnVzNNUkNmOEV3U0ZyUE03R2pJClhCMkhLL09JMWlrLzI3NE5zYlha
            U0w1dDd0ekZJaSs2aXBYSjZQQXBYUTQKLS0tIHgvODkwQlA2ZjgxVE50cVo0WFhZ
            L0JUNGdXUXl3N2JkL01tNU5MbGMxMDAKfq+li4FnfqV/tLpwSa0/4quf+oM8dQOP
            En8IXopE/3KjV2ZaMdj4VhvHFycEHzP5WjZIQoVBPTCnq8yMHuW4IQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-02T11:35:23Z"
    mac: ENC[AES256_GCM,data:sAVAvStqlO14aqiSvRv2f8VeIknCz2TWAbVOTB2Obbt6XV93Aq3Cx7hk5lOGirBLCsTKftI8RBIOXb+6ut7wU0p2D57REUjCVvesVZuYYoZszuoZuVg871UIQx2Hw267TYeDwyDrA5e5vYYY4UEebXop1ExHcTbEl9uwomZ58QE=,iv:2RioPdmLzhJtPlhXrEogS4kmut2L2C7dLQMzLhk7ItQ=,tag:EGnZtOrkiUe6I3r/l1obTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
