apiVersion: ENC[AES256_GCM,data:FDw=,iv:56t6A+r7ccuZ80t8YSQfcihKrqephebYJRzU5hCvSE4=,tag:gw4LCIa9pQY2D3hByqSQlg==,type:str]
kind: ENC[AES256_GCM,data:TB74mG2i,iv:CbqSVnyI+8ohaZEfUopALm3Tt7tEebRAzm0v9q9xIFI=,tag:Ytk+siV/sowGm3JuHF2deA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4De32Z6A0stt3jfkgQ9wwB4=,iv:qPaFUHQ6srcEOUi4r3YTYebs7ElpLVXE7OBP3UyvF7Y=,tag:ZKA8UfkZAHlRIaNhDy+5ag==,type:str]
    namespace: ENC[AES256_GCM,data:a+v7SotyavBa,iv:mvE6KHs/sqoGP3IfLh4nYwiR9nizCN4kiFKJLgtH7go=,tag:wRS/f1vd2crCqV5vwjuIpg==,type:str]
type: ENC[AES256_GCM,data:FOuuSX7h,iv:9xeQlWqxopUlZo4uW+BFIwwduOKVyagGwzjGg8MiD7E=,tag:Dfg4ReF8hgmSwPAVmU72+Q==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:tQHGrsoPFHlmrVFC7IXfLckRwJNtPegKqxcpjcOo3qlRpGxIe24PZGkx5FyDWcS65bQaXMIEtgg6Y0qJ5wFZDQ==,iv:1fo5xq4YGaW9fJqjQECBSLD2DV4w6vqUgyENgWUl0tU=,tag:N3w1nSXEIxAPeBkweAQj9w==,type:str]
    #ENC[AES256_GCM,data:RlzpmH6Cz6iHdQV49AwB5dMokA7uI2sRpbT6PJ3kznt/b7du8jzwf4JXwxBEN+Ou2S+kmlnSu51ZeCjN0411WDWHQuU=,iv:N9MCKG5j3PPpa3J1pJwHNqCW962AIM2LxhRanzxm8qs=,tag:jDRN7KqZLuJRr/rozNcU2w==,type:comment]
    #ENC[AES256_GCM,data:TbW2nD3xywOJgI/5nyUVfg+/lZUZQkjC7wkfssKJlPI182VZm/BZPY6sRVI7ZvtXckVCipjYPsKv0p1pTzKAbh0OgHkPEcg3uQ==,iv:vJXDvLr1Vah4ZzasLbtHpexU3pUB4ASwT94tuDfgCrg=,tag:8f09Sbl4EDpfS58FyucSkg==,type:comment]
    #ENC[AES256_GCM,data:fQPPWj0H6+oWQMiXM0SU+1bVVqL9fZ0ZF6WWAAopgoYs6hQC11Ldu823ASlmDh4RdfuNRc6Iht47M40QTXBTHUBsJw==,iv:DQUll7Vkw5DIUlrQ+62PD+w9TsIR+Zuq5IK4lAeCUzE=,tag:FWi/ok9R5V+0/LFQPStBNQ==,type:comment]
    grafana-oauth-client-secret: ENC[AES256_GCM,data:hgxXYgEkAA/RazUYiqBUvx5QBXk0wlTwOKAEfJDsmjSgVkM2TNDZCh+E1nKvGMdGf+x647yothJ0nVGocRSGBQ==,iv:qHW93hxFkgA48RXVWr/iRZ4EhVLQZQ5qvhgIbsbkVHY=,tag:ZTRppqupD41Acj4zeYuCug==,type:str]
    litellm-oauth-client-secret: ENC[AES256_GCM,data:4dQtPMOJOJtdEqlniN57GIsjlXD7nmqDfrj+m/9SEDTF1rZagEk+1Objcg88uHXKcA3RooIJ815A2WYjzeNyoQ==,iv:ZP54xcoC73f3/d816j6IVhbx9TM7BDkoXZfVnlyBJ8g=,tag:O5P2drS4kv2oAEvVe8Vf8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTllLb3Q1NEd3QlVIMjdI
            QjhJSUp3L2x5eFJLZkJJY25COGtKVCtIT1VFCjE0QS94SXBwWUpxek5xM3lmaVZL
            U24wcTd4dm5sQ3hRdG9ydWk2MTdiZGMKLS0tIGVGeXFObUNkM3R4RURYWUpWcDNi
            RVkwd09aUG93Ulh5ZzVsakFzV0o2MmMKIWTb430In5OR/Ex9ouTrpFWcMa3CGbBu
            vx38wUSJAoAr5TVivaZS5YHz9/aY0s1gJ1aPVJg5XzvhgYsEdBMnNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T08:48:34Z"
    mac: ENC[AES256_GCM,data:AcpUuFahWF1crX+6z4iEF9Nzz7Z8hE3aoojbrSmx6lzQV2qwZjmgxVFMFVA4txpStxFEugdIMGQSMH/2XcCsqUgvsaKqt1YEKbr5Tl63ppKn5+6c/nLQTQrJdfgCOE/OecKhMjPvbfzQSq6iVPYYQ+u9LoPs0zGzr//+YVaTq0U=,iv:i7Wo175fiNyxcnDmGcWoOHL+zZ1g4AGX9N1NJ7QTWB0=,tag:RThRxEWkYMr+yDVDcc47Aw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
