apiVersion: ENC[AES256_GCM,data:HHc=,iv:rUhMynpVevvi791ilJOn5+rDhqpCgQSrpV/A97BIOso=,tag:YeYnd5/78DxfzYKGF/1+AA==,type:str]
kind: ENC[AES256_GCM,data:pV4lh3mh,iv:MK/YHFF/MJddu8+27qLu73p5+oFsl0JsoDmtLIBnU9g=,tag:Ir3qlrasiBBP54RIblXNXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GqcA/uqgOR+KZGRs2fEffx8=,iv:RpiIX2ILesvpsQU1Wq7oRGlIxbBBrBiZn1PoKLEFfJI=,tag:9MDNmREQFMau15JrNXK0ow==,type:str]
    namespace: ENC[AES256_GCM,data:pWpmiCQdz66G,iv:G2onvMW8wH5tv1jPS0n1Tu9QrE0i9PumKAPnRv90670=,tag:bZ81h6W3sMq9HUekmgLhvQ==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:OU6z5ZqyhIKZUIzIWIXSokdFC3mbmcozuratkrv7D6vhqKeyotaLhbilfD3GnulYvhVTPLbkr/0Zr2OsI8MD/A==,iv:y8h/36oejxnlXAqdJf/MjdFWECKS9oSlA4nA856WGRE=,tag:cn/hxdHhDm4gnoPMRgVXZQ==,type:str]
    authentik-bouncer-key: ENC[AES256_GCM,data:gAE4/3XIWgGf+B0khvDDeyYoSqOLxz+4GS21QZrxxvF/Jq30/RAzDd4/dPmBdL6qvBOUjw2dkjvs5SOvEbhywQ==,iv:3n4q62xVeSJXp/9qeXLtDvH8pWy2mH9Pg1xv1CgNoyk=,tag:4fiTxHw04crbT/ooPBG7cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZ2pzVlhwNDZqckpIOTFU
            akR0SExaNXB5Wkg0Y3lweHBIVzJaeHBHV1FBCjBZM1Z5YVBRYUN4K0hFOTR6cnM1
            a3NBS0xnRVU5MDFzYklIZ0FJU2dlaFEKLS0tIDRMUDJFRlRrdU1MbGp5Z2U2dUR6
            aS95VU9UNU1WTDhpSmlvWVNZNm1LOHcKsuDGdeflM7+K23viDxQmS5cbdfseZGxf
            nzqx1cxT+9pFLRiHiITede12pCKpat5iDug4xkcLFgZIVtHOhotxYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-05-28T08:56:55Z"
    mac: ENC[AES256_GCM,data:Iiw0AWc75sjYVOenfSEM+3pu2RZZDbnGgbZRZnIYdlTGRSY0Vxm7CjHOPJAqjjdVqXGCR4Yk4v6uq37a906YE73xpuJNmhaurnMPM32WMdaqmejohJqR07hWBEzrOKRcLKdlBpvvrT7Vao6O9ysRknGbRlTSMg7vtMIE+IqSZfc=,iv:OFAOhb+M2CFe2bfBH6SfzhX2xQEeyhMdn4Lrvi2VzUs=,tag:cCD1Fl9k+iHNlTElampT9w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
