apiVersion: ENC[AES256_GCM,data:aNg=,iv:viF8mUTW563XfMEdi2NMCzMo6pJ0T2JfyHHXywuEQs4=,tag:HpUgXD/Cga3keQKOqwrRfg==,type:str]
kind: ENC[AES256_GCM,data:7C2atc2X,iv:eoJGZ2qU9FHZZdJGwozLvrcCUaxtjLQMU4VFC7PHZoA=,tag:PL+HGM9NgwMH8z166s+J7A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Kfr6Cillxyul6nxnjtbt,iv:riT2UFR0wZm54nFeVKp6JIRlSpZN4GpCh0O5Say031Q=,tag:mw3g2GWPVle50+pnelm8zQ==,type:str]
    namespace: ENC[AES256_GCM,data:Z4OJChqJPw==,iv:zk8LUncdZeIVW7loMzhzkxt8usD8XOydbu43jGz216c=,tag:Ipva3Bk5fxcHDl9FCZIHew==,type:str]
type: ENC[AES256_GCM,data:AUuHZHcU,iv:A7Ib8pWHPq8CJyX/ElhxrTkvagYuKlu8/NvypKukvMs=,tag:udUZxl5sATsd68vsDgKpQA==,type:str]
stringData:
    #ENC[AES256_GCM,data:bcnwzYP4q8A8Hz2l9r8wWNGHCm2YhANE4b+Qs2LxsDgTslxaJ6F+O6Xlxk31lhq8eBHJwxLkYkSjDz/3WiK1hrCHQvgcYFcV66o=,iv:DDhEvq3Y17EKqK4ScBSjHwzbTFvIe3NOSdSvbdtiiyw=,tag:xEUNMEw/A+Po1adDowZDtQ==,type:comment]
    #ENC[AES256_GCM,data:rxTwn1Hpdv2UlOmL4hNFlF0B77D8Sh0HSYiDfGwew4Kxpruvhj+3zoJ+jZWA6KCHMAWJnC1dng==,iv:Ooq5DmtvCMNLUyySpPrIjWZbIMko3LoAyjPAp+gZAyI=,tag:/azzf0KrjVCtImcnATlkuQ==,type:comment]
    secret-key: ENC[AES256_GCM,data:GBGET6JuFGcdfeKxcmHXEVQxakoK8NVWyv3q0c66CIPSmihDJFDw5wfSNyeM0LkisqFMyqxZzmAr6OazexVXbw==,iv:8pe25Wbo1xJ69GMmaJ17Fcc1v943yJ7ZkpGWgBP1reo=,tag:cVwhuFAjcCRJ1fEzDiDqzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnd1J5QlV2TXRjTE9xckhW
            Zk1yOERsTWJRQWYyYlBxSHFkR05TbzI2SnlRCmljc3hQOU1aeDF1N1hUVUFVN3VY
            cXFBM1RaTlh5U2FtR0RtMElTZ2lJY1UKLS0tIFA1Q1Axa3Q4eFJSMzN3NWN2R2dn
            MzVhaHZHZE53SUZLQkU2Z0xra3k2SlEK/U9ozbmpFpbs7onLrkakf3RbqHuKBgJV
            DYjMKn6AMoHk17BSK1GWysQ0TGhC9rDo7AWbY3EDWXWIH6vqp2fHvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T08:17:16Z"
    mac: ENC[AES256_GCM,data:cqSqlsGOYJ7wAzT/Dc2cqXo562n0DctNbAuk5YImlpEQDtRlt9GT0Z0ZGE8K4GdCMASAn+cE+Ysxsy5VMaaVMeCFiGeaEyFYgg6sVXm0PY/+2Zklf04hFlNt2ZASlLeqfI14T7abC5+1LcX56nqdhYvNkVUid/0aqp81AfXVp/I=,iv:o8CBqNmk46VrQEBgPIPIiKNn4FpbEmqFJMjbGKz9+Mc=,tag:Ax53JyZSUJdQSByawdMHMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
