apiVersion: ENC[AES256_GCM,data:vgc=,iv:Kwh2VLRG/eW9FEeF6FzifR0bzk4iNRPOw47UKm/NyJY=,tag:lAr3QnBgMvB/HfrfDZG2Uw==,type:str]
kind: ENC[AES256_GCM,data:BmEVQksC,iv:Dw7g85qQWf+Rj4DaPLoZzDF0Ao4C99h1PhX0RLgzXj8=,tag:Sc6avVRaH1fHGzAW3658hQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FmQMjpkxDU9rs2ASesWGBbZWnaeTvOnsDqF9kXqL,iv:jAey9kgrvHqtt17W9EfzVMkF4biH+z/MdYZ2/BFmTOs=,tag:9vqqGm7ijGjp7C0O/H4ZRw==,type:str]
    namespace: ENC[AES256_GCM,data:8Ky/L2iQF265,iv:TWtNhqDHFthxN7vtEgZdFdPzFcTds4hhPp2xZnRJbSI=,tag:mn09/hawZ2vYy25mLy/LKQ==,type:str]
type: ENC[AES256_GCM,data:+GwyGJzyY3p0ZEME5XwgEIw7lyUrSCk3,iv:29HKe4FptJFO5YewkAyHwS6fzwLJuD7lmYMuit0ivM8=,tag:fKDZIymR4DlNwHLZh7YHyg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:AQW9n/zgm+IP,iv:e/EbwcmYWMDYJR4ag/zMoBbv//KWCQznM6F4NIGDQL0=,tag:xlO581ReL99RX824wYrnFQ==,type:str]
    password: ENC[AES256_GCM,data:zr22d/1jVInTh2z1laadcoafB+cSjIklZ0gwusUW3AhTlXWeuBumLJPf7ubnKdAK,iv:l9R2K2D0YuGwAjHvrfvCFsLN1RQASU6TYT2l1EjCn0s=,tag:+ypFHkQBroG0sxPNuEKV6Q==,type:str]
    postgres-password: ENC[AES256_GCM,data:QYXLAYWR9Cc8Hk82cUku+ByrcHXdXL/mSOEA6dLwln040ywNKOilC2H9oP6uL8SV,iv:HfGwvyjjmg45bX9q8iUBLR+eP8YwZWRQYlSqIhEzOMI=,tag:p08EUGUcKorpdlewg4mc0Q==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:jltmRZriYjzj+Q9cCbe9DQDd5oryHn8R8vlAvVJ8zty7YyGXjINq3yAWDGI7KpNQa3UEexC/Ugl/AdG1Ze6b4g==,iv:6tovho9cfNBt7nAVKPFwcScZ6RZUJGl5jw3ClDJTi/A=,tag:4NuVdV9lcbSVEp6Oy4IcqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalNFdVRHZHhRMFlvYThB
            UjdzN1ZPZnN4Zk81N2lZSisvR1l0V0UyZDBjCmxDSU1DWHZUQjY0R1J5QktZN0Ji
            bGZjRTI5cG5WMEYvM2lNZDZwaE93LzAKLS0tIFhabnJUbis3S2IvTmdjTVk1Y0xS
            Zm5zOGRHeG13UkVzRThpVjM2bWtldW8KJynj+scOUPKL/wRDiNyRKhE/UdKb1nps
            za4F4xY0p3mRkO81CBCd7pOp02pq2j5G3mB4iXxaLJ41rYsTuHqtnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YlF6TldmMWliNGJyOHlZ
            STV6M2x1SzZtM1dGRUtCRUN1NzJVSzFmaG40CnE3TUtUUjFpNytkdnZrNVRZYTZF
            RGFKS0c3d3lLTXhJTmlDTVc5cmhzTGsKLS0tIEp3WkxROFJxajhlazhoZ1BIZGF4
            RjM4K1lMazJRaVNmLy9iRlhIZ29nUHcK3fviDQ9hVXzj1FdZEhOU3dKLqYc6RjXb
            HMbaqn3gR48Ja8xO3wxYO53N0qEeoJasEBqURnmUASwTXDcFhp6BEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-14T08:38:53Z"
    mac: ENC[AES256_GCM,data:8EVwZptr2P4mSESUIqvLZmR4iHQMaMHa3qlZQ8jHCev6DBT1FacVRVvqkOkKK7eqGZ+6qdgKfjj1lERgbF3ZKwUf4N2aUdzXDcAWVt8oH+47btUWszeLkbKhLeGFFB8K5l6lxGOFY4dKmIax1ojzA16qSukG+Rx0s2RFz+e3BPU=,iv:YFT8h0TTyV2j56GawNMRheGWMfyBhSITvN8HOkjH+yQ=,tag:bR7TThhMlJqThkIFrJ+x0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:vgc=,iv:Kwh2VLRG/eW9FEeF6FzifR0bzk4iNRPOw47UKm/NyJY=,tag:lAr3QnBgMvB/HfrfDZG2Uw==,type:str]
kind: ENC[AES256_GCM,data:BmEVQksC,iv:Dw7g85qQWf+Rj4DaPLoZzDF0Ao4C99h1PhX0RLgzXj8=,tag:Sc6avVRaH1fHGzAW3658hQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uA1Hnztf4PjikJ/JdFBo4X1y,iv:+829ORPrIh3TKIsNVw+0e9YxrHMjgqy37vaP86gEDaw=,tag:2tAbfXii4lRKavPFlScYqg==,type:str]
    namespace: ENC[AES256_GCM,data:8Ky/L2iQF265,iv:TWtNhqDHFthxN7vtEgZdFdPzFcTds4hhPp2xZnRJbSI=,tag:mn09/hawZ2vYy25mLy/LKQ==,type:str]
type: ENC[AES256_GCM,data:OJGR2SnL,iv:TbpxypxWY01Q2xlfPkbTIQzQvx7cnPaytYpcwVJpjB8=,tag:Gcegft5+hSonFz5T8rLycg==,type:str]
stringData:
    #ENC[AES256_GCM,data:SG5JQ97+WPC9wKXr2sRQ9rSYoSILDPRUih0hnfncb5XtINtaiOR6mwDDhhNwMlyZj7pQ0MQfTjSiUek=,iv:mUghas5cJs2adRbPjlD2G7Dud1sizH/kldPpkPKEqvE=,tag:d4lYZBsuQOwnK/UJJXwrFg==,type:comment]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:ffG/ElFvoXrL2QiLojI3qj/mwhG5PMv8bdGVG60uuHq7ZRvxsMGPGZW13ztv6ghPz+U6qiEsFZhRZFrpf8cUKA==,iv:BeEYgkmAecyjd78vUF4miNmiM/w0uNzlrXkl6q/2/Fw=,tag:3HIB+qpOXmnZxm3+4OiACw==,type:str]
    #ENC[AES256_GCM,data:XUTwzUCdcnJFV0XQN2fBv6C9/j3R3SxYmGypT/R/y/ZPl4Y+Wk1/MVsNDnas14Etk4MBLN++2kEKvtjIT3ue0FUemiWPruOmywSduw==,iv:bMN1vjz1PL+CLUjiX/Xa1srrH3t+Hbrdv5yJgYXTTK8=,tag:QvGDfKRWkxj+WlxUq7ZfdQ==,type:comment]
    #ENC[AES256_GCM,data:nQ5DzIM+ttjU4NJM0/84DcSSUarky4k4gIiAen6rK7Q6DWBa+QPLAqOPuc5asquJa+DcrKNRWZCC,iv:spRcR5Vr6xK9pEXsMwRlBntSV8OpsdaQbMlN4c9NrGY=,tag:5ApbfYRBu3mcCdvD4dznUg==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:CLgk5sfHjA==,iv:E6Yvu1xO1eWGdkGp+DuXxInk313V4zDZnG8Il+S91z8=,tag:SIV6A4dPUBDgWfhkxZyXgA==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:RwWnFSQEDg==,iv:qZ/TeuE46BA3Vx19Hy7H3FymW5fDMCG/YVCvaKziu08=,tag:rdztLS/QgeOU/hSI3TNBhA==,type:str]
    #ENC[AES256_GCM,data:mUgAXyV/UIucx/ioMSLNLKLfVq5KUqeB4yKJM7wOUyFfUgBCUVfLPFB5/AwiDUC1GWZFeSXVmQm7ZVA7X58zfatS4/sxNzLjGEQ=,iv:buaeUzrTq9y9KE4cQre5pdV8L7JpkR3fIATZZHBCIX8=,tag:LMTPQKY9SV+RFmKIRXle/g==,type:comment]
    PGVECTOR_DB_URL: ENC[AES256_GCM,data:nU+pX7OdkOVkXuX37fpTtQvR0i/bcS5fLNyfxmWDw3cadODeIWoJ2izaN8wiXTsMOWWT/stPlkgXUC2vVOEeaV0gpv6OnnrXGNyBxBnnKbMTA+P7hS0G6WDPZWzbgMIRUkjHQoeOTGgKVJghaaJo27t31QosElJFHlSxrruc1JvDQ59x5oAUXw==,iv:IYz2ZVZTg5i8Yx/VghjE8qrlumdl/i2jlCo8nwSNsPg=,tag:ixtamiiRSYtRu4/PcGuFlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalNFdVRHZHhRMFlvYThB
            UjdzN1ZPZnN4Zk81N2lZSisvR1l0V0UyZDBjCmxDSU1DWHZUQjY0R1J5QktZN0Ji
            bGZjRTI5cG5WMEYvM2lNZDZwaE93LzAKLS0tIFhabnJUbis3S2IvTmdjTVk1Y0xS
            Zm5zOGRHeG13UkVzRThpVjM2bWtldW8KJynj+scOUPKL/wRDiNyRKhE/UdKb1nps
            za4F4xY0p3mRkO81CBCd7pOp02pq2j5G3mB4iXxaLJ41rYsTuHqtnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YlF6TldmMWliNGJyOHlZ
            STV6M2x1SzZtM1dGRUtCRUN1NzJVSzFmaG40CnE3TUtUUjFpNytkdnZrNVRZYTZF
            RGFKS0c3d3lLTXhJTmlDTVc5cmhzTGsKLS0tIEp3WkxROFJxajhlazhoZ1BIZGF4
            RjM4K1lMazJRaVNmLy9iRlhIZ29nUHcK3fviDQ9hVXzj1FdZEhOU3dKLqYc6RjXb
            HMbaqn3gR48Ja8xO3wxYO53N0qEeoJasEBqURnmUASwTXDcFhp6BEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-14T08:38:53Z"
    mac: ENC[AES256_GCM,data:8EVwZptr2P4mSESUIqvLZmR4iHQMaMHa3qlZQ8jHCev6DBT1FacVRVvqkOkKK7eqGZ+6qdgKfjj1lERgbF3ZKwUf4N2aUdzXDcAWVt8oH+47btUWszeLkbKhLeGFFB8K5l6lxGOFY4dKmIax1ojzA16qSukG+Rx0s2RFz+e3BPU=,iv:YFT8h0TTyV2j56GawNMRheGWMfyBhSITvN8HOkjH+yQ=,tag:bR7TThhMlJqThkIFrJ+x0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
