apiVersion: ENC[AES256_GCM,data:FVg=,iv:27+lbKN+zDz+PqF+EA/cK/SaufjQhaXDchurUmPY1tQ=,tag:q6s+rGlP62bD5UJiPW3eog==,type:str]
kind: ENC[AES256_GCM,data:lYgrQF33,iv:MPWIFoy7ij48MH7n2Lbmq5CgnT+hprKvSbSlWlo40Ns=,tag:l8zI9gE5lMZFePg5mplXrg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2CyX0ASuwg+INp8zhfqQzS8kdA==,iv:eWBFw0HHdsQ2EgeHTm50iSDxusMEwLT+gjzvcsqim4I=,tag:j9Q5CSr7c/GosGuW+EtpNQ==,type:str]
    namespace: ENC[AES256_GCM,data:aB9UFDtjxw==,iv:ilGu9gogeqX9vQ+6fffRbcpfRtfPg5fvzskt1OZ+NWQ=,tag:uj/j2+bcV4V1wPHneyQ8kA==,type:str]
type: ENC[AES256_GCM,data:Je6HCmBN,iv:fQR7+hBmwOSm2UIHZLgNIBZdgn5m/E/0Li8t1B+ayNk=,tag:1Ah/IpkHCHgkA8UcXgrvaw==,type:str]
stringData:
    apiKey: ENC[AES256_GCM,data:qNyklXbZq2pSiNbg+DLrL/yPvOPUSkDYO5m5O0esiNrjhhrDUZCI3eEficZcRpNWIlqGxTL+J50jd0FdEEhgOiIz,iv:U0XqUZdTgsU+iYRM9TRKYKhncBiv86G7dTYUbKdVJAw=,tag:Ai//5VTyoaOBRSP1Wg0YQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN3lHOS96Zm4xSUw4bGgr
            YXlBSlJjb2U0QVkvY1p1cDMrYU5wdU9mSlhFClpQa2dhZHZMNUFUWW90NDRPdlBG
            VXlxNUExY3NIR2VLT1JFOEVYNFdMaHcKLS0tIFNJY1NVYzNaMjVPek9FWnkwdDNJ
            WmlmWUY3d3dqcDUrbGgyNlpIdGNqV0kKf9fPTWJnDojVN4oLgEGnNSZgsfgXvDcV
            jLZfQMGJy3kQ7oD5O1nWPt8fhyrFQoN+iUCzHHU1w7k7Hg9QBRGeUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZCtlWlFkYXhqdS9rYXho
            RmpXWFB0WFp0a3JaN0dzc2RlSkluMDlBTFdzCkdXeXhMcVpXOXJ5ZzNYLzNVMWh4
            cmNIK09laldSK1RsOXdheHJPd20rbTQKLS0tIGF6UzZTM3p0SFhDTzl2OEVFeXBZ
            TnlJR1l0dnVpU21vMjB5S1B6eTBLZG8Kdr90iWphnvo21qMnj2im6TRxDJHsgE/n
            eGFOVZOCKFalrvMULdX/OGOUT3O340Q26tYQ7mUUm531dhYdoHTDjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-30T18:48:42Z"
    mac: ENC[AES256_GCM,data:KBWj/MAdka+8qTfIyz7rwfBM/48qynGLAMaJjaQiRVQFLLfeIk6ltK3V5lWHK18yQHhq0bMcLAhoxnFOXG3ehU/4cTt7QCKNgqIvKRFoJtxTxpoILvY+nKvMOOUsxxYtahRE+qRvsD2Y0zva6bbdz9RTQEXL8KCUXJeMT5X/I+8=,iv:kTaPf9nFRFCBSzGQs6VbqofQf9Wkcr1/UAWcWpfUcOM=,tag:uPgB/3OlB8C//qdVzhOIYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
