#ENC[AES256_GCM,data:9pxqXU3Q+M+F/xTFg1+KQDGXpEzJRidmECFx0mbj3zV/7aSw5sId/DUaJNTOEm+DUzZ2jB4wQ9jmBWVB7+URIPHPAxU=,iv:7FVng7XCxnL+dTSafuqIXk99iYYpBB4ARFGza080X7k=,tag:lgCCD5DWt+O0MYogD9oY1A==,type:comment]
#ENC[AES256_GCM,data:UjVhcLRQnL3Uo7kxsp3EOld0Zbg2Wud4J2XEaNsbceThG2Rauxa9xm4Jq/nr7QCKvY29rZQkr3M39kbKlwWcsBJXiz3N,iv:ULbaf/VfbLOMwwAgoAxcvfEB7ZbNwD76kzfSgSmtnCE=,tag:2NuHmmwxJHZKIswnWwbVxQ==,type:comment]
#ENC[AES256_GCM,data:Wfm/aTKm1zzwWZB3pRu22PW0Thvc2Lqap4qpHxTi2XNRgHfmomhurrnq6QjtUOJI13iVNPK7Mqm0GrbvsxB6esXGFhLu+4ja,iv:UiSFr5MKaMesURF2S8SUbGYRYqZfuA17W96DcZL3iK4=,tag:r1rGconh0RmtRXdOO0JhEQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:nz4=,iv:Ow5k27qe4cxo+SsMi8A+0XhgAZz3ynEWuJ6a4iSoBSM=,tag:mZylCzXNQ5yJo/0tWXSyjA==,type:str]
kind: ENC[AES256_GCM,data:eVYmlULd,iv:dnvl3Jz6vihPd5IyJQw87rg0jpYEMpGVoHfFT0N2F5w=,tag:6QSjB2JCx5pEB/+1T3FW6w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TN2SdHoM8OF+7/kcA1HyOm5Iow==,iv:hwTTIsyG0dq4A8r1tI53vXJc5TneSyPwqrZDY2kSQow=,tag:ELMAdjYvCRei5N+/WOavfg==,type:str]
    namespace: ENC[AES256_GCM,data:8LHsScMqfR4LQBg=,iv:y7cKa84ZjJPQN6+kDKDgfUoxAFzU9J7D/vKgTaAxMOQ=,tag:c4ZlgPivBM8x6fJPL3114A==,type:str]
type: ENC[AES256_GCM,data:kwEGFK9u,iv:Go/SMsjSfWibuiA/XFiFrSavKTbTBZYDqnxTHyGQfa4=,tag:zKuWAhy/z95FBETCehsQ9A==,type:str]
stringData:
    Z2M_MQTT_PASSWORD: ENC[AES256_GCM,data:jax52I9oJlI8iVkH+jLCdeOOrC7+pYiu,iv:cfvv8ejwA7OzfcqfOE/5jQUud57S1tmyI19gVA1pH5A=,tag:EG6IBERaTiDExhutRP5xEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaS9FQkUzVzBLREliRUZS
            Z2orNjFZMWd5N1IwaWRweGxZbTVkTGF2Q1dvCllPdi9RSlEycWpwMFZzNlBkRVI2
            dFhsVGprWUlPcVkvekIwSjJFV3ZSbjAKLS0tIEY0Qit6ZTB6STlFYlZDOXRnWFRU
            N1c5ei9EL0xJVGJ6aEpsUGtYV2pEb3MK8Tlg1YgwEVEyb35DsFTl0moGuSmW/00c
            8VbcaSYlY2RSWQ47MdCGZLv4IJe+M/T9iq76YFDTCFlGdsD9Aau6lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRHVHeWtGM3packZZL0hD
            R1lKbmtjZDR5bVZQVURqbE9vR09Ya3B5WnpFCk5aTWNudzhjdkQ5WmhEM0s5djlS
            S05DdTIxK2U5cWo4R2ZxUFNWR2JhSEEKLS0tIE9aL3k0UlZpSjRvcGFFRTRvd2Vt
            QmdNVkZXSkxydENrSFpoRmdNYlhtTVUK2XWuwZ+XcN9RCPzoyEfHm9iOFEGXqwl0
            Ye016pbENQicnJRDqJ8gow5FESmMeOMhGuwTZWLF3zoH2DW9WjLrVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-13T18:47:12Z"
    mac: ENC[AES256_GCM,data:M2x+A+jiZJkTo1qjsv6mX6pBoZrXsFytR8jzdzwvPk4UwS9OZj+W1pY6zRD0/SyIhREOQ08vXsozWVskku1QcqEk6W/uuNMlixX/17YjeVEe5JvnaR/QafSeJZ6qqW5xnHIs1GHJBpOWxn9OYPqyb2N9g1tweNilSnzzcnKk8Xk=,iv:7JVYeQhD9Dfohhi7IBBwZqUeY5riEqa2zOCSK6pTQO0=,tag:FT5x4/96y2G/uDTtT6glyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
