creation_rules:
  - path_regex: tofu/(home|cloud)/secret\.sops\.yaml$
    age: &age_recipients >-
      age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf,age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k

  - path_regex: kubernetes/.*/.*\.sops\.yaml$
    age: >-
      age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf,age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k,age1f6cd8atfuvhxmjugw5pquk45tszqxlh557sg8k9dsufzc9kgmpqshjm9pz,age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0,age1lk8hyd9mducrxtn04vk9u9x827ccd8w0l5qu8aru4wt56vhf3vaqjem4x6
