#ENC[AES256_GCM,data:iqE7gaUZxH88xeZ7UC91f6PkejZ52yKweiORFBWDtPSI3g8Im/3DQOSg5+wOVaBPoZJJYWjMVg==,iv:078xIZo14pYQvoI5GpHv6U7Ap1636v9UEnZ3Lqn1t+E=,tag:QL/IIH8s7e7IB04M0uadsA==,type:comment]
#ENC[AES256_GCM,data:Sp288c8pNsM8W9+pNEwj+ikrtI83iL/kCGynOYUWaRBXg6c4ZYvjQ3BxBwqpk32nJDE2EJqgUvD2S9uNnA==,iv:qisgQzotJTp5oPlaodCGqfmmry/oSQqxEa+ACaiyrH0=,tag:ASK+1A4PTg52lwEOQv+fLg==,type:comment]
#ENC[AES256_GCM,data:JFS1zVzA+eQyGBhYbxzPPUItRv/XeCXaLVjcWiiaObeqP/dAlmODWtHLfyv9T6kUKB/SV+fEJZLwlg==,iv:5MB/3zhDffYfNpTPu9scwquQY9+jwTBI67dCZ4YMGIE=,tag:J63DsILlhr3CLnn3XOs4eA==,type:comment]
#ENC[AES256_GCM,data:cILzc9JuKEXOgnh+h+2g7AIF+kcYRLxT6Adbh/5XjA==,iv:s1o4L9eWRQRQIpjHy8mOBK+EptLpuxve47C6ETLTJhI=,tag:KTlCyl3c0pFLxGh8sVNFfA==,type:comment]
#ENC[AES256_GCM,data:aj1i2adiXhDZlDFvyIkjiRRO+xfsAbqnuVpCV7GYiDZCZsZ41po0qC2SNOScXzZ4V6lfyTbEr+ml8kuS9yyGf/nK1iuRgbPNh8pN6kpOwkBqTRSehIdEPnkiXB8BpwfmBkid00av3P7tr7fBxxrD5w==,iv:XSr9u5NNbGlXg1T2Ll7Uk8IOq7f9aTg4r5LD3k7md28=,tag:zjq+qHFxBo8r7/LvOGwOGg==,type:comment]
apiVersion: ENC[AES256_GCM,data:/3Y=,iv:nqstepe28LI0rsy7nPNVTIrTxbH6oQMgkBmOdKaT3rk=,tag:2ty7XMrnmJl0ny/2LgCwMw==,type:str]
kind: ENC[AES256_GCM,data:HvMeOytU,iv:ZnC7sSqSjjwEV0YTajqISk12w/8M3XnlTREqFLh/YYw=,tag:ETapYJlG1O0hTWyp2WZx7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5IAxWyLA5C+rgZnl76s=,iv:ghMiNVfdoFmiqUq2t2oW9RdwII0rPcu+nKDfJc9V+7U=,tag:FfRpLQ9/ovXedkG+1/VoPw==,type:str]
    namespace: ENC[AES256_GCM,data:PauMMbjMLjmQFom9,iv:dIYnZTnpo4G4fUadp6PkP0lz8UrQPybFhOS0O0CUqjU=,tag:CVc2+8eR9bbR71iLmcGVsQ==,type:str]
stringData:
    api-key: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTzR0ZTc4YlhuZC9Dc3c3
            Uzh3eHptNEFUU3N0UEMwQ2FZbkl6eUNxeHpnClVvWDZ5K0hUMUNiSG01ZlhneWlL
            czN5Wk9JT2Naek5MdGxURVd1MnVGMEEKLS0tIExFZ3ZkTW9iaGVTTnR6Vk9oaFZC
            R3R3c2tneDBCSjlqaDAyYzdYVXc4NkEKwQ7qLv5QNjQc2EBTG+2Txrp1HKQ/Z/zC
            NeYe4upki2qzlc8h8uYLbWDZg23zLUL5FXkY1bNPWvf2U6mfi4G4IA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTGIyN0twcHdjRXMxQi8z
            T3Z2aHhIVkxmNmYrLzI3VjhZc3NYbThaSmowCisyL1k0MS8ydllZMTJKVkppdlFO
            SE8yc0p0dmJKTktGMnZ3REo1VEVoS28KLS0tIHlJTVdoQlZzRktjVHBHSkxVZkZM
            SCtabG9ETjZxOXN0ZnRONkxKUG9hVmsKFx88lRWi7fGW34MH1bvacWjhHo1l05B3
            sV77ch0Uo1qSasPNdzCV0vKiczEZxfC4Ec3MFORM7uqWFmq5084D4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU2RubkFpUkMyajREcEZp
            cGZMV1FrOEJ2V1JEeHVMeUVsK2NzakZEd2o0CnhUQjh2RWxPaGg3amVnb0c5WTNm
            b3VJTm9kSEJDT0lmZWdlSVduWXdxRkkKLS0tIGkvd1dYdkliMk5EWEp3VHd0UVJL
            c2NkbjRVZXhCS1MrVnpzc1hORmkrNGsKvGFqnEeQKxusRq7d4C8tAtK0Zhyd7XK4
            yHay7kuVeoFETInO5qVcnpNvJji4UIZvMUNMB044n1OmoNrTNkGSMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f6cd8atfuvhxmjugw5pquk45tszqxlh557sg8k9dsufzc9kgmpqshjm9pz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZUdBam5pQVBIdEtXeTZU
            UW41RlhXbGtwYUU0Q0QyNVdjZS85bmlyWkUwCmhLTEFodVdvRjJsSW9oZktqTm4z
            WmJkM1lvRmpndndYSkpza2E0c2kyVUkKLS0tIGNCTWlHcno3NmFnbFh6U1NMSlda
            YkRkTHpGLzlabjBRN011SU1ocHdHcVUKbajrvpQ0OhcbyKhGzV20mjnkFim/NJo/
            2X9Jd1ZmEC+PTfMNlpwMHQjfx3IF6/8C6nUeLHfklv7SFHgPweu06Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZVJlL3NzTnZyWHRNdFFY
            bDVjazM0R0lFL0RrYWYyeVMvYjU2czNlOW5ZCjBBaUQ5RXkxZ0J1SVFQWjJiNy9L
            aTBwcExwZ0hoY3VaODE4ZFFvTDB1WFEKLS0tIGh0dWdIT1BLck1ubE56M0hhSFk2
            RlVWZ0FPQlB6TEpCeGVKU2pCRUd2Sk0KAfLtvKOkvX58gEF/rGOlc0560UurvzAa
            oZdqdlxlcc75/i7xeqOCQJj2CifcGr9yQZVH2NVHbw1LOMVajdvEPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lk8hyd9mducrxtn04vk9u9x827ccd8w0l5qu8aru4wt56vhf3vaqjem4x6
    lastmodified: "2026-09-07T12:06:40Z"
    mac: ENC[AES256_GCM,data:dfe0AFIQyNTko7PPNuCoWEKZUyH/YYuz8SYnzu2cWRXaXLkPQY18WtDOxu+vIORJPGIY8NO5RS57A46Jdrj+feLnHsFVn3+2XZ357NTF+miXTiwhAJBvOFuqJxCIBXa4muzfF3U1rQziQSdkVfyS1PQaKBeoKsOyy2iys6duGJQ=,iv:BkZ0kAwZNfiW9fI9rKkBSM+0Z50kvHEXGvhJ09IGdwE=,tag:ANHHxu/V4DAuKKJwM9FWPA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
