#ENC[AES256_GCM,data:8y8RryReoCRUQWUbxJVHU9d1znpiGO2cQRzFo6+vIbnmwl0uh8WfFrZfXSoUXwrUEfpRrLE7/delW650DMuNDmFHCKROs0GkfQ==,iv:6S8aIh5hZx+++Vl+fuw0L9KKHfplD4oxPoXhdEg2nv4=,tag:Mmx/5CM6xcrhNNyNiPe8dQ==,type:comment]
#ENC[AES256_GCM,data:eZBa5Z84yrCNSezK5XR8s6p4YelTcrcYAZNHVlYQE8FG8GTBaDeiPlIsc73URoIUfqCqpHqCOMj5Kaqzn9nogO+V4wWfEOjUmOs=,iv:kHQR1/E1iPO+PPC/odKjFn2s2ZN+fXnnB5keQYqyoq4=,tag:riKgem1fdy+k/l5QOh1i3Q==,type:comment]
#ENC[AES256_GCM,data:EUfUugS4sBuJiQOtE93RvCJcYHLMSGYzkTKFg7pweZ/eTZ9KU/Pw/QpqHBLPjhYCfXmK4VuNfAGYUDm8IYx05Gs1/IUiB68GJkw=,iv:jPgrzUZt/AWS9FlbN5dWa9W0N1Cz4QINz3qTC1hDjfI=,tag:TV3EktBaQeES9EOw7kELYw==,type:comment]
#ENC[AES256_GCM,data:3okgngJQKam8+WPUgvKTSiOb3II3gsQV6hD/JLlOk7EGN+gnjo5W9yEkeNEeSjTA0+OqOEGzWWh7U+VVqROVbd/dGjENkNEeMA==,iv:snQMrCUK/4yLFVLRdQQFxn8N8bPb01iAV4Yx4dc7ol8=,tag:T0dcpVZCIakbmXc/yADzFg==,type:comment]
#ENC[AES256_GCM,data:yIKZ1TaXK9Wj/PbPZtZSosn7w6auNOF2dm5KQv6F8B/YEoL7TwOV8mMBT/1qzoDX0xzfO3p/mB0IxgJVbxC48zKxi7s8iHp7yw==,iv:qdHCI1MRVI4RKq5P5/hbeozQGyZBOsKXZu51BFPmLsg=,tag:4e6wF4W24SAzD9fXxl8Epg==,type:comment]
#ENC[AES256_GCM,data:wo1LWaKAK6qKnWBEuZVK7p/oE+Vj/Fqtz7L/9gyvfl334jt0B3sw++oIZQVstbeFjcPYC4bQzgG1hpxjsr0=,iv:IzZ/6TpCDnuDEw1x+OZyT84e3C9hzJGAo4gPparhYvg=,tag:V1Ai5Xl+CbCHOlf1vYNatg==,type:comment]
apiVersion: ENC[AES256_GCM,data:rb8=,iv:QMnLH1WQx5/JEsQaxTU4rc2Etc7U/DLwo2yPWcWUhto=,tag:M1kVvhDLMSHsdWf7RS8neg==,type:str]
kind: ENC[AES256_GCM,data:X5YJMTSs,iv:O4kJDhci3b3sULBUpnQDzsOidHgJ6aAvsad7ccdXEtk=,tag:9SYGzYNct5QvuoThQeofIQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:c1iotwjRzS2dO4FjIRenlzgGTSTPiEXJJ2V6DQ==,iv:F+qsirPNgZHl4ASkrHJJpUvC9viQkR8TNrcKzfLTBMs=,tag:G8BILjqIVNefDq9H8oGPdg==,type:str]
    namespace: ENC[AES256_GCM,data:BSPEM/6u,iv:AgmTE3FoQoE3BRjOjFLZHe4+z7/lZRrDG12RZYFy3Wk=,tag:LQDTGXbDv0gfZshGZhbYhw==,type:str]
type: ENC[AES256_GCM,data:qXd6SC/Y,iv:1o+r7sBs7HL5JYF/wleL+N1G3JWkfSKR4qUnGDw74/k=,tag:6q6j5Y4uXODoDORDtNja4w==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3jsUKzfQJ2Yk4R3GtpSZHmG/ooP6HEBctkq+3dxWoA==,iv:TPgXDX2GvcerAcXQpa6YYRJyfCJledF+hfXBptrhTeU=,tag:yubsdyU9YP9d3zqeiR/Pmw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1zdkqWCh/azE5mBjzGx42PNHrxVogTlc3xew+k/qhA==,iv:x3Sf/FPmcmXOAy3x2trI3h7ezsfK5Fj8nt/zi1KYydc=,tag:ccf0wVVmfYvFKsR8axtPmQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:tfIHRQ==,iv:+HGU2wHmhHRjlrXseTr7lEG6MduD35kbeG9JrbFg9xE=,tag:fLTMv8h4sWd0nox7k0F8Yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZGc2KytaM2EvdkNJR2hi
            OWVhUGMyQWd3WEV0RFlmai96amkyckREVEdNCkdRTy9QMlRWRXNKeHl6VDNsbCt4
            UmhOM2U5b3VubDVaZUFIYk9tWUswTXMKLS0tIDZob2J1S1lOTm1Oc3RGd0ZLUG4y
            b0ZLaXlTQlhmTm5PUU8zMHNHWHpYTTAKnvNKZzEwAxh/HCFY5yauE6Babxwk9uH5
            aHnL2hhSPpYnDb/kC6EeLP5jgXPBdEZoR2S8X9/OY0KDh5FgtaQpiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrekZ1Zms1ejJMV2hndy9h
            eElEUTE5R3AxbzEvSXRsUVVaRVppMktpbDJNCnhPeDhEWjJQdE5BYU92LzYwZUN1
            WVhBaERMMnJodnQ0QU1meFcxVHpmTDAKLS0tIElsYUlqL25TbWMzTk9NOCtNVHc0
            U1FuamVWUW9wVlFrcVpXSnlPMFkxb1kKqqyD7w/x/ct/sIQ4mQOFEEwbpEVD8NHm
            07GntZbmfVvnWF3/rrnIM10uQTDI6iRSmkpdQLTnu3wU3RwYLJ8HXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBualc2dXRLeThOcDNPMUIy
            U0M4YmtkbUJIdktqdFM1dlQ4ZlJhS3Z1UXo4Ci9lWWl1Ym5vaDVzTkY0SzZkYWR2
            NlJ3bjFDaUlESGlhRHh3dUFvY010SWcKLS0tIFNGUGxvMlJKNWVnMGRFdDJiTlVZ
            ejlNOUI2cCtIVHBaVEh5VC9JSE9aMGMKqpqlLWuqnLXGyH+P3CNRBluD9UCf157j
            ABRyZ6OOzjfhBg3btGkS3AuHAnhbKmcEUtXwKY8mp1zBPZM2GzhESQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-20T20:48:48Z"
    mac: ENC[AES256_GCM,data:3WLGsLxjiF9WhtnErG2F7sh9wjXM4XbC9xSEJrVAnH22UJa9H01aBQIv9qmaaPqk1cbZVCeFRG5LtCX07rHMQR3ipc9uO4goydug7g2Q0zTBuAMp4Y/FxKwvJK1tQSCS8WkbtAZB4AnxKsgxcKduEywl8FbSZxAI13KL9dvFpqk=,iv:NKZIgBFh9O35H8bvZZq/bKjiS8rB2MulC2rI9nh652M=,tag:QMQdmK7At897gWmTX+NdIw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
