apiVersion: ENC[AES256_GCM,data:Lqg=,iv:esly/xQZM7l5T2dnme219BOkJJY8pFPmFDp3LKehYxs=,tag:1FEXaCEHhEsE/7UlisvtVA==,type:str]
kind: ENC[AES256_GCM,data:tmN5D3gA,iv:9/PQxjc1Jo6r1iy99VidJRydksi0H9uhyVyTkfqADaw=,tag:Bmp8LjnWe++QZv4zQiJFWQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JiTmqjS1SCehAEAHCeoMEczPmg==,iv:q6BvPNN77EOfRq8Wu/7nafOdpKy/he92j0l9Yu9pl3M=,tag:ocebk1TuFo33LSG/k2f7rg==,type:str]
    namespace: ENC[AES256_GCM,data:C6srvMJinhe4,iv:KX15RCG4UkRMN8RVKwwyukVsvLMqRmLO2meGdLQNDCU=,tag:XFkHHvjIBd01lR9NLgnszQ==,type:str]
type: ENC[AES256_GCM,data:jIKs0mrZ,iv:9UX7Jnmv4iPRWmBUinJcRACq8GhDZajOopfTi2ujTl4=,tag:TNnxXaIo7GqCDePIgzTSyQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:D1dvS3Z18+1ZjPpEAfcgMIptLdmGP99Rgn6bko9F6ao0+b2Bxi4xQMWBorUME2e/flYz+LeA6V7aKlWn93mlk8DLYKqRWQ5f,iv:vcJI9qYuKYiD1eDZxrAfJuOhoX6ql7WL+DH+PBVMPrQ=,tag:fUXH4e9s2fYG7LbVVg18qg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zaf5EJUkadID5f30LMWY6AfBB4g=,iv:3zSTli+L34MjzGZyjbpmHts+oCKRstA07fPnYtLk9Sw=,tag:EE8kMAcgL593Xcwb7imadA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3kalkD7g9hX+Y7pFRCXVrJYQCBXCklgHWg17AFzr4tJK+pnN2aqD7g==,iv:C20cD/xNZ35Y1qhePV2Q6HwQF9LHbxlSPfcSWS3LhYw=,tag:e67RCDSx2fMCt1FHEnPS8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdCtaSkdYN2RDeWltb1Bt
            bHpHNzUwWU5XY2wrb1NFdkR5SmJBeGpDd0RZCkRVZ25jOE9acDlkQy9aNWl3anNl
            Z09HRFM4SkVsSU5xeUZzSDUremtsbHcKLS0tIEJkZkN6eXd3eTVjRDdWMVI3OVpR
            V0xyci9aVThkLys4MkNBV0lYWXdGWkUKoxqg19qTMYaV3rO6E68dZ6h3wbIDLVoH
            v5yyILAKpGWuvwyWplywDhWj5dRxVtVcvTZ1aeOnUs8+yN/dTNFfXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVjNSNFBhTUtyZklGOE5p
            MWFqNjdMUzdDbU56NVNsQng1TTl6Vk5XT1ZBCkljYytsNzRUWDM0ZTB6Q2tjdmF0
            T1YyYUQ2QThzYnNWRW1mOHBDMmMyMEkKLS0tIEVlOFllT2xvazFCd2RuWmRBR3Zz
            MTZXOVlxUmpOK2o5d00rMWdCTXBVQWcK+qFJeoQp19jixdAvqhEiqr+9TGdFPNYa
            VsqiljL9S4k4jyhnj5s5qmg2Oxa3ae09y4GuW9rsCyTkGfWZXsrxrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-03T08:10:23Z"
    mac: ENC[AES256_GCM,data:T1OWx+LgAiQA+A+zy2zC7DQS1GxE347HRvR561FZnooVrcJqPv7h8RynFPV4NQxq6RgO5tVuiwbH+2O7wDZYUzmm3Ig/Ge6VL1znNvlqgtfDVvI3PbZ9VDEiN/qczqFi8YSdPdoAmXIkgCWLkfeZ7Ac/3H/egelHeNS6GIXkue4=,iv:Z9VJpP/VSEBhMxLbZWmArKQzH4rXwWx15ubFtHlv1Vo=,tag:rADo5UcenG+B/FHNiqpTcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
