apiVersion: ENC[AES256_GCM,data:KXU=,iv:KsDXpQuhAsWZ/4bnR5h6yjjoZvOdACArw/MwKy5lh/0=,tag:DrN36vX/bKI3jFJMlSUiPw==,type:str]
kind: ENC[AES256_GCM,data:IPxlXr0A,iv:Rc2wnGmv08p7aGDcICOqy3WEEKaB1nv2FRyAtqo4Fbc=,tag:nENPvEK0R0h12+F1EOiqEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pDn48zEAga3dyEDL3IQ=,iv:qF/Wsmpruudauj6tuJZ5t7moRSvOUNCuFKgzZjCJmEY=,tag:L61JXcn/CX32k457jG0+jw==,type:str]
    namespace: ENC[AES256_GCM,data:ZevuCwmDGQ==,iv:i+2ITpwJhep3Imgi1+ZiMS7kcFj9Durf/DtmUuIW53U=,tag:upBUy658SW1fZbg3Q2MiEA==,type:str]
type: ENC[AES256_GCM,data:j23m8XyG,iv:AT4MuXejr6aBlb2J0YBJCjXoqfg0kl3MRhw45Luw9Bo=,tag:De+6G0nYj+tHRi0A8njdAg==,type:str]
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:9/3dmgZ9tn4DOf1Ti1pq0HoN738SjG1xcpdkc9lpsvF435sO1FrIjPigBHgACSUv,iv:f8ckcOGXwrA2NubbHkLNwIz531EgqBtQObz2KkOEVbU=,tag:B3uc4gMDKyHZZ2fw9wpriw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0w3elA2R0VqbjMwa0Fi
            N0k5NlRHUjJyWTF3SjkrOHZLM0s0blNIYUhVCnN3RlJMRUpxejVRRjFUMmRQV0N3
            UEYrM3RIWFllQjRMVjdnY2lHU3A1Q0UKLS0tIDRTVXY3clNKdDFlS2kvVzVZL0Y1
            cVh4NndhVGo1RVFJSzVCd1dacWN4Q28K1RwQ8Gt6ZjFlD9V8Ul5wmpbraS9O0RZc
            XlfeXvn3k/cPKQIxfitXryqAhkLICCIa7atJDpbdwaJQGW06mOP9hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbHE3MjFHc2pqc0xlVzRZ
            SU5rR3Z2SHZBYWpGWTZUOHdBekNVR3RzUEhnCkVUVEp6TjIzT1BuL3RVV0ZmRi8z
            T0RvejNWcHAzdmFZMy9xbTNFa2FWWkkKLS0tIDZVUWhHc0E2TmxrSXVlM2g0N2M0
            TUxQOW5Od2FhRWw4b0lRZEZtd1dmN28K7pZLZ+lJtLG3BHP4Z51/DWhKhrTr5Bz1
            QWoF3yJuCJf6bjtlk/w0taMhcF1QEqnlyOsoL18e3gdULZWtYDax7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNXBoQ0ZubCtKdWhTVVcw
            eGJkWEhBdDRZL2xEaXlCT0ZUVzExMkUxbHhZCnFZckNNdzV2aUhCQ0lxWEJaRHRm
            OURZdkhPRlI4ZGhSTTdNN2lxTUREVm8KLS0tIEVaU1RPVXRhRzVVNHhyQkErMXlJ
            VWhxMVQ1Z0F5NCtKc29KbldIcWZwZ1EK2Sqf89bVZa79AWoe8S0P6Tt4hbJQPieu
            /mp0rAKdW1qs5DTHN3N3alXfEeqNPeD4lGAR3nwsmrnK5RJpkdraiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-23T08:01:22Z"
    mac: ENC[AES256_GCM,data:B4TnmEW4zyM9sKi0PArUcqwS9oNIXuUpO8mU/06PlCoRdXefe0DWa/chYPLE6RUtcPrWHjgjDC0YTHARzABpQvSO4DxbrXQONWMow2cX2vEc0Ni9iO2WZqvKOXoFEqz1HQvzu0xLlhb2mLghOzqQICBNjNq/FNJh6FnUEqLk3/E=,iv:39CBAEMStQ5WEvuO4Dy1TRha1rH8n1aFgDLXy/BU1u0=,tag:ZsGU0BRYAw4P4Yx3Q5z3Ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
