apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-credentials.sops.yaml
  - postgres.yaml
  - database.yaml
  - sources.yaml
  - helmrelease.yaml
  - httproute.yaml
  - httproute-otlp.yaml
  - otlp-gate.yaml
  - otlp-secret.sops.yaml
  - vm-scrapes.yaml
