apiVersion: ENC[AES256_GCM,data:+ok=,iv:e57SPpgI/fFtf7m5PVfhWBWn0vYmBn6jvp2DkyBP+00=,tag:FGoYs4an9RYb99MfEsRVQA==,type:str]
kind: ENC[AES256_GCM,data:TART6vo5,iv:WErz+XMsBqmDG8CfEQMmiMzExJbQCrpG3vHtCywUFzQ=,tag:Rf4O5MY0Z0Py0oeyHDUrLA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NllM2ThTIoJcEA==,iv:G6LUFVRsS5G3l5MwqvEcGTjuivpvK3kDMy1UGhoVnxU=,tag:lkfYwY+skRKHkkPgqNd5Mg==,type:str]
    namespace: ENC[AES256_GCM,data:EVb3w+UeDw==,iv:w4MDZ2l64jLBw9Fe2xQKuhySdNbJ1ZK3xRFe2k6RRmg=,tag:Lv/emIDgcor5MUvipFTNFA==,type:str]
stringData:
    OTLP_TOKEN: ENC[AES256_GCM,data:d9ZLuJu/WnhxgNbuNnbLRv1Uwek14pz9jWVFXReZQlV6lKMhl8p0wug+dw==,iv:NkgwBdqC6oCGleuD4fC8qCJBDtThW6D75JGGBcokp6o=,tag:71KRESseAw3kTuz7KTCipg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMm9rdTkzWnE4dnhYV0k1
            bC9kM005ZXF0K0wxYW5HT2NpNTZuZkZKcFRVClJHTXE4SzNqREI2RGwzbzNuZm8x
            R1JuVkx0UmhaSFJFVkFGSGZwWkJ1SU0KLS0tIENrajRwMTBxc0s4Q0huRm15ZGRa
            ZTllZ25kU09qaWp6Z0orMXV2b1drOTgKnJ9g4OKFrm4m9asjS8IvIjBk021ORir7
            Y0mXeGyPere5M0Dv+5zDMzSomlIpZPNjIP0eqTEkYkLPftryyq2gHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUSt4N1NRSzVUbHNRNnpG
            eDJCQXNLdGgxYnZUYjhQV1V2QkhTQ0plcFhvCmdJYmZxRFE5dWprUGh4SFJYek5k
            WFlnNzhVS3dTMXRGZ2VvR2lPQ3E2VWMKLS0tIENoM3lFNWtQaWVkVURTV1dIeWJ6
            SFZ6OEl3SHcwVnhxNnBOc3Nub00vbEUK4+b9UigHypRA2tGT7Tv/8x3PYhl6KmJ2
            txbMSvIVCgd8pL5uHd+YpLLqRatMNDlZHW5hmHC99U/2sDnuV1TSsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaDgrSmg3OVJ4SnBrU2pi
            RGFka09WREsvb0RIWmx5ajZRTEFyUkJ2N1Q0CkFiWDJYY1ZJK1JoYW9tSUVyNmlv
            VzR0cElINW9WOEptYW1FNTVzbUZ5R1EKLS0tIGdSV3hGTktDQXdxd2I5TEZ5WXp5
            ZWRRdUNGVWo5OFphcUNmclFub0JrVEEKJNzOIN/BTPEq4tCxygo2f22a5RjEiQtm
            VBy9k6ZG66ieyNFNLU0itkzsXKZi7oAAoMTs6F5+5kmKubu3A8JpjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-13T13:34:15Z"
    mac: ENC[AES256_GCM,data:EQV+/5okklCslDQzRRnjJr8FqJO2xux/VpYjfIn+0VahoE61nS+p748JnSEDK9TN7udjIWb3yZxC/8cP9W5jzDjhxyw9z5IMji93pwSAl7Wz/f+dL+kuqlDz0aNfyhp+/CgWb0BO0ZwHmx9Iq65n6HAx9AXORfKgdF+XDrwmN7c=,iv:YjulD0kX0RFAo73N5uTnQqFE1BQYkTyF0PGKCwJX4E4=,tag:MfFDfVogMz9H/gx6tsjeaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
