#ENC[AES256_GCM,data:b9EpBSnuAasqXLHDRSXEIg0VDmkvUa6PGAV19lpMlsXCV94vkvGSsSrAiUHfoyx3qXEn/DvWjsYqaNakNLY6I8C+KytGG5MlA9w=,iv:Kq7lM+lqGcTy5OZxKz08Mo3LUUYzgYok9SJEAYjnu7w=,tag:q9AJr/fJdDkxgpQgDyC+OQ==,type:comment]
#ENC[AES256_GCM,data:YRWFJ0GBRcHWs7MN1jKq/mGjRtGX+Hv4O8qxHsnmsn6sCjDiShIpexSuQANVpNcr1KJ/vSfr8NZPoT6NyOUji+TCNMgUggVXRg4D,iv:kBdVT6bolUHX3b5p3J5gUVwfhdg8ogyofZAwnXL1WkU=,tag:Hl5DYavq4KGj8+EWuYIbRQ==,type:comment]
#ENC[AES256_GCM,data:2ud2htJReZUYIh1IGtZ60/eHbuSVEw5wtvhH1a8iHqz8m62BIsAmeSP0fhKt5/ZiDlTooPg7bqAIPYz1e0fpVGVuxSoGeo6+Xus9Lw==,iv:JNEaTISxJda9YtZsg23VHRooIGXHgjYnr/P2052874Q=,tag:ZtpIO8g46Kxw24M5+9UCqw==,type:comment]
#ENC[AES256_GCM,data:kv7xtl1t8O8dmLvKbvwG5qDa/7qnnF315QGNSsJ8bI/KsJJ38rBjnxY7dXmV9jJdPgHOJ0vRmexmltRinywSPD4mT+PYLzN22XZ4,iv:zfpHGrmIhCd1Bf97pKQP8CSKX3Jh7h8K1PlnecTSbkU=,tag:LvS3/EKwil/idWOzVLHlxQ==,type:comment]
#ENC[AES256_GCM,data:EkFsR55eLUXSo+pSoh+dYWrDXZmz7vksB52X6PXMWkXQvLnfwkGNSolg3o3OHakpT2cO,iv:0dS/h+Q/1x1VJgp1UKXt9NOfiCdQcEUP8FYW0xK6+gk=,tag:VbnWfgjRHzl85EF5NDi5xQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:rWM=,iv:z0LZovw1e+Xjc7oywVctlTIbGmUcwO1lXsbCJ4y/tkQ=,tag:OYgSWgSMvMnXSVUUGXHX2g==,type:str]
kind: ENC[AES256_GCM,data:hhFiIBMT,iv:iDS8KTZkPWbKFw/2OGhsPfH7l/LHTvsoWlZiFya9wjs=,tag:biN2F6kCc2/Ax+NpIRVwrQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dqrrXFBfYGsSiZIUa44YuoQmUbSZoWRLZ7pH4g==,iv:c99YZWCcGLiLj92d8pcjrmHOO9MxkYRrhMp0F/PR8Ss=,tag:3WFqCbPNzk90PBK9x+gR4A==,type:str]
    namespace: ENC[AES256_GCM,data:umsabJX7og==,iv:6J/pHGFiGP5HVJ3PABMtyPT/hA5TggaWkjQ4RwHLiII=,tag:yB/heI5MnPkdinQxcUv0Ew==,type:str]
stringData:
    username: ENC[AES256_GCM,data:lY7Kb4/kUA==,iv:F320vu+iokidgrV+6YvhXam9LckBbzsMAWFHgNDBkkg=,tag:WNesmhLO8GeZIqXENi9SDg==,type:str]
    password: ENC[AES256_GCM,data:uZf+++OxrqgTy5C9fiNHuNXFNgV7T5rpgtcBbwfTfEI4ds+iBBUCqdct3yECnc2f,iv:xt9uHBmZtz7E6wY7MOF1Z3s4exEWa6yF81F4lGEClqo=,tag:ELHcJEXiUfvFBqFQYrOEJg==,type:str]
    database: ENC[AES256_GCM,data:XPOWAWo4iA==,iv:J3TzxTcJUFwO3oGILE20IT5all6BC11N1sc48Ehz5eo=,tag:owDEtF8CybiVjqfCGPEN1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbG5TZjhKeW0xY1VLam56
            NlY5eHFCdjRkTS9uRkRCYnBXczM0SEdKLzFRCnZOc1R6cDhHOE1iKzd6dndSZlhV
            Sm9LcVhWSkJJb0lsZ3lHQlpxVXYwbE0KLS0tICtjdHdyc1Z4NGN0Q0dzSnM1RjdR
            MVNWdEVyaS9WZmlKWUVId3ZaOHovSFEKe5bQRIiDZNzwHa9qns9KAxmPP+kZK/Yq
            oymmAKjZagdo9dA8UO2865iNmb0J2xQ5fNxUw2yQ+93HZMWZHBirRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNTZ5UFFLNjJHbHhacTRP
            enZBZXB4L3dMKytZWkVHbGhTWFhQYVJxSlNVCjJURU9lVDNRd0FGU2JZc2tQdHp5
            cHVkTFBRYVNROUJpQm9hT25yWmlLbzQKLS0tIGU5MFhBSVp4N0lFbnJtbnRLaWVh
            R0Z2Mkt0VHAwdm9HR3JBYkhwSDN0QTgKpFKfAVD9QwDZKg1Gxae6NULAzmSKRGU/
            uSvOGTZ51gBwXTeNjM9Dx3DJWMhj0iZnwR7vRk8wumAk1aDdOuk/Ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicmZWWGMvRHNlUyswZEtD
            QWMwUitGbzJkSTg0cEJHdjdqZGZXMFc1elRvCnIya2x2RzhBVjY4Lysxc3kxSjMx
            K3MxemY0b3dJc0dxaUxlM1J6bis5NncKLS0tIHFtS0hQVWFTaXJ6VUpDSGljWW1F
            ckN2ZnlLa0JGQmk0RlZtUHFWUmRFTDgKYhlCgUSdnQ5QW7bx4LJ3Y3VU3lZCqRX0
            JO7paPAJvtnouCE8nM6WbL67hGybVRbJVNWSChTVEfwaRZ/h5o9phw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-13T11:02:25Z"
    mac: ENC[AES256_GCM,data:uZb1yDd0wgVgo4MeFEBtge6pKzef7djUXuzk8HB27A8QuiztRxorOgKTmxheFke5xtcOBzM2FaKLHgLQbe6Gyhc0VwP502h7SmdBcQkpdjIYM/dzixjugQQmGdz0r5CP3Q6DY0X0lmmhxob1x/j2D0fc2ARt3hyye5wVV5lopEw=,iv:3uwF9bm3wGLIwiABqR+aSRE9fO6RjbwypwCspDU9zdw=,tag:lcIwNo4x335aulsC348jiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
