#ENC[AES256_GCM,data:eq9EcN8FrbMf/gsSzIgjpOLxieBOrK1gbBADZPal9Fvk9faVPbmXYHmilfOzeePKRB24qPUTNrOih6PF2xNHjGUhWxwFLRc=,iv:wor2MiCSQaD0Ex/babrG7EBgCfPu/UjAAQPYhMKpoeg=,tag:xslLaEpDkqY+/+sX7SmLug==,type:comment]
#ENC[AES256_GCM,data:aJGGBVyqHCDj3PYmAB/aEyoGaiaCT2yQjeR4U8225oB6ce4AEzlC0PTDgNiyOofSuCLj61joZ1MymM1iruT7dw8uA3P8lrA=,iv:AlPQboioh/ANbhsSa5xMMIBY2t/SqPeaUpoiv9XnZgo=,tag:GSx8FKKwzY9dUgaWeA+/WQ==,type:comment]
#ENC[AES256_GCM,data:QJt5LjKts2WKt/Mekz9DI7B5+zvmjPlCgR1xSxSWdkyYhNrL/6+wGskJ1Kroej+AL0cvQRjxkOiUGGnZ5OJTXRZfbe1MfUta,iv:yEmHrQnb+ksD6Rgandm5EbkF0CdxP+aOHYygoB7tp/M=,tag:WSarkL2TVZTBa9tYt85mQQ==,type:comment]
#ENC[AES256_GCM,data:UFU8H9M8JDqZAhKcsxdKKyoLZA8DAFpfhFtojK9yqm64i6W14q8CdSsDSnopECC9kQ==,iv:sG5pZTMEyvZgTdCZpWN0laGI2w6bJ5NWF8QkaeIiLas=,tag:kI4o7+honjQ7/mTrsIhcZQ==,type:comment]
#
#ENC[AES256_GCM,data:6kwA55DI+Z6h96y6khzElgXBe74wKoZNxkiLlX1L1KmXDCmrhGREvfPXjAn9/QtsvFHx7L6002i3zuBaZ46oCXrYaCjAaEqfaA==,iv:WlBmW7x36xShA8mq7ILaVSl3vDs7Cu24WjhlI6kl4v0=,tag:h80RqhqTcvT1LnoGqB4yMg==,type:comment]
apiVersion: ENC[AES256_GCM,data:Yf8=,iv:EQM8CHObAxiIFPNtrAvTrVQ/7jgvDTUiVgRTwHSHnig=,tag:/K46kHdsEEEwcZ2rnuvzgQ==,type:str]
kind: ENC[AES256_GCM,data:QlkqzwWZ,iv:4u1ae0NsoUbe9JLzjChvxrBqOe68fB/2XNenWFyzNmM=,tag:rhqEaWvaJdj+AgcACdVRfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eSmN1AzhN7LLd8Cs6icTSji2AoKK,iv:QZxJ8zkLaUHKp/pvYKlFvCAKIDAdIoYuqUOCPlHr+q0=,tag:+0nVULpU/gsmWvrMhwwl2Q==,type:str]
    namespace: ENC[AES256_GCM,data:v9I2lFrUoSVJYgLK,iv:bjT4hOR+l2Nr/jcJx6EzmwV0f/neZzh+LDAiWZg3ORo=,tag:jt60W2BJU9MdSygR+vWX3w==,type:str]
type: ENC[AES256_GCM,data:AUuGT3M3,iv:PEFIITU0Lzx6vAs3u5NbyyDAI5ZO2CA4qAiJ6XgQRMA=,tag:Naz3UO9ghcdvvL6yVSS0zQ==,type:str]
stringData:
    librechat: ENC[AES256_GCM,data:Htup87/dOevtgAu3qnWTAaAAeTs6eGOkbmz0UZWIl87XV2JyEX9mZMU064oMGvSRD99egxT6oIbnqYaeMAYl8w==,iv:v+euEKrrVBfGSOCxnzhgGOcuEEJSbQkSromm49jAc9I=,tag:iDpKA+z8X4Su8nopHS2OMA==,type:str]
    opencode: ENC[AES256_GCM,data:L10OjyAPMeJWuD6FdtVMEF/PhdLWQDa7NCCgN2t0oOi9u0XCERh7lItHftfsc7Ypp4LOBEast2EjFW/TfrNHY92+vw==,iv:7s4bFIwHqUHW35CySHvkvYTYirYLvuHL4MumHxWy0C4=,tag:xXAnbTd3aJF+qREvLaPSxw==,type:str]
    hindsight: ENC[AES256_GCM,data:0XHAh0s5jr4lrZKQT59w/L3+YGQwv0BqMmFfdLOXGSEluHE8X5LD1iP/XXf2t+mrKl5XI721T0DBjg4MsX9bHw==,iv:PwgbU+W8U+8vaaY7ChBC6SvCbtyyzvSH3lSKcCkdRg4=,tag:glFXVSoer1+qdGVQunLLGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlRCa1VNQ2hVZEF2N3BX
            WDhCeGhvMmZnRzR3ZGRIemQvb1BDWFJ6SFRJCmNXcGpma29SbldsaXowK1d0bUlt
            TzNvdkxwbVZzN0U2cWdmSFc4Y2NVZGMKLS0tIHE5L3dSYkdBU3RGdnJ4N1NvZXJE
            dWliNi95RVJaRGovcjcrRUp0NDg0REkKqHDQebS7UslgmbwGe3AIHeUy1H4bb2N1
            QC9KWdcGtt3F5ErAOhw24mp5Iee5zUSIlQltsXeN+8iX2X02fLpFqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TGpPWFFmTWs5T29zc2Nm
            SFdua1REcG1KQUpnZ1hCKy91V21nMlFCRlg4CkdyM1lSQnRUQk1ZSW9aMitWc3Rp
            a243R2VpRGxTUHFiK0ducFhKWkJrNEUKLS0tIE1kTFlkU2d3cXcwWWo0S01oZzZt
            SkF2cC9PNGNnSTNmZTBMMWxLNkJuNUUKXeupPfvFJA3cbGYUpC9xAzBCIHK1hYJW
            s5OJci33sEbqOyFbs2oQaiW/MUf4mHcDv58DZWgbGcpaQtuFV0s7NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNjQ5dkdTUmtIYzdPSGRs
            VUtiQlVieG1GWmZtdmh2Sm9OV0xhUVJVMHlNCmRrTlhodU9qenZXamlicXl3bzN4
            aHZ3ZEhKbXBuS1pYeGxhQWZuYm9POHMKLS0tIHZJT2NZZXkvbVdQYlI1bHRQMG5N
            eWFSdHNpMTBMd1FzS0liU3ZqMlhZZ2sKICk6Ux0qExlGPAod4hVwDzYbepbpY9w7
            p2SzOctTjMi58PpSIro7670a6Kvduc1Ph018FSAXG3+pnADkK+3i2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-20T15:01:04Z"
    mac: ENC[AES256_GCM,data:x2MPcRCqDcJlog2B0vdBHbaTmXMcwXoFR0/okmVCkpScrCPlh9H3kAs+9jzD3u4Z7LBkh/7zEPrKOzFWqKD9B6dLLCRK+Zk2WPW0UZnl/1sjdz4VgkuDAP4rMRB3dszO5Q3xbfgorKpUEEXEdZqnsjfh9dQ/DP/oQE/y6b8MpMM=,iv:8NQAmIpddWlklEwm7pLcJJp3mUQgFqAxBPaPkrfkeJ4=,tag:T3B3zLNxN4CQRANRp5uZ+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
