apiVersion: ENC[AES256_GCM,data:fQ8=,iv:bfz6wdHezkMsPIFCfYnHSZiRsuInlEDy0cAqM/ZkEr8=,tag:9Mme/+ypG0DB5epVXUljtw==,type:str]
kind: ENC[AES256_GCM,data:WivEoXrk,iv:XXE2Tgw69Efyy8S1VmsgjDgiXWtn51qlmLOYs131IyY=,tag:HwrE97vs2Ub+3QfurY0u2g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ipqqPpObhuFAVbZ7S8Y=,iv:oTgFDuKk/4yASdWhL+hNs9bXSLn16D+oIzQGj/CRHxk=,tag:GIZAcH/ZJ7rcZGhHeNDTpw==,type:str]
    namespace: ENC[AES256_GCM,data:YcG9JfIFrEt7dlYk,iv:maTiw2c5ddnNw96leNXFqkNkbZk8pWMzlIOkNR2IYi4=,tag:KTwDkas4ItxM0tpvvZL3Qg==,type:str]
type: ENC[AES256_GCM,data:gqA7Xd8W,iv:wdpZtP7GBo2GEbE/ytXCJ40TGemg1HAXJXo8xsZeBA8=,tag:uXM6unItQD0mS/fXw23y4A==,type:str]
stringData:
    Authorization: ENC[AES256_GCM,data:u9u9t+vpqzpXtZVT6gpcKEr7QzLc6soz3DjbtJxHdY1OY4S/BYzYNGw78Ynx42iCG2hjZF2Z/3bdDu95RlsjHX5BAQnaMXlMEg==,iv:LQbnAErMsGX2mr+ElpZAgSsgAUVjWNRLojl55Tax3E4=,tag:zUASvvl/JeRSsAdKL1/7SA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQTg1anZ2dWZNcHZIMEZz
            dW85NStGeUVYcERQeHdpNXJjNDIwQnNUS1QwCm9BVGZGb0ZCZS9OOXFiY295RlUz
            b1E0Vm9kdFVzNGNZVDNXUnFqVG5LdzAKLS0tIENxMmhCNnlFUlluVFpuc09abU9Y
            Q1ZPOFY1QWphUy9lSm5aRElnL0l0cHcKqc5zkzt3kw+SSt30ArEU2JKQQq14381L
            wHEzsIek3kRXPouC4QbPiiTsmciHQhPBjn2WrnOre/Dci252FhzLwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeU9nelhpRFJKWWhWcHV6
            emxMNHFxS0dnQjZ4bVhuNWlVaTk2cWhRQkVzClk1SUtyOE5YL0dvQmlCV0F3QWlp
            K2pabVBLbXprWEtBM0NOazdiaEdLOG8KLS0tIFhxUGorQlhuWnkrc2FwZXBkMFlq
            S2NmUkgrMlVybVkxUml2Q25sYlZZdkEKcAn88jBc2DrSnNg0PRIbo2ipf5Za1fPz
            bIY5juaA6gUJRPc4oi40JslvqT8rSCRrBC+iWc3lWR0zdeGqNmrkaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU09IcWxLRVFMLzlSUGc2
            Ty9VdWR5T2JydW9mcXRyeWt3ekR3RXZ2TmtJCnhRMGJ2emZBZWhiWTBzdjEydFhR
            UXZnMC9kdVUzTitseVhQSXQ1eTgwNjAKLS0tIHg5TlBCeno5U0lRS1l6QmNoemx4
            RjVrV1kwUWdJOHFMQzlvWHFLSktUc1kK7Eqy9IIk4f4JKEBwkhRJbftKrqHBY048
            /rnqH2J1ibmcwRrYl3auYzgzl2gBbaPnrN17gZPgpRESVny/fz7iUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-17T06:37:54Z"
    mac: ENC[AES256_GCM,data:12cttC/Xz02vCwaY9dl2pWd6TxM0whnDaM+fz1ti/dMUuWL97XdcKADKhhiLxEyYnSzYZEi8ZvgzWYmvcnAAFvmBnoJwG4A23tV3jEcfrTpWcQinc4SObvehQ614emXzr0NV0kAv4+iFUaXUAU0b0UaCTs76999RNFCiE7xi6L4=,iv:ehstNgXyQrMP8nitXg70rOhxxpwSYvfHgYrZvJm/wt8=,tag:hplr69TbPa1wDvijEQxEVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
