apiVersion: ENC[AES256_GCM,data:8FY=,iv:RTS/hZv+m/eR1G1M/SPlSv7119HbTtJAzbhlro3yc84=,tag:RlH5xRqeadYn2rUN4aI48Q==,type:str]
kind: ENC[AES256_GCM,data:e7rowCTY,iv:171yQ0y0nzm+Nqg4NAf1s9+sCGo+S+yOQ/tZR3rI6eM=,tag:JtVVMriaebgAXdJiNBq6CA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:N8Jd/3Fei5h8,iv:ECpK+uc4Z6fpZ7bw6xLYG11mTC5C6P0gaM2ZqRux8Ek=,tag:vxjFxqopiQ2YHeATuZTluQ==,type:str]
    namespace: ENC[AES256_GCM,data:7kppnA==,iv:zF8GDjtYd9b56okA/vbiwui/sVoVee07XkpylskUCwI=,tag:Mab23bOL6SEGFZhxCBHeAw==,type:str]
    annotations:
        serving.kserve.io/hf-endpoint: ENC[AES256_GCM,data:9TL28eA+I+X0FgvHzQ3mIrRYz4briA==,iv:LlXrVC3G8Ts5iIw8h9n3dwf9M7PFojnG6s3IBKH4AvE=,tag:FE/yjdw2Lq4/QO7wqu0hTg==,type:str]
type: ENC[AES256_GCM,data:I3Kh8TSc,iv:3drxZwcov9EJlqaNUf3T4q/eFvGZAbm7ji/GVyfTDuE=,tag:6rGnmxrGfXDkuWjaGS7Jhg==,type:str]
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:yYO+Bjqv64TjMLI7sloGFRQKrKQ8QW6PIdQN+hmtZ0lcsiX0MQ==,iv:lcCnjfsfWX7pn8zfH586HldPsrRNgmJ7I+RZTIpG26A=,tag:1Zp82Jw5LXlcImOVKVeEOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K1B4VWF5Zm9XSVVCOFNG
            T0xDMzRaSDBlTklYc29CL2Frek1Zd2NpQjI0CjhPbysvUHg1eElaQmxza3c5aDlI
            bHRUNjRydi9vY2ZhQnlhVEgzY2NrblEKLS0tIEI3K2N4MFhjdEF3VXBHTStQL3BV
            QXRSWEgvMjN0dG5tTXJ0QTZTTi8wNEEKW63u0t5ciySGkV8k+lnVAH1HuDg7WPLM
            ZZQxelwm4SlqKubsVW9/n8+ECsQqn8GV67UiLZ7r+zDn/yAyn3BzfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbHFNbUNHVmJyVWRaRHJG
            QzFiTHhUWFZaVTdicWxMOTF6T21sNWV2WVFvCktUc2ZrcmtZZk5hN0h1T0h0TjY0
            alZMQW1CYll6ZjM2bEYvRW1RT1pRZUkKLS0tIC94OXdjd1NwMzAyU2VIdlprUzRZ
            VXdDMnVrREFydC9PdUpQNlY1dTFzOW8KfBiCel1uPEM+X0X7c2koZJ6Gybc0H2/D
            eBXYgjs4Z+9DcdeWtmv8o5oumagO7GvbuoX/FTkRU37NPuygBVZJrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-01T17:35:55Z"
    mac: ENC[AES256_GCM,data:rsTfbdjOTKSXYpVBYKoYrCaQx7s7eBR3m+aWrQtxci9X06qBgKDQ8AkZNhlt+qS5KzvO1AMUMu0p3+gF4cjDSSFJct0uhSrZMCUcikbvnk5I4G26xJlEY+E2pqfd8RYEHedKKp/MKchwE0oVjt9ngFzbN+Dr88W2ayLZ5HXIDRI=,iv:BL/Cg9KWwkQF7XKKqq3WRSbADgdmE5eK28C7L9jOJMo=,tag:yS0oVHdNS9yvzS6jp+WjUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
