apiVersion: ENC[AES256_GCM,data:f5M=,iv:jziTbSROJP+bzd/n8+pIRmwRbdsXXRO8lDrlsjV8kB4=,tag:9GzFfEttJkht/Z6/iq6tMQ==,type:str]
kind: ENC[AES256_GCM,data:3F9jFyaO,iv:uUkKPWOCHOgWqS78lYw69Gleu9a+XubHwkalR5YYuLM=,tag:i6qcpbO81FRdoaoyUu0coA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aOa2diKeNQTSOeCQQpEjyubaSQ==,iv:JuFcCKcaOmP6J9p0i+mnoSe8DjJ7+hGPa54B7i/pEzY=,tag:8Ir5s7GsjIlXy3NM+IYZfA==,type:str]
    namespace: ENC[AES256_GCM,data:tgUJaw==,iv:yKzAxOV7/6Hv3KZwYQPNuSKDtI8TvTDZjYmujy52aDY=,tag:GUTivAxEU2aNtB8iqGXtVg==,type:str]
type: ENC[AES256_GCM,data:vUCPAlJB,iv:EYC+w+OYonwy/mFpxuK0L3K/oGcFm2ucP/va+gN29ts=,tag:itiIvJXiduI9ZQrZASY1Lg==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Xxf6/IiZjAo3YknqY7BIPbaaKa8fHa8XZp/VoxgeT0Y=,iv:wVQRBsuN0uAESWATLa9oIfZkcqW2f/Q4sf4yOfnc5hU=,tag:/pKJDqxnlPIQSlEMknRMjA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FX5VCmtK8UTA27svIhTeUsvFbEVAlGxinZMSQr9vT1IeDBpbt4CmK7h1J84WVBv/fgvfHrW+t9u3ry8YZZr8,iv:SEuo/+2m5FFjdHI0T2T7hlTWWG9A+yjPq10N2pJe0/0=,tag:9X3NVaXZEo+HwYAdqHXAGQ==,type:str]
    AWS_ENDPOINT_URL: ENC[AES256_GCM,data:GAp/GK17jD0bdh4Wi6EHowpkK2zVrTmy,iv:OtpNDLkThE0Q0SNZ8oR81LfeMKwe1U14aF6781HPgeU=,tag:W/6Is/lvW9RnaB8t7acr1A==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:e9mlgO9KHLbY,iv:kz0ndUMDJDbgeigAGoCNnbwvwIkBeBlF9h0y6oPCHCw=,tag:e2XmFTyxLTcJ9gmDa757ow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOGdXOFpsY254ODRwWUpu
            ejF0T0ZGck5laXAvNExFQTZtdFN4V0lxNGdvCkhzeDhXWmcxaHBxQmFBT2ZDR0ZM
            L1lPY2cwZGdiYXI3eTA2YUs3YUJkL1kKLS0tIGJhZ0pzQmUrVGN5VlRPaE1CTnRv
            UmR3Zit2NUQ1TlJ3TmNEemVPVlZWc1EKf6Ib8TzLXkWnvs3Ge+EwKjVpfrp2Jn7R
            vS3LOrDqMIZKYF007fF9G5ffu58izOY5i8qV3mYFPUzsiqEHoAOvEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-02T13:37:19Z"
    mac: ENC[AES256_GCM,data:Ijc+c3CQ2r7cPf5R5QWrB+jP7tx9oL2OZ1az6fqzCWLP8ukXjqnZu2vsz5kwbf1IPNPt6Ne5+VDIRV1462FYk6VcobbJstFnnfusJjE/vdXfFnjzFP+BlZ473GvVabjUiBAKnAjnTuoTRmvdKzykD47aaFv5uxPH3RvBZrArE/c=,iv:aRbQweUzg5BIt0lp0nIQ/8npsh7Vyilex05Wj1W5C5w=,tag:gUJOXFuXg4NtbTyKR7NbTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
