apiVersion: ENC[AES256_GCM,data:Bm0=,iv:k1IhUYbnDFvlk9fnQUOsvxYYjkAdlCK5uF0+bsZl/so=,tag:WzWeEYgxQMAOjYtNJFe5bA==,type:str]
kind: ENC[AES256_GCM,data:NfNnOCCt,iv:pVxUak158or5dYFji1zZaWRv9KMrBJrfXwZGzu60ufw=,tag:8FJ0GI+lBHsTXvxVYcQSuw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0qHxgAL5uIZHZp90LoRD7Q==,iv:oHx9SeWP4QZHdp3Xy2ySuL0Rs0Td1kUh2pmdpuB7+uk=,tag:4TwU0j+ygIwpxr50AV+Aog==,type:str]
    namespace: ENC[AES256_GCM,data:UaEq,iv:BQ6Pw9BRh3lmiNd2krn1BckoEQWF6uR2jHuEp8GMogs=,tag:bqHUy/4KiJnU7tbl8tEadQ==,type:str]
type: ENC[AES256_GCM,data:RbpOPtul,iv:M2/LLpJ4vWxl6VisMhM+DhLwL2biKUWsPDb+XEMeLLU=,tag:+a80WaIE0F88jvnydRI8LA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:8ga7gyko1opvKxxIFw7oCJBJPR4=,iv:ELHIwN8qXoSW+BznZqATcKBT7whWrjJ/zviPnYxpCzw=,tag:HlsuXDMO8y/UnXWXHJQvmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUjJ5Y29MZXcyVnU3WkZO
            aWwwQU1TdC83TzRFeDJKYkpacEoxUTNHZFdBCm44Zk1JU1UrN1Z2aHE5ZFJRZ0tT
            TjRKSmpTRWtqWE9lRXRQOUVySG5maG8KLS0tIGdvSGZKMFJVOTEycHp6UWw4TzI5
            TkUrR3ZSRmhFUXFPM003dCt0OGVhMG8KO+t0hoB9NZjLJXKUY3wKsTIHo6uEwu7H
            9RiJJwuZ+0NGI44Gbu3FnN9VzOF4TMrxD5Rih+Pj/Q11tjE+wCDGyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMWdkZGhHS0tEUU1UQmx4
            VG5TSC84eXpWZ0Npd2tIdm11Z2lpY09VeXp3CmFZR1Vyc0lQMmZhNTdYQ2FKWHVo
            aS9uZmw2WEF6dmZHSk9hSWJOL1BlOUEKLS0tIElxQWxXZ2JodGRoeDRBRjAzVzVP
            bFAwVDlYUCsxMjFHYnJCL0NZZ0RxOXcKlMy/eDqh50oWeCorJA+7v6tkauCAzya6
            50n0G6sVaK/psCnhyL6oeMCXgZSG0fKt1WMHf1uy/wAa6HOdW7zizg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RWFkRWpxeVpxMi9SS0g4
            L3pBTkY5TE9jVkg3N3lHK3VZWm0vSXZSb1U4CmcxcjVDeWYzSzVERnY5R3c4M3dC
            enBNb2ZRTHhDN1NhQWptaUtoeGtKdGcKLS0tIE5pYVdvWUZpRjdoOVMxRWtOL2k1
            ZzNibnRFYi9iM0JIaW9jblhXUnFsSWsKpPAIL93XhfVhY7TVSgw7WfySlQBcUGKk
            BUMPdlqCJvgNf3dxCDJaMp8Md0UMtyVmFANJ+V1C8XEDIL4PFuvfLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-15T08:25:14Z"
    mac: ENC[AES256_GCM,data:WDT3hqttiQwZnrN3YLv1jkgJx+bSrjAPxvKTam7jAM+lU+xui0IxA0lwbs0XSzEL+iNa9jeTbwVGehnDNrbe1jJwQt3aA1t+Je9vQYBeRjZ0xjSnMfFtKUa8BgUsAPq85jp2SWlT3AGTgr+Y0F+e9LP7bjLm5uZRsmzTS0nNWD0=,iv:iNrwNXtuCWlASEIB3BStlldDiMXej+xQhaMtnzqtc0Q=,tag:Zs7wTVGC4HD1yJAz+V0Itw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
