apiVersion: ENC[AES256_GCM,data:2HY=,iv:c632+NK+mh991JwC+2+ktpesr3iSlSQlTP9G44wDpYs=,tag:0AZXXoiJmaw4yzjz6mA4sg==,type:str]
kind: ENC[AES256_GCM,data:9OWum0yR,iv:HQbTbg+NsljjHeeWrRVhM5HDxTY6QcyE+qNhBC8e++s=,tag:heDAc1iiVaLDBW+TFcS2Mw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cWgXgD9wSoBlwMAxvXV5lk0IySdvaShP0bF44w==,iv:2pj8XUOv4T/4UpBk68MGnuua9mx5bi1peztZB/HFXe8=,tag:vuu/PYLEtzIHSswN1LHzUg==,type:str]
    namespace: ENC[AES256_GCM,data:vV8djMwS,iv:7MBZq/EV/9lD2gXElHMnJd5sVb5KBZQcd3A/aFH6dt8=,tag:frJIyD9IF/y4IGL09q534g==,type:str]
type: ENC[AES256_GCM,data:XAzaGhpN,iv:AuB5lj+6gsuxnY7by7MXIQiihRUnGu2MsFH8NnoOIuc=,tag:5T/LEoSbUhS4U+qPhEy2PA==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TcXXwG25aR11Ry4EeLS21ENZCLw=,iv:4yehDD6KaK1dZs+llUGK7QKpVkvIqAB7oABBgnv3rq4=,tag:ORhtqyhpnBXftNMdLdr3kg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xeeSUrDT5sS9PThEtpOOz9BtByw/WXLVbiJ0fw9+YkcqYvo5aC+3kw==,iv:JzDNVVxybaoZVbOpEeFVGrvpKbLunz0UyEsVb1QbOUY=,tag:8QgDtxrgOFe5RF5wI67gbQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:a+zr0w==,iv:aAzljkTYMh9xaXiu46OLIo75MhA/Y0uay86/eyy4nsM=,tag:opyyDzxbTTyOn8aq1otttA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYUV0ZlBQTEhUSjl1cVh2
            WklBUWpyZW12S0lSTEIzd2FpYU5XMVFLQUhZCjkvbDRQYUo2bUplTkU0WmthUW9k
            eE9Pb05tblhkSlJKTHFFZ0k4OTJDRlEKLS0tIHpVT3IwdnBlNG50akFHdkZjZFhT
            U0xsODIyRG12UlUrRXljblZ6NUJCekUKOHE0YGNOMhiVYZF/CmLhn7CFzY6VmYGS
            m+R+tKzapRrUy5VYG3CPAlObrTNureQRpd2u99KS9lU2bGxsucDvbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTElxaEJXa3g0cW51MzV6
            a0hMWnkvTUNQaWdNbGIzOHFWTzEvdGoreEhvCm9jQ2l6T0JDOEZXajZnNllsUVpv
            ek15M1pKRVdnMHJHejBpeFE2WDlHOEEKLS0tIFRmS1c1a3ZwZEg3QTJ2dVlRZWE0
            em1IZDc2eFNwVVV3UE90UTRoYk5NZzgK0iNveeewz/Q0QCfCZ5cFqAhUi0h78gKp
            iIsBpo+7nlHr5TNt2eo7CVdQ1uxNpY5iek0FVj6BgCEuq+V+M6gNYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY1hlU3Y4cHBtOHNhWUox
            c2lmb2lQdFJ2TDZOSjVQWEpDL3lWdWh6bUM0CnQ2T0lpY3FabThsYnh6OHVkbmpm
            THcyQ3J6VXhvUTcvWXV3a0QyMVl3a3MKLS0tIEo0Zi9Fc1pPRW04alNaaWxzR0sx
            cDRLUnZ3VkZIU0NETjF1RXpDdEJ6YkkKPIYQbObVKUravkIDPHskJLtibva/NXG3
            2NCFnxpFSqwBGCqLu9CGxAg0z0Fe39Cr72vnXbapODw2jaBVwpXqhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-14T22:09:12Z"
    mac: ENC[AES256_GCM,data:5XLSDXXopaf5qPlH9gehYFHoq9cnElKm5ALJtzqYKOchfrSnWLMnGw/RGNJDfcqGhawz4vACLL87H5MAPJFYFF0x6iQQU+jJuZ6vO18CFVtVMMvXOJcwhtpslQNgsqcgQTKTZTFY3GWqNZBHxvA77KPA+IXtzijRN8SnYSprfgY=,iv:j/eDvPpY8Zi1aYdNZcuDcRdorLEi3Bv6UBipDENW7to=,tag:4vshpaK9OjE/n4HfiUI9BQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
