apiVersion: ENC[AES256_GCM,data:uiY=,iv:bsWbJ873WMPYR+JCCCruOrhb87Cv7kvPxNObzo8zf4g=,tag:8TFgrEAamMDqPOGjdYjOog==,type:str]
kind: ENC[AES256_GCM,data:q9XRWCGa,iv:3e95vjWhS3l3pHjgfmqbisRfhYLAWGMZ5pbHpIxFQUw=,tag:Kvjhqc6+9DyBTl5INL2ARQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2odJcbNH5wIo86T/aA==,iv:6+/IhFNrDbUv+fAs+QR4d8DZZqQbE9+vZrwF5eF9O/I=,tag:tuvCiuwEbKsNr9MLj2wUKQ==,type:str]
    namespace: ENC[AES256_GCM,data:TXq0BXpYSUmB,iv:BKWpX/7XfCLxKCsQL70STg7+m1VaLGUbbYT3rZlsNDs=,tag:m5V9lRs2pWfdCiuY05D3gg==,type:str]
type: ENC[AES256_GCM,data:GDUCZI9k,iv:g1YOQaYKcesD2cxWcbT6PgGuD+1Pl8XPfSMkSvF9d6U=,tag:jEiVJwl98Tnu3RO5ApGrcw==,type:str]
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:9l0K1Iiv9npJJdZuPho4RcCfhMo1y7H6cxss71augKrn79lOdk+Eo5IpNHaAx1zDf0LzsLR03iCf4QZhPD9DaE3//7J6BkqBcbRi3ComBPD/myRMGzA6DtMj4iAcn88Ify8CQyYQdHYYCXba5KDh+GQKJRRWK8NGc1jcHP6YKwo=,iv:Z68xVCIgSTs18pk7zay2TZgBTsQpZwCPGNj+eEBbx9E=,tag:wXoTlzIOzwELC4r9YL06hQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:8R1eVUoIrsWjzxK5wY4Trs793CgVLvEpxWWDaULTUg==,iv:4e0ktoE9WcbC+u80Polv/3zNaWnSbRzxFeOn5bY4oXg=,tag:3QeNDAjLUzpkvnQA4CgNNw==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:R/zldJS5jCkN1zCPwMftdR42yJ7YnRarVbwNdQCokUmVM7OdmLw09nO71ATNgeGInW5pDIiCNtJ/uXuc1ndv3uevNfF1+remEGHA1bXNxclk2zMpw4BMK/3ycgwi+vMdPunMHprKgftwU1dMx3dFAMqgByltJ83kewOrtzlqxQm9lg2HodjAldoiEDUoHRjjWJNVzYoHWO4j4SnJU0aKVy5D2i+S31Zu7rpIaiqSnfLV38LqAY+K4kcmvN7FlVCpJ+ntA2NdFh7WP7sAHzVhbSr+HjoQ2+5nfgbPv/qZ6yPGsDwI1mRPEbwD9W0kD0seS5FjOoxwkkMSyfMnAofKE1VowveEGfHX4bszADyurpaOJCa2L3zQ8bF3gXhHf0nPGe/KAF6DoUaL3L1o7GHWLGibqrYNl7lIW2W+EYhKAm5dvTdxwOOzrYhIo8FA8Y8F+EcygKKCK9MfEcVAbslmkL8PEJ4XkhBe2GE6M2PEpJ+NmuHtATT576qZqmEQ44Ye,iv:cpmcv7LfElwY75DJA3y0yDDQZnW90H2NfSHt+eyofZ0=,tag:eslgRzpS/slYKDxl7iZmXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbTk0MDVrdVJCMWZGa2xs
            a2laYmlkY0xxUVQyOWRpWU1ybmpUaGNwN1dBCjYzdzI4dk13d3FvdTBySm5QQ1h6
            WEF6VTFBVjJXUDVrMnVVMFZnMTlNRmsKLS0tIE1XY2dpemV2MDdkV3pBdEs3cXcv
            WVZIeEdKSlhqaFdRajJqemk1RGt3a1UKM+6V62YkjlIxAMmEzQAMyTtG0IbasneJ
            vIcF3wGl6xDsQ1a/ubqd9Q8tpG1DUb4Ow+MVn611MSynIuVjhF/bHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcC9vWXJsc2xFdmZOUnJj
            U05YNHJKUEYvWVg5aU53MDdScmpWTS8xdkVZCkcvQk4rNEdjUzlIcGQvaGRWOXFH
            Nm1kV2FBNUM0NERrVDF2SVJTUDc5SHcKLS0tIHcycTB0UDdWcnNWNWxPaVNxdUU3
            N0JvRm9ubFk3azJHakphQWJraGlyd1kKHMyBdlY4Kulzz55Q/aMfdOqyc9SEjpLb
            DrlweTg51DzZM609ZnmBatUnFxoqBSdKyGLrYCFVeXzj/Be7WmFjqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZlo4NlNkSFpmOVFDdDlJ
            SVBLOWxrMHd6WXQ1V3BjalhmM3JTdW5YUW1VClExSW1WOGpaUElzVi93THVUdXBo
            OTBqN3JJTWZSK0hEcm9jOXhjYXVsMXcKLS0tIGZQNmc3b0cwWFpFVGdlMzIyUGFp
            NzlMc3FvMjlOV3VqN1lCUGRvN2pkYzgKPD2QAbdFwqRhK2WG7sTcq5rZB6ztPQto
            tbqS0zRsolQnRGkTiEuG9liSgQswG0w/BAyxu5DJzdQKEqeKxuYv1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-15T13:50:00Z"
    mac: ENC[AES256_GCM,data:y1N4e+13IyFYcpmhOi3xXWguoY7U3AOnO5PxdITtuJdbGJv+uDHVOWE80aODSBGxh+6BGQBMQq3lv9BVd17ykRStFx8EYZjVa5ioNThWD7iIq82uD4otIVfnXFTZM11noNokHAkPc7T+W1FKx+vCE8EB6vSh7jYHSqq7BqsQPJs=,iv:tRSlLJYPXNWXBoIGAbXzkuhLAKe/CRojDsWUreiDZQg=,tag:X05weJxIaUP8AXbhUphajQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
