apiVersion: ENC[AES256_GCM,data:xmA=,iv:7wMTVRbCXNOoJC7cTzmYDJlEoidPypF5NYycR/vYWtc=,tag:TlRaYgpADO6tpeyHWSpM7w==,type:str]
kind: ENC[AES256_GCM,data:di8LsARE,iv:/tYsWKHecG8/bucGV02iT2Ds5GM7H6hiWLZAbO2w9DQ=,tag:+tKF52IWbF29VcHxYMyehg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2o0Ri2cNWB7pnTBCtfAFB8VueQaPrI9TnFQQxU7U,iv:LTP8DPHxbqSwri8GxU0enL/4nYcguORXf72q1Sz6+wM=,tag:4KwtVOKcK+TipvFyQ7ty9w==,type:str]
    namespace: ENC[AES256_GCM,data:dtdw8rZPgSno,iv:GzBqf8BjS+p2LbSZ6l6qROzZF5xy5PfjYejg8NvG3UI=,tag:cG3wmxChBngSplzYpwDRWw==,type:str]
type: ENC[AES256_GCM,data:MXxC5IRK,iv:Lm1/Pm/FZpmZ7QyeFUTlmP3AhohRw0p9aoe2Hc9g5vI=,tag:G5wSz+jZsHeUDKl5CN2z8Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:sAJ4FtQUw7WY,iv:auIKvfCSkRcPFV88Yr0Mzrbzc4EL9/pa3mXRYtLMXYw=,tag:z/nu9lHgUFJnJBsNs6jomQ==,type:str]
    password: ENC[AES256_GCM,data:bCdZRsPSFpWfa337cyqt81T1rWT1he1EAlUEWon+RkI=,iv:Ca52nzgNjJCiI9Ikm8b+bvy2GPw7zCa+Rt62Gw2PQfg=,tag:Xk0C3K73PWWY2RxOK+Jt3g==,type:str]
    database: ENC[AES256_GCM,data:xY4a2lU6EKcX,iv:pMCB+/o6OvMWsdjeGl5hFSluBzeBSMNNy5KJL6ZY12c=,tag:v/kMKN5MscQ8lL7xvDPXdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSllRakErMm1zUVlLUU96
            Z0FuMVBlOFhvNStteVFUMDJJNFNjRkI1WVJvCnNoN2w4dUcxZzh3aU1kQWw5WWdw
            MDBNb2F3Z2hzRjFuTllHTmpSSk1GckkKLS0tIDFHckpIMGM4ekczWmNXMzRUdFZW
            dU0vbHB1cmM1OTE3b2Z4bkFPVXNQbkkKcKlEOKmN+4nVSqwZeAZLwB+E4dkxuN0I
            dAw2dGcGcl+t2XODH/iCWLGbh8wABqeXTGnAU8+7MKlIbLEHfUxZsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyclNtd2MvLy9XMmJla0FM
            TysxQTlwa2phaXJYMlVwRmRzb1RNYVNVVlE0CkRxeEd5Und5ZmxHc09NZjlSZDgr
            NjNxNFZEcW5sL0V3bHEwZmpML2tCM2sKLS0tIEFWMHk3VTVQMzh5UzBHMXBUQ0xv
            ZzRoYTBEY01IY0tUSlltRXZEVTN3VEUKwnWqgzZ7iFNF5rO2R4zce9GgTIC3sxui
            4TAhZuY9XFRvxsxmAl+U+8ind8lio/D2SmD64PbiUxOqFRllQeQqsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ3JzL2ZHbHVvWitzSHpm
            c3ByS0VqSW9yV2dvVVRUYUV3bjJmZ0k2bmdvCjRrTXdHRWpEbjdCM2V3bmlucnRI
            ZStaQzh2d3daa0lPUk9TUlZCN1UxckEKLS0tIEUrUmQ2ZGNHcmNIVEJ4SEhXVEhS
            UGVqRDExcHBqY3N1ODRVK0dJSWtTZk0Klr0P947RHwGnfwBxdpMdYDhnm/k0jhs0
            6PDoJiQ+YSv8sNSmCNzC94Vvf4QEv18MzwNS9Dliu+oC3jrjgdNLSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-15T11:39:46Z"
    mac: ENC[AES256_GCM,data:TcFYkkfAGYZE/9E2zo1tP54LuO+V+ckKh7UO2VAoDaynExP9x+mbO05PfewdvdoTWGziHxi7gRliotUZbAQfYlYb+TCvfbpiQLo08nZ8/fEgoQlMcs+ZdHnIS3b9UT562mHHTrIPa/fhPZB0VkYOaElnF5jFIFV+ur/fl2F3Zho=,iv:NMlSTVIT0TYVw00IE1fVqJqDH532fXVQXeDtzUb3mc8=,tag:0scVL2+Kn0FTMx9qhaUzSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
