apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nad-vlan-2080.yaml
  - vlan-routes-configmap.yaml
  - storage.yaml
  - sources.yaml
  - helmrelease.yaml
  - httproutes.yaml
