apiVersion: ENC[AES256_GCM,data:HIk=,iv:V4R9niy7Qz3XaieQTPLKcZwx81z4K6TFMX9WA/P5Lfw=,tag:a681MbH9HMUNF+tK3DDs1w==,type:str]
kind: ENC[AES256_GCM,data:meGXi4Hf,iv:c4S+vJazML30sh4yrwV8ZAixFfdSHKKxs0vuIgIQ0R8=,tag:8SWJ7LWoavweLy6wLA1u9w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nbhhU5uRM2XNWWToFCaKbhbrBLypci22b8ud,iv:pLYD0bqsEBxRxd9hafy/wrHwpJgbZhQiTY1cf77B6MM=,tag:gkB30gOud1hqIrXfl61QtA==,type:str]
    namespace: ENC[AES256_GCM,data:63C99Ms=,iv:iVpwly3GmiaFZFkuDDQmYl+cVxbZiHJ1gmF4FEEOCi4=,tag:HjEWioU6AfXTSSSgi9gdsQ==,type:str]
type: ENC[AES256_GCM,data:2u0j1BL0,iv:rio8lxdtZYQQ6ms6LO2SzE4i73vzkxM5a8MFRU6RiVk=,tag:57kIyZqcqXNVqy1YjmSkhg==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TOb6AD8KOcoevzjIIn6VUGK4HgQ=,iv:XNpcQc1HKaGaDS6syK30Az00nljtpi/fODJLCYHML+k=,tag:NCrFH1drsQXEPhOp3myY7w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ReX+GDy9pg6XlYmUu/gkR1rphfiFcDdue6rVv8WHlhkZegw9tHGlrQ==,iv:7KzDXp2fNGqnEfcwja65Ob12YR+w81PnfLrFw5iU+pg=,tag:z2OCxN6uSjhQyZAsvXPV/g==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:voTjUA==,iv:aGnY4vEseoOj78lsm//f/rSPm6E7rV0EWKQhVuiHG60=,tag:xRwDPJ3w0Ql1GXpDJINhjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQUx5SS9aMk9wenNXSG5q
            MDJzaVZnL1NGemZqUDN5cS9MM0x6SnR0N21vCnNtOUlEbDNiOTk3TlZDb2drMkVk
            a1QvNkVnNUhrVi9MTTJmRHlqZjlmUUkKLS0tIHNWUFJ0dEgvbXd6NUJreDAxTjJR
            c01MdG9GdFREaVN3Q0FYZmk4SHV1NjgK5NlhKYJ7ZusihB/1wYnqckGKAfUkxUbb
            6xPm7grKK1+qQRk3+4kCmvkuLrBw8Jkb+clWrsRVOYL4axgKSDhZfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUm1sYjRsRHBhZ1VFT3Rs
            eFNKT2c3bm1xWllFeHlwY000MnNNaks1L2h3CmlmdXRHQ3Fid3lyclFPNjVleFl0
            cFZOQkorTkFTZUhmYTZSRjh0MWdQelUKLS0tIGhySmlvMmxkTVV3N29DT3JzRGEr
            KzIyWmJiV2dNbnQ3b2NSYVBzNU5Pa0kKRAoRuByxofXdWHDLvjuIaga5l66awV1E
            NV8GpMuQZ4ULQDXMbfRyh4Z1J9jqKjpo7tQhnLUs5vQ6wvQpm74GHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OXZqdmU4UW1xUnd2dHd2
            RjlTM2VNV2c1Tjd6N25KNVVqeDVRYzZneW5jCldQdXcwVTZTSmJ4bFBuRk91MEFn
            SGNReEVKTTQ1c1U4QitvOG1jVnRlTUEKLS0tIEdmZ1VVWTdtMjZhVERYa3ZOSFNj
            YzFOU3ovUWdwYmNqQm9nZHRxRU5kVEkKCaO0pOgmvI9hOLyMknA0ea0Q4p0DZNNU
            xWwgWUwGAc8zvukMhuDxacH2rR6KhLtp7MiSwGyWLA81QaDFKiLKyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-24T14:38:17Z"
    mac: ENC[AES256_GCM,data:wBgG1uvHVNfNbkKOIpOuZ2gTo/mdBbNlf0j4I7XjYf5olLEdpACNdebw6QS+4mUpXb3EqNKapPDgcaN1NXkabUYmh9mp+l8HWgyZqdEes5Z/XmthYPwS7guK8otjypPRGIH4mf6AQFgur9NP4kjEw93pYov/0tAK6rl4s/GNwcM=,iv:lp3JlfsG+rk6mu1czM4GAf819WjxMnOvpki4UW0ODOI=,tag:WOyejr97gyPMtbK+rZFXgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
