#ENC[AES256_GCM,data:bIy+qKszNrxhTuLBfolkyYxqmWzF1xdElFyLxufPd11UifCne7yIVGdgLWTyqVL/3vswPnLpl84shlBaLbHEl0EMBE/TzQ==,iv:Iw0yB14/7u3Ff/2A+CDVCQZ1UK1hUHoOABtCz6pAKu4=,tag:kZ6MBUH5x5m01bowHblLeQ==,type:comment]
#ENC[AES256_GCM,data:ud0Ffj+OkOnL+ehHlA8srQXLkdKTnMS2RnZNSFbO14iWy+/BHwUslDqNWy2gpzqqb9cvo2MPQtr/7UPB04CjyCC6l9in,iv:HNrDk2HWAqeEOF2XFcUnRvFtvCxBwlK490tKezgrkcI=,tag:3M37+3c8JV/AScttbb30jA==,type:comment]
#ENC[AES256_GCM,data:9kxYgvQUti80RxNOteCb35ZLYwWxNipF4eftMR15oIr69RG5BHvoDeUQcKC469bbTVUP+A2293EXjCsM9Pfc+aMdoBqQX19S,iv:K5D50g9KvhdllpJ4OeXrzXlg8xLZCes/N3AlnV+6c+Q=,tag:/fXXpuZK14juGFZ3RvSV0A==,type:comment]
#ENC[AES256_GCM,data:260gHAqkAG8LYqN1u8rUjvKMgcgg9yx/NxX5VV1tYfaa9OqT7d3sJg8nt1cR9weKWY/frEap,iv:ovBaLyUjrBXLh276GKyHyMQjsMpHS4jaBR02KVhgp6g=,tag:UYrDleuDGLwlqrszeNCvxQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:USc=,iv:wYJeveyo4uicS1Sy/Os1IjjimTvHXpd1DO4MqFJUuRk=,tag:S0EX5DYlrPpLVt3eFe2HKA==,type:str]
kind: ENC[AES256_GCM,data:0ClFGiT4,iv:zrq879/LLeuuPBZHT3SIGjmhLAMdisxGJ+GNL+fzYnY=,tag:VViAe19eNC5QS6dECULzNg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZfA6+F4eL4zZ9mWwndr6+8/qy4JsjDXfnV4=,iv:1mmB21OQROWt77CnDU4YCi/nbBG9pz+hGOSaOXG/GkU=,tag:8jxJvSNF4h1fzFBAsvEznQ==,type:str]
    namespace: ENC[AES256_GCM,data:bNX1K64=,iv:Dxgfwt88krp+2Ib+Sc+Y1qzk2H4ftoZSlyv+UqgEPUE=,tag:25YTKBwTp3tOAShWzgqjkA==,type:str]
type: ENC[AES256_GCM,data:YhbxrvG8,iv:3eT72Xrtg0YXFKs2fay++ws5zdQVInam/OtgS4C+qds=,tag:5aKST1oy4Vlb9/8L4dCGHg==,type:str]
data:
    username: ENC[AES256_GCM,data:qbXyvVdj8/8=,iv:+DrCo8N1cm2yYNIseP7ERSeSMCl4IAA+0aKMT19zcmM=,tag:ye7IVycDqwmYTbfFUGESfQ==,type:str]
    password: ENC[AES256_GCM,data:GRE6I3jmxOumV4pMxcYeAPMg+K9OClR4c1p5DiiaiCBy9uV321XRTg==,iv:AmgSHBw86D9wR9jTjDftsPo5qbHLnsDwitqykWHGZv4=,tag:n3gbhFEqNGJNBD9hcZ4lqQ==,type:str]
    database: ENC[AES256_GCM,data:vYNbBE/TV2Q=,iv:QMBNY9TJJOvODtBALt5mRlXQio2xFkH1NM9ZckN6/3g=,tag:tf8Th6NK3tFlrFWwhELE+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZk0vandLQUZmeUFUNnF1
            cU1DZWcwRC96b0t1NXl4YzFYTFVKNi90SVZZCjFzNUU3Um1vNjczcVBlMFptcUlz
            YkVLWExNT0ptd2dDL1BEdjNpY0h1U2sKLS0tIENPb1Z0S01SdndnbGxpWHFiSUkx
            NzRpL2NuZDJWYSsvSnRFQ1g0blg2enMKGf9h6beLtwOVSwfqSP5kRLfOF0x2OePa
            pXFcXTQNnry2m3nGO/AGM+Qin201WSVAWeqbXRV4dm/CSRQI8yEgHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTEhDUGkvMythWHJCSS9P
            b2NudzhZL3NLOUpoT1ZXSUhpdVFhRGtKTGl3CjZHL21KNXNsM1QzSW5ObjBUc2tQ
            SlI4NjBBeCtTVEFwSk1vTXZwSks5UHcKLS0tIGNZTGlnc2NjTXJaVCtQZW5aRVcz
            RVdpeGZMOCtKUUJmbUVCOWNwM0pmcTgK8+5LIWQGsOyEsseRiZIweuLa9u9jW+b1
            Lc6ZX1iqcD6UIVooJr4QQKcvIya7kUUkBOja0jSyLGdINiEupKhsYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd1JaRUx1MDJlWlVyN3p4
            SUxZdXA4ZXRHQVlSaUFnSithaHRpKytqd244CkZCSWlmeGJiU0tHdSs0bkNrWGJv
            VUFRQUdObmlJQ2o1RlNRVGl5cUt2OFEKLS0tIFYxcHVaSWYxNWhER1ErZWh2dmht
            OGJwdDQ1cjN2c2JSdFVhVVV2V2RqekEKkz/Utt4vahCIsDeEOTuAK1MDNjEOlRdP
            WZ+6/r9TLpgpszl2xRpRGMWek4wlooheSzk5qQXVYUBir7nBdPljew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-24T14:36:20Z"
    mac: ENC[AES256_GCM,data:eEpvSSHnty2Gy96xzAX2qB8I58fWkwa8Cb8tvhYGLkTDy4CWxdyoM5QDgiblsXF0X5SMpQkDIhDQ7CsFo6D8sOYXtta9oWNYe3/kc926sOuh/YxpYWPQ0UOKT2LOFqkm+rMkbvH88NwF5XaJED46mtqNJJypyzIVNp/3Hci2Bek=,iv:qYiRuV25cL99qJfXe+4iCmkckLpPx4xL9U8npndbmGU=,tag:C/3LyDcMBVrYppBTqXFfYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
