apiVersion: ENC[AES256_GCM,data:nag=,iv:ANEQqm/u4fio0XnUZ8Z/YKazxeLo1COODCPOHEEE8oc=,tag:canCpsbNcRMcAsV6I3HTvw==,type:str]
kind: ENC[AES256_GCM,data:rYVWH+y1,iv:RCQUH2uavPD5BeuVqOAr4mnzl7usozmi2734RMY7zIg=,tag:Rww9g8QM4Xs0mInq6P/adQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HzKT4iKKGZJvJGoQ/gpHIrPvUWI=,iv:whLr5O2YxacDqBOBkIZ0kPDmJR9rMpXOAi4AuK3E1fA=,tag:MwZVk3M1tLzL2xa2WTDIqw==,type:str]
    namespace: ENC[AES256_GCM,data:kCqNDa2A,iv:S/7yEBzmrLndxMhruui1UBDII2zLFB1ys2LzEjQjOjc=,tag:qUTYP7DXrEG9gg5LCmNu9g==,type:str]
type: ENC[AES256_GCM,data:nX5DQsi3,iv:lB9ziTidQzEuxWTwwSmN/G5+bH7//3cud7Rtqp8RcF0=,tag:Po8GqhfS3q5/aNKMTiNktg==,type:str]
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:8MKLVHp+p71UJL8ORpLv4EVyYau2RDHmFvoKKPlbiaE=,iv:FhGmggj9WnZ1gSQzK4uTJHvsD616IFPyaYkWpVlQ96A=,tag:Ny8t9td7DYnrmitiThG/Dg==,type:str]
    HINDSIGHT_C_API_KEY: ENC[AES256_GCM,data:FWqLUx8D39NceDSLqQ/HlX5OqFLiBvZA4pTHebNlrQnLRkutKhLTV3/RQbxM8j9Fr49/8mH+POQBh0vuMSkPxg==,iv:sbUhdWK0XZZMIDd/i3RHStcIR8g8+IGOASG6V14EV1A=,tag:78BuLPgvLOlAWuKDJ8X6cw==,type:str]
    HINDSIGHT_D_API_KEY: ENC[AES256_GCM,data:frMgVdK8vWDPcwip7Ew/jNejVjuuHTWyIs01vv46uQp4VgVqrpIkT5sbUyJ8LcyBgLemkiRBmyCoIplc2t5+7w==,iv:IAG7JUXtQJx6OpCEBBT/691wX7Oeoj4tf+Y/Zd1OClc=,tag:+ShbG+svQPj0Jrrxf4NiHg==,type:str]
    HINDSIGHT_L_API_KEY: ENC[AES256_GCM,data:Ko8PTHfPuO0B+sqMP+7pWkP4ioOOdEKcuueBtdKehz4iOxxkgLmhRgPPE1G4dn2mCu+D254hyZodMfVk9d6IsQ==,iv:ciIjqy8dzEAxb7iJ+wvvK6eI1dx+5rEJJKTTVby4ry0=,tag:smGRCWF0iMsTfrkQ4RIUOQ==,type:str]
    MATRIX_ALLOWED_ROOMS: ENC[AES256_GCM,data:HQcvRBSgkCHDSvItgkUAhtlAU0VaAc+TGicsyOiE5FvyHVTCg8E=,iv:qN9AuJT56wqYry2s0V6FItIgW4HpfJ0g2s9cikheq6A=,tag:w3m9DsMbRJVE4kNkXeYfKQ==,type:str]
    MATRIX_C_ACCESS_TOKEN: ENC[AES256_GCM,data:PeeE4hHgdnAivEljxcEfLboF51oRGtUTRPJgBdWxjJJ8lm6PYALlyGA=,iv:UdFclIZ4+9SaSHMJv69qb3t4eUQKuVK0F9xfsiShTxs=,tag:sgBcK218HZ4A7BNCkLsD5A==,type:str]
    MATRIX_C_DEVICE_ID: ENC[AES256_GCM,data:uuU2UyPClHpPmj4=,iv:+MQ9inFaPLMU7081phCcrJpk3uZPN2AXfAj0VdAOdUk=,tag:hvJcEJ/kcYDZWUYXJd1ldg==,type:str]
    MATRIX_C_RECOVERY_KEY: ENC[AES256_GCM,data:KdPIiyutcGMCoBqmieLf1/vc1CvnHzduD0EhmXlD,iv:4U0aPf6t1pAEubhlPvu1MV9zBpuXE8kpmjZH8Odz0OA=,tag:7ageyRJk9pZdvThP6g17MQ==,type:str]
    MATRIX_D_ACCESS_TOKEN: ENC[AES256_GCM,data:N4llPbU49mqx6TPL3P0/61wt+MQLnIWTo8EhnrYpoigRXCiMbKkRT4k=,iv:BSj1JwZfdZTCUantlwEPEes/ibL6HE0kBiKQzqO94bE=,tag:OSj7+VZwHux349+OWQU9Qg==,type:str]
    MATRIX_D_DEVICE_ID: ENC[AES256_GCM,data:0qQM10OZNlidUXQ=,iv:NgNGG2n1xbT5OqcTJSFDcT0+WglqWf/NpTmR95vZEeg=,tag:a4RoYKH7JTHgWlP21sopvw==,type:str]
    MATRIX_D_RECOVERY_KEY: ENC[AES256_GCM,data:IzY2orBll5GggwbQvYoe9wQQG/a1c55p9E6J7yhS,iv:kvjsTc26CN9C2gJOXgBcRLGeT3LqkwglKySDe2Fj+Ik=,tag:WDj9YDGoSE2Fbz2n864jwg==,type:str]
    MATRIX_L_ACCESS_TOKEN: ENC[AES256_GCM,data:ki+PyR9wrQB70pU79DliDOO9YciRI2yAl4Yjhj2yWUorZzdsYr+Qfjo=,iv:Q61tnJLNRF5gTghT1akqnE7I2aRr6T6/u6sBQz5xsrs=,tag:O4YhraVsYCpnFKN3A+MAgw==,type:str]
    MATRIX_L_DEVICE_ID: ENC[AES256_GCM,data:yHVZnwk+IpgLQrrXmH8=,iv:dgc+Q2X0m+Xgj4Vhk/cJp8srUkvMpeD8s9Zau8T1YL8=,tag:nVVMKsaViQgr6BKiN3iFMQ==,type:str]
    MATRIX_L_RECOVERY_KEY: ENC[AES256_GCM,data:lX0OXbpJ5hqmtrFtuqxGWknH+yk11wYF/EH7Vliqazsd,iv:vzk4fYVVuwKFLeOiOqqLIm74e576LptJLd4DQijD7Oc=,tag:VLlZKYV/BlFuk+nR+ibLNg==,type:str]
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:0Vcf9Sxggway6qZjUWpfezf1A/4x1wHXI3k6IYs0mD6TWQ==,iv:vjSrbI78F1Sqmfutkr9cjR2wdSvo6BK4PVrJARzbiLU=,tag:v6lrJE4PbSINVybCkYYRQg==,type:str]
    MATRIX_M_ACCESS_TOKEN: ENC[AES256_GCM,data:yod7cfb+zEbB5+BE7mzO96sA4hf5Z26Yngd2xV23U26p4n9R1Mqhieg=,iv:F7gKqqhiYJValFmvef/jJmRFMIuRLYEZ9t2lgvqI2To=,tag:hQaBY1VNvH6EHoG5gX5ZXA==,type:str]
    MATRIX_M_DEVICE_ID: ENC[AES256_GCM,data:Sn0metNoGn/r2ICrYQ==,iv:fI8RQVeA8rURxiMoMXmm7Znx2bv7BgUIJpnYSQLs4Q4=,tag:hqQJF9HJ3xln5JY4hr3Nyg==,type:str]
    MATRIX_M_RECOVERY_KEY: ""
    HINDSIGHT_M_API_KEY: ENC[AES256_GCM,data:xOWlPSsKScWw3chJIGcxH/k5+vHK2xUqGouXFthxfHBLUjxRKig8hQe5TFoOqniIJxKq4B9nRNNdWx5MjJ6zZA==,iv:fRik/BFZYXBS/E/kfAGKoRk2zDScnITPN0ZNIu/vT9w=,tag:X+fGEmy8dQ/UlbNZUrYU+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcUpHYkdFZFRUakUvYjZQ
            QitGTG5yWW1EbFNUUFNxQmJoQnVXdjhtUUZ3ClEzeldqdEJBUWlkSFI2Y2VOeUpK
            SlZubmVXL1NsYW1JNUFOdnVDU1pRWGsKLS0tIEtEL3pYZ2NUdWRnWnBKOWFYYTZi
            bDlhUXgrdTcyV2YyMGhON1Z4OVQ0WW8KwyMy7B6qXCXTa5G7LEy/Q5/o+mUwhoSQ
            k5Qo27WmA0rtz1D4wFxB4K2tT15uD1mQXwws4NRqIWN87teFNS6qJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TituN0hPZzRyN0RkUHdD
            b2d5Yk0xcGtzLzlkUm5YREFKVTE5djV5VEVzClpHWjE0QU11T2N2Z2Nob3M5ckhC
            QlR4ZG1HTm1nQ1Z1SjkzTmNwUk4rdTQKLS0tIFpkRThuYWRQcmo0QnpzbHlOYkI1
            UHZRdG1ZMGJJcllpeFN5d1BMM1krbzAKhAQu0t0q2Aaaxvj5ASq84l9CKujYZfz2
            76eXIdemANVz7zAkzt/tqYITw0T6Fo7Ful3uRXyygsPh0Xqd5yrk9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYzJXbkVGM3E5Zkg5a1Zo
            UWJGM2ZVZXR3YmszSEF3d0FJRlZrREVNbkdZCnMxVnR6K3BRSkZWR2hnRXdkaWZN
            S1FMQjdLdkxMajE3Zkt1cHptN1JUQWMKLS0tIDNHYjYvUWFQcnp0aTRkeCtNNVBE
            aVFoU3BXOWhkdEkyUkF3clpyY3FjZjAKZGzzO3lUI1ET9RmNPX0DPE5AQGYrEN8K
            37ybdJm7yKm92/4GlPDE43/EDIdxSTS2xpHa4+gMKKwnlyn+YBgkig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-22T11:51:59Z"
    mac: ENC[AES256_GCM,data:55esb+uSeo4Cr2/VMqrZjBzMzks16HrQA/I/xi9VxQV6jYXMg+gzSrAnNjYUF3Ky0B1oyOeLpIAGfP/GFIo5QI9z9lIGs2DTmlp1WoHpIdnDfBgceqhbrOydHNW0liKfCz2ZqHZwXZETK6OeCvzZz39UzztGGZ/TwDSmsu6v8vQ=,iv:HU1JRskfbD4HNEohYzLyLE4Hw0MTyZwjfdIlAQN/qDw=,tag:hIOMUzSLYDjmzhIpgZK0Cg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
