apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - cert-manager
  - storage/tns-csi
  - observability
  - security
  - netbird
  - crowdsec
  - tetragon
  - k8sgpt
  - backup
  - cnpg-operator
  - valkey-operator
