apiVersion: ENC[AES256_GCM,data:n6E=,iv:38XIpemjuP2RZAnY2NRRrry651sVkLEgNwnIPNExgaA=,tag:iYqaEF0sxiZB89+1GCJWGQ==,type:str]
kind: ENC[AES256_GCM,data:NtQ/ydP4,iv:sDzm+ne/p9EHNzW1LPpX3XFcIDvom5bj3DbP2/vy8Ig=,tag:ufViafsvIff1eLUtCZ0d5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oV7XHKae2kbrkbd1J96m1q0NRitOwaVKDOWKfYLd,iv:CUXg5KX+UUOgpOI5cqpYiawNqZQkx1aYKyR5MbSkFRU=,tag:tQDYbWrN2NQjPp+6aC7Vhw==,type:str]
    namespace: ENC[AES256_GCM,data:RSM/TuomImy2,iv:Do0W5A++jg4NfGHVL6iyaL1qroAWck5kpxB9ULbGlco=,tag:RElR+H46xkQk1KtC+BmvCQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:IX6TYCYRRjsf,iv:l0aVbE4qYgezkl8bdfyAonC0HZ83jIbjTiYXH6slBA8=,tag:MR3CjBE8OSePXOn4Yfmrrw==,type:str]
    password: ENC[AES256_GCM,data:SVhLfhYJtXzxytOMhtaGq3gykCkuHV6UBIcrFS6Nkxx/wAtEl09pX59q/AGXDGk4,iv:XZHwwM1EFtiJfTuAQIUrZSXxYH9pas2qa+nRcBQRuKY=,tag:LifV4QJSXCVEK+PQfQWlmg==,type:str]
    database: ENC[AES256_GCM,data:46P/6jSVsfQ0,iv:1tOIHvWaJUO1sQlWr+QwhsAfb0WrRVBgcsx4O6hjFmI=,tag:E7hMUUGqaFzMildLV0zkeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOXJ6R3kvcnlYVlZ3aWls
            MEVxaTRLUVI2UXJhUU14d1Nockt4ZFFIeVZVCnVodWp1WDZoZEE4SmxzQlR3VTJw
            cTJYbXdXY3ExKzNDMFRoU1J3dCtOTGcKLS0tIGdNc2t4QnVPWTIwSkpVN0JmNnJq
            Y0N3L090TG1nV2NiSHU2NzZJOWI1SnMKSlHOkJHhQbvKJ1AuSduXoTQHqY06Gqj0
            5TfG7nn5oPpX4ITFSlKmSvVCVGDwahgpPNmk9Uuj+a91ETXZ3SLkqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU2hBazZZYzRjRUN0WUNV
            TmZkbG1qZytwT0lWT2N1VjUrUHZoVzlrTWpFCjJKYk9uT3VGNU5hYUVBdHBXcisv
            dUI3eXpqWDBMSjJVcjJORERXTThxSHMKLS0tIEV5MTVNMWtDY0dpOE9EL1VtTDF4
            NGpqZnpTM0lpMGo1QnFiNjA3blJmVWcK6yV2SJJmw6nQ7XbT9qZitTK7luXTMLI0
            OQqJYYsIvf9Xbs/OSwqFHa3V+gVBn/DgDrbhDMjA1HsSYEt/Az1KQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTGFNWHJFNllPMWkwNkJm
            MXJNRzBrQ2MwRDdtL0hmbVFmRThLcndYcGpRCnhOYXJ2cFlXZGREcHdyaFhnMUI4
            OUZraWxJOFpuZklNcTg2OVNsQUE0L1UKLS0tIE5DNElnUndBSWtXWjBjS0dpNjhn
            YUtEenF4SXI5TnNzcWtVR1FJT2J1cE0KaQdrUlf2N9eIqLWmBCRuKByvPNG7QvRz
            uisrUomvesg3FZk4oKp/wmvzfNvCEKFhwvgPskMUIW2gqVbHA1FM0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-13T08:13:41Z"
    mac: ENC[AES256_GCM,data:hVV+hEM8tfIzyZjM1yeOy+6xQwfSFXbxfgINdvWXuxwYM3vZPHEHrpxoebOw8dwZLYsMfDcyZLeSHGZKBO8yYw2BRzpdJPciC5t4f9mKfOrUyZeLPjKtSMDmOdTl+XvK3IKnmLVCPlRBkoUrHk7YJvi6AE8qmKDPJDi45G1n9Iw=,iv:Fe3DfXptDeiTmW5hDvZmFGryAbeB0sp36HbPzvoVmg4=,tag:d/bMYC0wSwmrwjf3WAacWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
