apiVersion: ENC[AES256_GCM,data:R5w=,iv:dXj7p884hV5t+I6VwYOg5yk0vbqMGqTB8l+mHG70jjc=,tag:0qh2523meFUQ1yFLLHTHxA==,type:str]
kind: ENC[AES256_GCM,data:GzffruJx,iv:hUvGfJh6lN/w75XE0c49+I6M3BfLX+JwAcAlfSAhsLI=,tag:ckJzkdS/pfFkbvJ3UrQ3Bg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IKWK0LoDyLrK66mCsA==,iv:IyAKTRwvEUfrFJDL6u+ztO1XbH0drF79wVCcJvkZs4c=,tag:dIgXuWJuyZ6DZ+hCZCDImQ==,type:str]
    namespace: ENC[AES256_GCM,data:dolfD00b5D+c,iv:vQ1pJzmOojPc7Ad92Hmr45zRRF8naRhal2iesWei2QQ=,tag:0BLB0j330uZgfGP/K5RHkA==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:yMCkb01phUc8wH0BRrpVdgQOuk70CcCPH5Gq9Jlt6l+66wVTeoyWWHHS4xsJvqzH,iv:0UvWoLNn82JlFHOpl95M254QpgaMJZAZl1YMSFY0sfU=,tag:FC5egL2wJd+NErqtuZEA+g==,type:str]
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:RHaz2FklXNHS/QY+KA7PBQj97sObMfO1UWvWru9/4tkpr5D3/H6Vhb0NcrH/mDJOiIu3ZCscyWChzRXiZzIOBjROgapj23N4AQ==,iv:4TWf3rxqrQF1161EzxC+0vJP1yAs/EbBLYkRCvbJw6U=,tag:nDFskuJ/p2pJcOzqcNxkEg==,type:str]
    HINDSIGHT_API_LLM_1_API_KEY: ENC[AES256_GCM,data:2/YwX7QMixSaIB+Ap7VukOeCXzo5Fo70www4hHxvHT4S1G/lYZ4X664e+bsU+CmeQ6ooo1QQgHIJOaa01vWqzcCNJ6CSDwyVGQ==,iv:Nj83CgBEsIoHiMw57+NlAgNYC6/rU7X+kKB5iUh8dWM=,tag:gBjWz1uu5FMcTYN4xveB/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvV1ZJWE9HNjN5SnpzL1E0
            ZENYR3VFcHJKNEdvcE1vZXNzSDFTa2xEMXpZCjQxTVRnZ095Z3lCNkJBQk04TmVo
            UU1jbEMvcXBQSFo5c1ZDN2t4MU5hdWMKLS0tIFl0TkMrR0d0STcwVVNsREl2QkVU
            dmtaSGJ3Z09lUHdWcnNhVVFiZVJGT2cKDWwr48I6/Vkmvsg5ogQr/7ee4njgmVXy
            LjkRIuWGqCng4PCFby/ljs4lfy67hX2tU8fS9fqsp+fcHKBhREIm0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWlNXNDF6eGh6SktCUC8z
            OEQreTlUbjVDSWV1Wm01c1pQaGtNVWF2MEZnCkE2OE92ZkNoVHpjVWFQNjBKQlMw
            eFN2bHU2S0hPaGtaVjh6dFFCNUQ5VE0KLS0tIHhJV0pZWW4vcXp0aVI1NS9ROXls
            T3hXVVlXM2dlOXB5NS9tWWNEMjVQVGsKnbnV7uolP8a/th+eK9Ohv6vvw2AkxuEl
            vmiR5UPX1PVOlfuBGuRhkzfL3zu55chCZzugzrlvdywodCg7Hyd8HQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNjJKRTQ1V2NUVWQraUpU
            dWNOejBmMTdmb3hINWRXWVFvSXNoV0VFZ1I0CkFHWkN5NHJmOVd2V2VzSHVkMjl2
            blg3SUdaaitudUg0N29ldjNBcWZIRkkKLS0tIHQ5djZVZlc2eEY0SkFESHJ0SEtp
            SEs2TVlVSUZCR0FSTk9tZzB5SWhSb2sKTpAV70ckR5T4eIdY7+7MGXL9/JISetQX
            uW4WF3DVI+LXITCRdx46LTkh4/782hLDipBtO3pR8/hrtyv/1RTpSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-13T08:48:33Z"
    mac: ENC[AES256_GCM,data:DshNCxufiom6f6EfRiUeVg+lo7sIoOwV8r3iYohMCrV+2WDbw9/TGW0Qcwcge7LXuUX3D2hAPi3XooHFDNHMx6KpsC+OPodLqLyublPGlJOm08oiuPvb/So/CUO2Uboo17JqG1cilLtAWENo3qZx6U6o7pXuM2NGPVAIIHm6Gr8=,iv:uiGpBmrVVqmVqa+wcsFwUqtC+EdHj1ZXmJDzBW9OvR4=,tag:c7O1jg03xswdLSxb0Sw/fg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
