apiVersion: ENC[AES256_GCM,data:rno=,iv:0nZ/rhRNrMOqlq50TnETiJIIl6IR10tSQ+ciQDFt3J4=,tag:QDEw6OrsJBfFrf4K8B3HnA==,type:str]
kind: ENC[AES256_GCM,data:JK2JYtJr,iv:dDGMHTYHrVHZw9yTOsGqkM0ewQy/UsVfAOxoXgqntRw=,tag:UQ22dMsdMYA+75Tri/HJWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hVEn9GPzvlSgBuM5lQ==,iv:NKe6HtnnGmLlFRhbj9PGHhlJUQ0kPqYWXx3QaS1VSl0=,tag:xUrPNyM26CvKbkovaDOHLQ==,type:str]
    namespace: ENC[AES256_GCM,data:9gUKAOHoHY1Z,iv:3hAeXpXB0Re+Gtdhx2bC8XA9TZgAk80NnkTBkLw4RLA=,tag:XkzVke0kNmIVDa9O1hHhsA==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:9SKVSawfvTcDN9EUpJhP2olYLNs9OFE+OVqjKE1I7zdLmYJRCeqNG9t5vvbmHudP,iv:NN0/hdwmfrsq0SJ6P/Ss872QMiZoNBJSEe98OcM4ZHk=,tag:dvZikWJVvD6uzaUJ1+z2lw==,type:str]
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:R3svKn9D8r8rFw==,iv:gKbFQV03o0h6naLn14iz+sRBMtvS9imuLq3XTz7v67A=,tag:lJpwnFbUEBR9Hnf8zFWwog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaTRIKzlNbzdnd0MzMnhS
            ZHVEaFFZbEpqcXJCWHBTZXpNaGxpS1V4cFhFCnRrUlRBQ2FVaTlBbm9WWHJlNE1l
            V2RSQTkwbDg1aFJjRkhKUStXU25oS1kKLS0tIHRTUm9sSlo2bHl5U3F4UW05a3la
            RCswZEQ0ZnI0RWJ2dlQ0bjVuSVZ4d00KjbBDStfZsbYvMxeWDpDP3Nq/z3uDCef4
            GPFJpINqFoUTNUpVMwVV0m4GYNrjoAlj6NhdyokgHyaPc/qI/QsiwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UUwxeDBYZldnb1RRcDdt
            Kzc5TnVUMms1RkF3OVVkYmNwYmlXTGJMQUZZCmtKYzB5VG9QWC9BOE9YRG41NSt3
            Um1YMmRMUWxYWnZDZ3AycUluRFhwM3cKLS0tIFlsVUtTeWN2QjBZdE8ydFpCVng4
            aS9rcjFmUlRKeHA1ZWRpL3M5UVZJcjgKnS0j0cq+cpf++RJF9YYpzoUQwz5Q7Rlz
            6BiVVtWI+zbA9WgxJB3lIbjQjvB4UHDsyOeW80c+wcOK+8UQQZKQFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bWFDM3I5cXZ0b3hPK1Vy
            Q0NDN1RRSEVZUnlWN1BYSE1QMUxySEFyMEVrCnpWRUk0TkUrUFB3b2Z1WUpoWUpn
            TWxhakY0ejRGMU83MHBWeXhpeDJJL2cKLS0tIHZYM2FlRnZyM2Z1UHgwbCtlWHNj
            d0tUZWxVbVhzL2FqMnVXNGpXUlVyWjgKDyEIFB8uLjlNY28AqGL+8zCrhgDJVSq/
            excln81iosvzyfxJw4iT+Ef49c1Xa/PxzS66XBt7ZI3SMZCA2MRIpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-13T08:13:41Z"
    mac: ENC[AES256_GCM,data:6kFJf4VL+T5PkFdhuh6eBnNIiLru+Aqt75PMlrQayVnJRo2Cyapz0xXZ2ZMRnkgdpDKBIbYYx0GnTCW3xJgfW50ZCMrXTu/k9W1hVKkoyDDYvMhsfdp5eaFr5sSz0c8HJyJoCSk+r3vqyBfah8w6PsOfdKJw/nzQlEmljOyGzY0=,iv:cWauJYsuRqC5Umz8sHqeWHdCY8Qx8HYvGjROnfhHQok=,tag:R4+ewJssnKxEQyl0daiPKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
