apiVersion: ENC[AES256_GCM,data:iqg=,iv:C7cFOjxSadRbj8iKoPEx1viOE62JCZjIDMmnO7Iugow=,tag:e7+ViMck20mF2BdSuLtF1w==,type:str]
kind: ENC[AES256_GCM,data:1iqwloXe,iv:mCR2QeYrJ7xHmHtQ5o/AY64Eehnk7/ci2CvYcYkHuiw=,tag:CgHW/BRIE3U7QcKgy5vTUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+waRGf00hsmn1ytoPjYsjwmxjdmwgGuu,iv:wGN9dM3NOcKPpLELBjjUu0X8RyE5H57uUX0625knV+Q=,tag:NTWe0MFYKk4cHJUEj8Nurg==,type:str]
    namespace: ENC[AES256_GCM,data:hbP5NF7tbCA=,iv:FHHOTo2/kS8B4K9rsXM7Gf3La9KxOz4zrSFzgk+DbyQ=,tag:7QTr8hD8+VhDOWWrecyT1Q==,type:str]
type: ENC[AES256_GCM,data:WB1b5kg0,iv:7NG0Y5tgXyMCfErk3llIRoaf7ZmEzpWm+xFud7gnNz4=,tag:AXgYoJCD6jHCXpG4+lbHww==,type:str]
stringData:
    #ENC[AES256_GCM,data:1L5qUK+pZkGYUv09B7EQZk2H0ipJ2Hpp0AZkP/6vi+4yGuEn+GjyZKzNIFl0brFgi1tmtjyEvKcNhE6EGUyb6TP79sjDquYxH7ovtAU=,iv:QkLMITLPF3Twiw1vpGtusJjjpLx4x0bHoxgKifwLmyg=,tag:Dp+yS1YDjvQcu2y44tJ6jQ==,type:comment]
    #ENC[AES256_GCM,data:QZDGOofhT4VP0+MolauKHJET3Xue3usnD7Bl7ocNvGmSm/gZa8GuQb1BOXpL8RcUVMTf5qgboZqv+SmhK4O7yg==,iv:6WPIHicRul868Nr4InIn+NNRYHidiL7t4+3Oai77juw=,tag:iRh9Lk8ntOqQXD5UJy2vWA==,type:comment]
    root-user: ENC[AES256_GCM,data:wEJeVkVNHuXcTlkw+14MVTK/GeeWx7ZbsA==,iv:2j4CbB83OgT0tO5ggsCEPrhdhY0PBQxTaKgdxtno/+E=,tag:NGeJQE2K4cIJKjESC52ckA==,type:str]
    root-password: ENC[AES256_GCM,data:IFrFtgFhyCJnfAKYvBKtuG9HnK23xQNGtQ1ypig=,iv:N1vXifA41OJdh6u2W0UphajqgVYwUTxFLiZXXAXv2aw=,tag:f6T5pZVCLkZm6BLsUkgQGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdHdCV2J3TGpxR0hFMVFk
            NzlpV2RNY2VnN2hXMmNGTXc2L1hNeUttWlJFCkxkc2FScWlOMGwyVkJDQ0tPQkZY
            U2FxeUhEaXMvaFM4UmVndmVHT1BZZncKLS0tIHRhRFVxdXZhQk9JRTNEaHFUMk11
            cWZiYXNkTEVJbEJDUXVQbTdkQ1JlWmcKERCGLF426rxriqxFEQJcIR30tIN/kLiy
            YHYeKSnkkHxGzPHViQdivGutyaxBqZkGBz4rDKb4S5oI9llLNXwfDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-02T15:44:24Z"
    mac: ENC[AES256_GCM,data:F20TSfP3RctUUYLx0TnmhaoGfIotZtU/pU4d3UKnyIhaiEmirzb7gEA680OlbsEPj6nw7jbMnRpaKlQQAfIu0BVSGxCfTa29pV81R10uLgipWlibucjdPjPyHfkRHeGDKBWv4op3rf8pOxmmQbTu/HczNEhNYw4N22b+K9m2R+4=,iv:U9xqpPVBpiZhXLVGn9wy6WMmvCPxltIwO6bc9I4nfhM=,tag:3+HuWr1jIyKSpN3CI1mwbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
