apiVersion: ENC[AES256_GCM,data:9Vs=,iv:227zAMTwJ3Lm2mGqpJC9DDc3dn4JuCWjV05YyNd/QqE=,tag:aL+OD6leFbIMnmkewuKFig==,type:str]
kind: ENC[AES256_GCM,data:7JSzyJTd,iv:xzGltAHekoNcm905jpiNl5KDbW+GwNthjA3UY4z/VNI=,tag:rovavvplgbyvb/SGc92moA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JIrs6fVLiglm5EXuXKqeAMrNUuWVOn0=,iv:4F+vo8F2l1aKYwX7Zbd+BksJJMokP0lNVY3SkkZXVQA=,tag:vGO69YXXsFlfdqCvPJAF/w==,type:str]
    namespace: ENC[AES256_GCM,data:UC3mOuOJyuk=,iv:MjSHb8xK7bmrCq9RNdjRafkhijban1Vlx15gnE/Yb10=,tag:ScXliAdbK24mpNv2ruljYQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:dHFZGdGuJ8g=,iv:re3mMxTCmISIPuuSo+ih00voWZ9HgRMC671fMu0ztOY=,tag:bcX8vhL8JGwrzgoAI/Kakg==,type:str]
    password: ENC[AES256_GCM,data:ja2sjya9HdvcOo+C+/LXO6T7LziVxpRRneu4AkU=,iv:Oxylo53dJtLsFP+mq0sD+4VlqF3s2oLNUrvVK6C8zMo=,tag:+a+M40bkeuX5U4YSIrZqAA==,type:str]
    policies: ENC[AES256_GCM,data:va8bvOiOUrL5RBBPPPxD,iv:ev6Xy4EsYIMMYyCUHLy9EGnL3mHgjty+8XiBxzT5lLE=,tag:+bMTDhCGIWH69AHZaQQBzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U0ticGlJNWRvaTJ3eHdB
            akdQaUdYZCs2Zmo1eCt3Q1YwZG94d3JrRmtzCnZEc1RoOXFwOHUzL0ZCMytPV29N
            MnVYZU4xd2hUOFM0RkdVLzNrYWdGZ1kKLS0tIFVtR1VRMjNrZzhMQzBmN0NEc1Jw
            eVBsc3QvSGRwUy8yN2VRQU9RTkprMDgKtKDpCohSVkXPK4F/xbRj/rgYTDOu6izC
            O5F/mKmLk+tKM5GzDpDsQfZ9uMU5DC4ORLAp0840y3pqsEEb0TcQ6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-02T11:35:23Z"
    mac: ENC[AES256_GCM,data:P0TTcZMaYZM1oKeKdvjpfkbOoyt75P4BJWDo7NZYmVarZkJkHMMcJPhL571tfO+whTMWRryYT+7bvKuolMsC+74zv5PRh7sL5kxmg1Yg6OPpUxGK8XHuyNa3zdPRKhkizsWPA+yNsnFSCpjfsBE2PvHOvub5h+YywlWpxyY1A9g=,iv:lGorZx5fz0Kxu3qKY4bjY5fTbPVXH9MLxha6tGZ//o8=,tag:PJHgqvoc1Awjzk8cRdR6tQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
