#ENC[AES256_GCM,data:Lt8EgQj0DC1VVqa9WzpAgNxgw8/5iHRmBxSK+EsgXtQe4uiR33EFhCESGZa+vGUqZYfU4hi6+MpM5aviPk08aufPKgjM9oipcw2MlmCJGA==,iv:knrUkecLJdLA8gjq4ITFfqIMiKnvJdkRDhz2FALaCwY=,tag:wsoLuHDiF4HZ7mTLeNyuwA==,type:comment]
#ENC[AES256_GCM,data:HjZmia5StMQM4Cy6GQZDa6iz60dEEH5P70QoowI9X7o5G36DcG95cmi1U8PmGBMUlPkheeOnzHsKPKM8rCM=,iv:E8tBQ3NbsxbtMlc2O3Y6m+fbkOW3DRTBoX3gP6bbS5s=,tag:5633ae+8kA9ZxNN5SGQyRw==,type:comment]
#ENC[AES256_GCM,data:Vxo5uclZ0ZSmYduW9fzELw313Vj18tGiKb+0AhwobYIufdtjkZ48I5Vhx78imw0x6T1OqBbQ/Bw=,iv:QEra698EFPUpW0igIGzKLzEufdf6XBXJLYX9M6sNjpo=,tag:yRK3k6AEHCoVHudS4B/CEg==,type:comment]
#ENC[AES256_GCM,data:VfaFpGJPY6HD7OQzUJyOVRuFzXHNAIzkZZYTsRJACA==,iv:58mSdcdJK8edao8b3bJpKda4vrw++HdYJmy8e0sr+Go=,tag:k34LY5q0O87iDjOxeyleWw==,type:comment]
#ENC[AES256_GCM,data:FHgBeXkZWebc5/5z5A0L55+J1KDf8/FNjFBBp4ahz7fuiZvmW70mX/ZR71mGlvt9bcczHJcVaWxICkt+mZ/FE1m6Ot2WJ/0kflAvJjjc6j51Kghel/SkJ+c=,iv:fKoOwoqSAbGibxZE4L/YWqFi16isrKJO+4UBM5YAAMw=,tag:Z4qtOuZnSB31WZcdqT3kiQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:Cnw=,iv:W0Xeg7ZC+y/RI2oMGoHmtKQ2Av7LeUTP4BUdvm6X/Xg=,tag:IS3j8MCU2eMQEeB0sIuM0Q==,type:str]
kind: ENC[AES256_GCM,data:L69jonEB,iv:Hrz4+QjD5IiOqXzRb6GWtBJNFqT/M6BA/yGJR3MiIbw=,tag:+lWmsM9X39flXCvKndOu3g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:U0IuWyRWraj2MkIcmaT+tKo=,iv:JbdRrODejcBk1Oq+U0FIbV3t2XFa5EK29F5pvfnch/g=,tag:OR9vv+rjnFvJl1ETV7ZMpQ==,type:str]
    namespace: ENC[AES256_GCM,data:rQ7b1u8r9g==,iv:nFHkYjcF8Zuys3UT7j+i6GMgXdMLxRzAQLk97o8cDXA=,tag:rbevCNNH7OSNyjq+9ndlXQ==,type:str]
stringData:
    api-token: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeEIyMVVNV09DUE1RRjZC
            UEtObFFjZnpuSnpNalYvbkx2MkpFNSsrS0ZnCnozLzBmbndISXBWODl4dHpsLzJW
            bSt6RzVsWTZrOTRRL0FvTFp6cnVuQkEKLS0tIGRrR3hqOXJVbytaVHpFSU90cFZs
            QzFrRllSajFBQjdDSlhnTlp5anpOa3MKm/7iCicHkZXG2I9ROnBQg59JrR+Bh843
            XEkjw6XGDC5eVA78SkhLtDEefWLu1HxvgcoAB2gcqk3yk06utNN8DA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUDdiQnlzc0EyZ3JlNWty
            QUxES0M5bS9CZlU1WVZpN3lMNUVDTmtvNHdFCkNRaTZ6SldIemZtcXppT3dnK2VJ
            OFhPVE5vM1JYVFJYMERIQWsxd25hcU0KLS0tIHBtSzZaNWszQmpuc2tCT2RQaCtJ
            WWkzd1o4Yzd3dGI3dTNwZFhNM3oxNlkKKoaqT2lToMXxO9avaFNUmVnusS72E1+y
            u9kE5wMVLQWFjZItU2uCXt6BBmcCJQkjBto2p+/RpFuuyL7L34tHgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQTIyeHFoeUErWnBuN3pR
            UWttZDFiaUt5cm96aFdqb2F2dzU3UCsyWnhJCnIrdU5XY1J2OXh5SWpKQ3VFT0s4
            OEJSUGFiWlMzL0JiM1QwdjhDOC82ZXcKLS0tIFRvYi9pUG1JWStTaWdEc2swR2xW
            Z2NVbmtLYXZCY0U1Mjc3TUdrUXV5ZmMK67x6ZOo09tY9hAdstwOzFtqIq6QQeJeF
            ZK6bh0j8Bb7EG2QiZtqijI9dix2XJw9lqERJIaULF+G3QW8biMefxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f6cd8atfuvhxmjugw5pquk45tszqxlh557sg8k9dsufzc9kgmpqshjm9pz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbC95alBrV0xLTUZ0N0ZJ
            Mm1TaUVTVDhZcE5LSkdQaUQyZ2R4aWc3eDBFCk5uMHJVRHRIMkpuNXdySjBIZG1H
            M1R3bk9vNjVJMEsrbkc5dUxMei8xbDgKLS0tIG0vNWEyNXZqTEJBVFJZNzg2TFlx
            dnNCU2pycVdTL3o0TDBGc1NPTWhGQ3cKPdOYFOuh3lYwbapzDni7ZODDOQEkZ9QQ
            KGMzUm++gWj1LofZPzMEabG2Thbo7ndTCk/ggkfz8t+0ewrwXM6nTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCK1RBNjFzMnBZU0JwUE5l
            eFkwL0xDNWNFenhKT0xlb0JkQWoyaEd0TDFNCk9HYmZBb0xJeklJRERKcHdOY3Rm
            aWlVOWZnazVWblpjUUNPZ3BxcDVaMW8KLS0tIE8vVVYrZkR5OU5pZFUreWk3Nzgv
            clBva21iSUJUU3YzMVpQVUcwSjZ3TncKJJDIsgz/8AAwz+gSe3iLI/nBQ43UxGdU
            3p6LqDd86OiwxJCHpYlN1waiTTsECcvFag4G+ZCIEyOOgheIymNDyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lk8hyd9mducrxtn04vk9u9x827ccd8w0l5qu8aru4wt56vhf3vaqjem4x6
    lastmodified: "2026-09-07T12:06:41Z"
    mac: ENC[AES256_GCM,data:Bzr3C9+WcHqiMRYrSMgwPGtq9XtDGuQ1UnnXhdgQkoQJ9L0Q3xo4TiW1NJeZiHgZCVRgyfnf7d3n4IJSdiF8vpdU3pCx8X/7bnOe3Occ/QJmJPdSDKaemayGqN5jSVcNwtPhMwc88oVwQc/HUgUbx13X1iHpJTieuLmzs+1A5lg=,iv:BrZAYb6klHaR9EdAw9KOJUuUBLFP2cQCTv4m8faHhsg=,tag:8Hw4ky4nnBf6pERbTwgL1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
