#ENC[AES256_GCM,data:hdZXsEP+t2NNH3XU3JcrRRmwqmh2uiBh03jcnDZEV6nGzTx23wiVRVRiR+kMCoipvz1eNnAJ7eqVSjH6VIFsRQ==,iv:AtigZhh4KVidJWhNS0hdUuhIHERlpa1F0zL2B/HKpBk=,tag:e6zik7AQqGz8JZz6eVjx4Q==,type:comment]
#ENC[AES256_GCM,data:TsbtvBJf4YgxNXHEZPee6+uzSJNetiQQ4cQsArfwfc6OBx6oJFmje1JfzcK9xIyQd+w5tBCtMoEFwLPHItkBqHdyAN6x3BiSAuY=,iv:sQJMtSaW6p6AIVgcqy6PRCk6/hQhGWzxfaDJy0fsXZE=,tag:Y26aXo/e4ku1U3melo0yqA==,type:comment]
#ENC[AES256_GCM,data:YHHufUAqCIL+3k4rffwA0LMzQvf1tuuU9qSTvie2a0vUBeZKPH5DMCu7cpFvku0P2woLkLmI+mdojjV6HhartnmwV6Lxq0+OgQ==,iv:MpHckzvsWaylpgD07+wIgRIcQdHNY7bDMe0ajFyzd/g=,tag:q1rUnDfcVWWFlY5q/iM+OQ==,type:comment]
#ENC[AES256_GCM,data:3Klh/PjC1xLpwAmCZvqnB5aiHV4+lw9ZYKsDtnCQKRNOTH3V4RYdVvaTpZ5GPtEky7Id49i+AOnFVn7uovS4OQ==,iv:K/sgf4/iShdner9LYBvp35h+NitTC6TT1506wuH+0Hw=,tag:VWuvo19BfLIkQ7/kTvXmxA==,type:comment]
#ENC[AES256_GCM,data:5H8tBwyAEg3LY8wImICxZw2QhVx1avHCF5/7/+ZUwyVfnsdErEsIxieFXK1Dl6zY3wDuoQGHsqhnYChJQtZrLkpSLnpplCh9fUGX,iv:5byy6UsFKzIHwllSfTFedP2j840jHm2B2MK/SIYQJ/I=,tag:MfLKV9F7zV7S+uDqI0KIxg==,type:comment]
#ENC[AES256_GCM,data:uOqCeN45YmZvBlJtgX93sglaCInFYFYuhm3UAJDvAhmOLtadvZ3qZndxaV7nSlj5sXd07rgA62NjnWIhqqc4F8g=,iv:Ur9raLIEjl1jaPmdzATCLMpBrw+ZDUhXeeZTkIA/+Mg=,tag:efNoal2hKBK9IkTi2CS/gg==,type:comment]
#ENC[AES256_GCM,data:w2bq8m7A+TFb0ieeHU4oyaFhbKvm+zOmEHA1Fir5t1G7swLnFm40NVa+u9IR1DSh1h3jT4Jpbmpf4KsE6wnt2dBylH+yKO8kGJIXrOvZFA==,iv:nsAPcUUoSnbbPpMRP5fgHwKBW27E6AFiLPsWajQcHsA=,tag:hi4q0J6CDY+3VPjcTmFiLw==,type:comment]
apiVersion: ENC[AES256_GCM,data:u9o=,iv:wlZEdmUKIpijQY4b4VSmaE+zVb3zz6xf1iF4wzWEhOE=,tag:YQyefWTSYAIqk/U0tDuGqA==,type:str]
kind: ENC[AES256_GCM,data:YGwmFUY1,iv:n21yIewJ8rOE77LVPI+eTXhH2gi5YMB5ayfIcrO/XtE=,tag:FVQl8fD8frvxoVv3+nACcg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QKt+echsQQ62ei7G+KjENpM=,iv:IEs1wUV/IQWdxwCTBbeRtGIOiXOYSYgXUNrK3bGOrSU=,tag:ebXB86Jwf8Tb7z90rK/+oQ==,type:str]
    namespace: ENC[AES256_GCM,data:PQYRdAAA4w==,iv:SmvzSKf/yPQ9xy7fZ8aDtpKMMh4ABDw3yq0gOPT0Jmc=,tag:1AVOjtRd6sT67BD9AgFwcA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:cz0Cjn47+iBXXoFKnVzKC9cd0t1d3YJ0gFLcjU6lxZ0Fks40oLL3ExOOv0QOA1vAAKec00526B5wJWoRl5vDVg==,iv:M8WSDqP1q5o7ZqXCtqaqygLsY4MImTnf0kv5DUjD9Bk=,tag:NT+Vt7OqIHpTyZHq0S8miA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdGpEY21VN1BLSy9uQ2R6
            UGVBZ2dnemx6Z1BDRTQxQkVIRXdUQVN6aFRVCmZTc1dXTDNjWitzMk5iQ1VLekcv
            UTN6VjliY0pOSHhQcEM1amhaOERMVVEKLS0tIEdjQmdZQnZrbnRqcEJ3S1FQZGhG
            bmNveCtkTndZZmJMcG1rVGh1L2dsbjgKGtLHNGSeKbYS+PE3+PjYBxstbuyTcJB1
            2z8t0/5SAxyT2i8wm0vdvCcWo2WN3IXEnnLDLn1+qcJtr3CpcgBn+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NEt2ZFRQbWhZVWlDV1U0
            WThVVmZIUEhlU3J5YXF3b0NaQ09tVkIyMm5jCjJ6bmVGeUcwbGZkZ3IwZStUMkU5
            UVV5VTFZVUdSbnRRMWtWUjB0Tm5CTUkKLS0tIGdYckJQcDJoUWhaUTR6Uk1BaEV6
            a3V4YzJJWDQ2N2x2TGFMMXZKMDBxejgKiMh3noPNHiBVsEFrqEt4QkK4aZjM1gcY
            LUWCh4lO+WxuYoSUtL0OKlTlbX2iw0l+VGw1GSd9zj/qoqAF5XkVIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQWhFWHd2MmNyMmN3ano4
            NlUvTzVNZmtiVlg4bWNrdGduTDdKbEI5b0IwCm1UYzFXVml0cWh0aFhVUHRRNE9n
            a2o3NjJMbTIxeU9KOFExOE9adGIzNXMKLS0tIE9FcHFTYkZPS1VYRVFpNHNRQXh2
            ZzdHMmpKdC9ydklUblJOYkN3ZWUzWEkK7E4VD+fTpmAh4IscMmLfQeSnLhcPW40w
            hgV9pO/CLmHqKawFgaflmsd2G2eQENzv/6f5ErEc6Y7C6OBpQFb+qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f6cd8atfuvhxmjugw5pquk45tszqxlh557sg8k9dsufzc9kgmpqshjm9pz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNUZYZlRzNW04cXV0MXk4
            dmpMb3lPZUxPSXk2eHZsWDZoRXI5YnNJSlY0Cnc4eDNPV0RiZVduUTZCdUhQSGxy
            N3QvanR3UmRRTmRkMWR2bGtYUVVxNWcKLS0tIFNydzFjZ2sycTc0MkNYVkhmYVZT
            UFFhRVdDN1FjQmhxWGZobHZWT21EQkkKHJT9u5tl15oH4lJoJ9LOJ0+orPuKNFAK
            YV+t7DLGXTITs0qdxrv9qbxjZr6Xupvf4/bOcG/7iSlyFGPZGfQiMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZTlwK2c5Y2cvQjB2MlZr
            b3VzeHlGN0k5Vkp0MUZobTN4M2F1UWJPbXh3Ck9DTG5ZMWR3SGlESXp1dGo4ek9T
            TFdqK3lRS2xvaUNaeklncFo5cTNhVnMKLS0tIGNQekl5RUNzTkRaQjdFWXVycVVh
            aUQxVy9VZXhDLzhZUUFoMFN5empLcVkK45dXPe6pTy+ZsLNKsDGT7bZIurgbYjMG
            5gczOQVd75FYEf/SgJfM7AV9SrZekhdW+jz16vGcQVl2TtyF8fr6iA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lk8hyd9mducrxtn04vk9u9x827ccd8w0l5qu8aru4wt56vhf3vaqjem4x6
    lastmodified: "2026-09-09T13:15:50Z"
    mac: ENC[AES256_GCM,data:2XIZlv4N++A+ub835gU7t//ZlPDRbUwXxlPTHA/fCPnUDXUrlmZgNtyYy4qpRQEC18/tdrleeh5UOwvB8nzZV5LjtCi0V7uzRbdeTpICzAb8ruxmwgr7EwHtWo5BVOMFXChj867eyWIHRL7nxYRKaZaHfpiAqFZBRtpnE1YW5Xc=,iv:upGAF1JJSv7u9XV+lQSOSEuYryd5H6LS37n1NF9MZ0E=,tag:2Q2kVlq5/fn4KgAqFuLGeA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
