#ENC[AES256_GCM,data:fJl9uBA4drc/Oua+yhdMkp073WELdWVxoQXhbsvluY53Szg1O2GksCc/zVTtN/DuDwx9zkJoBo/GGN2Td0IXMcbdCUN5E/Ygy8bYAsk=,iv:TbbBNeuOEsniqRvZXgJ38skG6h+mApsO2MAcX+joSfg=,tag:N5O8CgYxLQtYbBgNaccwtw==,type:comment]
#ENC[AES256_GCM,data:7eZ0Txyl194jI01cF8uecJXBDMa3FoeQsdqmkSv47wkKpXzC1qT7FeotQTWNgBoSkovS6VJVp5QFKezMXSC3b83ImZXnkDrEePe9eCes,iv:1Z4WZ19W4D1lI7+CXVkYWyARKFIBEs8mC0hoH5MMuqc=,tag:V2Z2R3/jZ//NczEBiA21ag==,type:comment]
#ENC[AES256_GCM,data:hiLFB7POnBaZL1DKtmcXevht9Ni0LrlrjyC+zpwUAVwCbpfrCCMVBcBc9HaWaI1VOho0EhtWk28krYaxaLHYdmw2pQjrXg==,iv:luZ2GYEc9tPmi51Y6g2EExKGc2QsP2ql4SONVxj+stY=,tag:IrLBmROAJV/c8n5j8mxBjg==,type:comment]
apiVersion: ENC[AES256_GCM,data:55g=,iv:Aa/d3tyyaQwT7vs3xOe2LoX3gaToCP7Q+G+K+tNjAds=,tag:TnT5WkGc1kZ/GqE61JxI4w==,type:str]
kind: ENC[AES256_GCM,data:nPpkm73H,iv:U4VEJFHvGtgYyFboVOAW9LAJku+/qR0oz3qnif0bTbY=,tag:FgDIjuPOyDhiXHj7/RVbvA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:c4huUUCL3CV3qagAg1o=,iv:WAqctjMoyKh0O4aVgXcfYgaa//3KgAwsnDMb6UTjCSQ=,tag:KsnV/jfiANOhoOOnfvtpIg==,type:str]
    namespace: ENC[AES256_GCM,data:6t5pVw==,iv:3g+sMS2Q99CEg9VEczZ1bHljUdd4iDVEZvU5OmaKd0Q=,tag:w4XPTTtHXvi3OQYrhQ0h+w==,type:str]
type: ENC[AES256_GCM,data:Ayzk3q/i,iv:i6XyOZk844ZWHSCbREl+nxviFKWyd+fIDBbcvXqAF0o=,tag:jlnZ3NWUix41A3dhvWsLmQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:WCHt2QDA8wzeoZCme9z/e3xVe9eqjjS9mpWoLJoo78Q=,iv:UQ9P+uLSOmR6pLbfZRgJ6dL83ZsUzP4CW1OINwrP8PE=,tag:4h2EKlmvluwtznh1AiWUZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNVpwOTluTzhDOVpZU3JQ
            M0ZMaTdqVEVNMWs5ak5hVGYzY1BVUlh2VmpvCktzTGowQnVsSkREdjZyRnpOYU5B
            a3dMQ3ExRk8ySHNSQUhWYzJmZzFEc28KLS0tIGtMQXc1WHpzcHZGUDhBbkFNOUJ5
            NzlTQXIvb2YySTdVbGdxY2VoRGQ1QXMK943Wf8Da5xYF9L5rfLsbigIzGgwr5wpe
            5gt5cSzPtbpx5C7ycdunqS9440DEQF8C94BIEeIyMu0UJxFzfDSxTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQnIya0w2d0p6VDROZWRS
            ZXFpd0VZT2JCSm11ai8zSHpXc2VJOWJjS0FvCkNQN05mUWVmcFVnN1BvMHlKckRw
            b0tIMTRiMnFLUmtBMmRIUTYrVGhEVzQKLS0tICtkc2VOeHpsbjA4QTJVRnZlMENR
            SzJLc1dYb3c3SjAxSGdJMFA4UDRQV1kKU5agnos1kpl+Cj2Z/RqW2X1G2X2/0JYb
            FK6+aH2j3SOnc80D7xD4Xslp/Ln/q6uAaMEzXCSCBK/DJ1B/DKnilw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-13T18:40:00Z"
    mac: ENC[AES256_GCM,data:z1WJekAhg2PlVLcCY5bh/pI9N+NanlhwezROdNLILWuV5JNERjIYFWl1ftGEaPr3bvXbcQ4wrHtUWw72CdWZ54/QvGhctUeChttd3txp5CT283D9enCVqPjz9nFvqkiTVJpHkOe6woVZwkMsKQpniw4x945BKd6g4D2JmTxCzRE=,iv:cqs+xOYy3hJmb7BHG86e3CfalFiu+XNqPcKIx9yUsAQ=,tag:vhCuz1XfeBjrU6juKI3NVw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
