apiVersion: ENC[AES256_GCM,data:nDY=,iv:6nDhSdYBTklMRqTViTzcLRzJbm5aJNW614hrGA71s5E=,tag:Mmok6bEiE1b8k6/nYvK8zQ==,type:str]
kind: ENC[AES256_GCM,data:ofIG2iIY,iv:q59KPYoI0eJswAvCuHxVhrSyMROaWbtzPeqBHq1s4w0=,tag:cLQO8M3TanNzJjxXXLi1tw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dHPL6Xgys5qu9YFftMlXj5zAMuE=,iv:xKc32pA+Q6I5GTCo1YUc1WF0kzOWEcHOQOo9EZOwhrU=,tag:Vblvf0WdbwNkyDnF2esOyA==,type:str]
    namespace: ENC[AES256_GCM,data:L806DhpYT083bQ==,iv:EhFOQ3OFF89cwMjKQ4xfWmYtt2X2kzsKcMXb0mQxlDY=,tag:JIJ9+Kp9LnO1PhGM9vKY5w==,type:str]
type: ENC[AES256_GCM,data:zUu4jSUf,iv:SzdewcX+c6UXsZ7kDCfNScIZIRpF+NCqkD3O4OLQzM0=,tag:l8ZbxmZshOs3EqZfr8iRmQ==,type:str]
stringData:
    pl: ENC[AES256_GCM,data:5YevMFprATo45yKcYVpa6JVMlwQHJtfaF6CytjITotAJCSLod0B/eFKIWSU=,iv:at23XyU3HTaYYzwZmCF24LeQhvRMB26Zi0k+NqXBG0k=,tag:JI3f8mn54ozVqOe4kvvb0g==,type:str]
    be: ENC[AES256_GCM,data:rv8P2ULK+X1b3VkIePSTGSUi9XNL88x2Tt6Jj8T4dkMBF10+n6c3zZ84zyo=,iv:AoTY2VP5Pj7D9FBIMJqj3XdUvNGhnJqGKKMi2FquCRM=,tag:4WdBJS6Girl+EqDfuiTd5w==,type:str]
    nl: ENC[AES256_GCM,data:qaUcqLc7pVH32NEQtzEbqOOfI8yOSHsPcJYUe78I5/ui4g/Heys0GjcVL34=,iv:Km7Ek3JiRz9eWVPpvXQhUyoV2JcDTEQVpFZrwCKsMbM=,tag:rlP9fobFfIdYW/Qezaqg8g==,type:str]
    de-fra: ENC[AES256_GCM,data:5dURwnNmmKjrNdM9HvyulwtEQZBLynV4+shSx4PNHbur8cejfsJhjQFTrh8=,iv:BWq5HB12uA/9bk/M2Vq5UX2EAuZFoZKZYJ19Kq82ZHU=,tag:70LU/f4vb7W8n5JrycBRqw==,type:str]
    de-ber: ENC[AES256_GCM,data:JZsOxBBO1FAfgN66JzMmHmPHKKf93BbQBf4HCK0K1cRVPPFbOpyyvyp9nw8=,iv:n1IoLZ+qvfaCwrQKb7IYPcxSjA206/EixIN8Nm9B+sI=,tag:cbfOeLftE4r/h2bzyIO66w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMVh3S3gwM1ZtUHdid2Vr
            emM1VVFiblk3WVNFcVYxWVVRRUd3SHFlMENrCi9oRDJqbld6K2lXMDgxV2JWYWRS
            d3MwQ2dIcTVpbC9FNVA5Wnd4RW9sTWcKLS0tIFlWaXh5MnVkZ0lMNFhRTWdob3U2
            ckVleUVZalpQTzdzK0kwdUs5OHlEYm8K7ZcPYpQnUvfQkC261+VaFGZMdTmQq9rI
            WYxYZfGR9zWssWhslK7yxcaztN9TiGGHL5TaqXyKUL9Eo312FMU1ZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NTcxNStEczB4a0ZBTThk
            NDN2OTZXQ05jTzBMTWlON081aDB1L2xYbGowCmdzMlZiSytTOEU0U2U3NndMR3dv
            N2hZS1FYMldvTU9rTDgrNkFFYnZoZTgKLS0tIDh6cHlvMEQ1c0ozakFLUHVYTDY3
            cm9oei96SVFzZXd3ZERJNFBGOU94Mm8KiTed73Q0nx6kWses7mbEI5BDPM5giFCv
            xCr0RXXy+ASyRhu48fDVQRQ1CGxJ3qqfRYzAjY+7R/8LhxP02oZbeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvak5VMHFLQnFsRC80NkpO
            ajAwZm9BVGlML1pJQnk0QjAzcVVuQ3lxaFdrCkRvSHlkVTJ4L04wdlpRalY0RUFz
            UUxWMjJXc3Vhc1NHMzl3WWRDZ0xYSm8KLS0tIFp5b3JyWis4Q2Fzczg1cjcwZ0lk
            UXhHMFZZbEg1MFJYNnFFZmFLMDc2b0EKIEhXcD1krieXCtqbDsyqHqSBFXP3uuWN
            1g5sZhraHW4CMp9X9FSYWjIYDnRTa7xRw3FhqD3WpFT8p2ZIAmiQSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-21T17:32:08Z"
    mac: ENC[AES256_GCM,data:oCu7hpYDTgLEsl13nmZ+QObTr7B04pt8YYovxi8XT3GQguiq171iH4SRDhlf0mq3aIByGydAHH82ly6IdHfhqxBxbI9ZjFf1QI0PIwcWjh4GJ0mNOV2ap3pmqM37hcSsjO6xve64DV1t0MxYYrXtF/O1y+pHBEbVC1h6SZ+8Bbk=,iv:pZQyZ0P0x7h9SUhX39T+fOBABZUD40L01qnvk/k/XFo=,tag:9ImtX8O24Q1Q3xKfTGd/eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
