apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
  - namespace.yaml
  - secret.sops.yaml
  - talos-secret.sops.yaml
  - helmrelease.yaml
  - talos-etcd-backup.yaml
