apiVersion: ENC[AES256_GCM,data:m88=,iv:vAA3PTOHtvG6QNLDaqBHbYth37e50hrjdVMZ14lj+6A=,tag:LHtuZQaXbVX/pAc8AqYQvA==,type:str]
kind: ENC[AES256_GCM,data:Ebl9oQVl,iv:yVCFVXgXCU6G1Rdgy/ojvFiXiaUTuhoUn7YAwciP740=,tag:gccQjiEGmlPzN2eba57MvQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:99qXS8Hm3nDYE/1Jdbm1,iv:rbxRCI3qzz5MSEN1WszEarll6aDtE5pdTVNf58f9cPk=,tag:BqM0yPl2QB+in4EsmbHouw==,type:str]
    namespace: ENC[AES256_GCM,data:FsyiWsCc,iv:Ltyo/hUcfoZbhgcd6ZELl02EJR5KRIMfXtnoZpw3aRY=,tag:j8QXFNhiQL7MY1MZ8Rn6ig==,type:str]
type: ENC[AES256_GCM,data:woR0S1SQ,iv:G0oloz6vE8boPZdnE7Fh5RfJah2CQVGlHF6YyqSQzjk=,tag:xTrf94Qk8i9Tas7DZqWSRQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:INwkXSdmK7YVDFkbjKcSK04EiCU1JbZRTHERupXS87NDOyORZ7y4AbmSQI9G0GicVnNyFZJ5I2FLv9ydOA+2WBEfgXqGG0LW,iv:nMzoQFW0UMrAbxbv4QisHDNXqtY5WmHewifs/Fhxp8A=,tag:99P3ljFKAAWIdW1uwWh9PA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TyORxe8SN8JAsxpEwPn7e7mqQj8=,iv:Yx5sXC0PNICcSK2X1lxfkZcv92Nm2fbjpv7mVksP3Ls=,tag:xePKjHGBD/Ega5c+VbYrQg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AX8jNNJ0Wn/N7Thjypa5ls/inAj6Gp0ZbbmazcwQJbeUXyKA7SpeMQ==,iv:h/Ku3yfVE/xHkSrXHzNXocKGzsMBGrCkg8NGuNY0K0E=,tag:OABbOgHecc4I3u+amtRiaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaGd3VjRrTXJKc2dhR3VK
            ZlVDa0JPRWhIQStEZ0dEV3A4ZmtXRmR2SkVrCjRiQ05ITkQ0QnluSmRNTEtFeTJp
            YUpsWmVjdWtiUlJqMnhRaS9QZEdrd0UKLS0tIFlFcFBaR2dYVzhLUUtxQkRxUzhu
            VHgwMkY5NmlyVlNCcXdhVEp0cTBFem8KjF0864ifqbrlnCqPpYi/WBow1H87b3kp
            GpvGmmyZ8bG+Sy1cYuDZzJQovaX75f5OUXFbygRsrO52Hece9zcRQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c2dCYkVPN3BHbWJLL0gx
            RHBwU1RaMjRHdFBTU1BYNUl2RVFVTXpIRW1JClJMYWZxQ0p0QWMzcW1VSHQ1ZlNG
            V1NMV1N0dXNFT2gwcmdPQWxYZHJWUW8KLS0tIDNVMi9UeEJZQ3l0aHpWd2ZjWmtI
            UkJkbW4weGc3eVJxSHZ4R01YYlNlb0EKfoVn3gjMmhUl+VlunfH7qUlPQAKMiTPc
            sTvh/NUvD89yQZzavznk9aLqjRcfGH+0rJUxODLxMBz+W9FKcDw30Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-03T08:10:23Z"
    mac: ENC[AES256_GCM,data:JzvBwBeBQXxivzRqX/IS0bngKU2E/Xm7EKhSbfKQQ8OwBDen4a1on8IgzW5xhMlNg9hTHmgiEq0kj8/UVt9+OkbOjiPgb29DRKrLjyOTHg5MGsBpUCE11Y1A8poa564gQBBRAPl9IpaPSf1zyrHVQ7fA8z2TXYRrBlgW/XXapjU=,iv:XQLPtafey17aguXMPKex3c4GQ2z4q/USWvh6O3Jewo8=,tag:bVw/fK9q3CkoF6ebb1yp0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
