apiVersion: ENC[AES256_GCM,data:KH0=,iv:jV9+wVh7jCFei83t+rLSCHONrdWVHnE/3MlmozxmoWQ=,tag:1sIpEB4FISJ2qg6yTX7Sfw==,type:str]
kind: ENC[AES256_GCM,data:Dh3wwn4A,iv:mfEjc8wQvgsBZ/4UvR1c4YjI9Srfuc4PpE54rLqw284=,tag:alEoCpjDLn2i8uEyNWQpnQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ccP0PgpkQDG+rcIyWCp8,iv:l5Javc0IxL3brj3SOqotCKq43kAhaxS7Z1uyR8huh0A=,tag:w4APjE6u2DV6HDmoGUGePA==,type:str]
    namespace: ENC[AES256_GCM,data:C2ZYbOdM,iv:1UFgb8r/GeXpp+f5Zz6q7sk/SKmEn1/uZPK7MXzGnFM=,tag:WS5zpW/bj3qoQesL6p4Cog==,type:str]
type: ENC[AES256_GCM,data:0RT0uRzU,iv:huWW3w6w0CQwoiKgXnAYucuBGmTGagcxQpqpfOkg6mg=,tag:mzytMp/qcWSR8eOp+TSrGA==,type:str]
stringData:
    #ENC[AES256_GCM,data:9sn1SjXQ6ph/dNPZU4bC/yhW/jzBTX4zTKXZNgzC4uaeqDMLpKFa6zipDZU8XsTHdyJSfT1+PRHthGcI0OPIKFgjCdoapI0wacR5Fg==,iv:K/kxeSHDgPjYK2ZUnA4IU1myR+P1Vq1ZjorGKKOi0Fg=,tag:sPLqQcRrEn0YQzpMLPX5XQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ysIFnN4bFsU=,iv:BDVBZ9NEQaIrI5cp22voY1jaX6PbLTukTfHGnbC9Prw=,tag:SEKNAhuelg/K9wc7BV6QRQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RE9n3h6+ZvA=,iv:NE+LDaUwKmkjKfbVVyvY5yFxjsDgA1T3xpuxlNyiIFg=,tag:3IiA/CrfWw7hwh6BdGy/wA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla1dNbG93UDFlRm41UWR6
            MDdMb0V4TDU3ZzE3YUpEZk9HK1VnbVhsVkJNClo0VUoyei8zRFhsSE8rUHBQOVFR
            STl1YWZOZ3JoODBjek9xMmdDK0ZtNkEKLS0tIHMvMmt0SXJFQ0hZUnJhQ09mT1NV
            Q1dPeGI4OFhaYWtkQmpWc0F1Mm43TmsKqVs6iw9U41kvO+h8zCgyfMHgnwFjl0u4
            KGsZOo4kbezg9dn9BuQcLlrBu2ALUxWNYcllB7PSREeOjN+b9cQNRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T08:00:15Z"
    mac: ENC[AES256_GCM,data:QkY10xSUl/Ztew4TjLvRX/X6fjTDiHGxbA484/sqK18TAKghBjCQT+DUjrDmAH5bGzvzzZTajiS99Iv1+k/+yTQhMP77RTEZX4opKFhdXr6H0/VdV5vfynENOm6aABh4qXGq5IQk/R4qPXuTl1lfi2DkPcbqdrQmPld2RDiNFxM=,iv:66aKQc3BR4EuPomecUTZIggR3nZTKRd6MG3RIMxdLzM=,tag:J9/h3IhAU01XfmpHS+kJUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
