apiVersion: ENC[AES256_GCM,data:P6g=,iv:qVSSWqd/e5S4/GLgh9mGcjKVsg0YA/PojMTvDes1dRU=,tag:E6MDUXxv359e40edi/1qew==,type:str]
kind: ENC[AES256_GCM,data:KuiDWin8,iv:NDRKx/nYtrUtuK7TGFQSOpgCqYcs5a3muYKf2QUFYas=,tag:WCtlHT5fVmoRN6PGwWh68g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6/D/SFBOiuwSRu0iM/Zy,iv:pFMhSlShHJ7UANikUDvvracls+FJPXgtxDnA4SG6f8U=,tag:8e9epGoNLkEadZ+3OrM3og==,type:str]
    namespace: ENC[AES256_GCM,data:kULmSeCE,iv:r7Ajye1yw1snevymnp6DVbDF5vGWiRYBqWRO4Pm7ocM=,tag:pxJb2Yki0J+UYIcc6OzrFA==,type:str]
type: ENC[AES256_GCM,data:cmIJC2BW,iv:41cKv/FmXid6lYkthbL2FrNzw9vo8GNOGVVhgX/x9Gg=,tag:r6a7g6QdlKSzxPVN9c7AWw==,type:str]
stringData:
    #ENC[AES256_GCM,data:7ekwQGwv4PZTRLa6p6tibdQea4VDgDkZrpetmksWHqOy/yXgecMTHieufriFN89o4iYNTVT15HEK8EylbV3qQg==,iv:9i1pAwBQV3IO28EUBCIiLcpoaMhLxwbM/6Xpl/UhCoU=,tag:9mfKpTzFdBiIpUrXXKFDPg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IKd1nShrvraidkZVMa2ErUby2LQ=,iv:xicYi/5UtQRJoMFyX41BafxxyvC2dGOSPXbaJiglr/M=,tag:3JkJUzpeIpSWUUH7zGfgkQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CQvkQi99BO/8bnuYz57EHvjfS6UdHz5Kd6CovFUmj3blfCABGIcI0Q==,iv:MnS2K7fq8Lo+o26afJjlXNPpaVJvTdXd1KQRG25JfCU=,tag:tRF5iXwq/Q4rqvKjW6VJeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYW9FV0c2SjRybHBIVUg5
            NkdmRVF6T3ljWHBtWDczVTlqbDBEanhnc2pBClZXSGplR1lsVnlyS1NyNlJldUQ2
            T1ZpZlc0M3lQUlRscFlKNXJFVk1YSjgKLS0tIE14cU1HZXN3QmU0c0RaRDAzT2k3
            RVgreEJEdVBFVkl4OUhaazd4dmhVTkUKRVkg75eZYqWqwAQ/9lsI+rROMwc4hoW0
            erAQAkjWpfjJGX2dBpS5L09uDevxb4QLuYpY53FIQl6qLZUGAkrHnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T06:21:57Z"
    mac: ENC[AES256_GCM,data:T5qOA9jNNATY+cA7BJL4JlloLF4L471xtIBYfFdYAj64faQcWlWjgPlXuxbzBiA8NmjOgpY5GCv43HKEGPVL1ambHA2xLQxWKWru1z2lgrEL7zP1zHoCEW3o+yEur2C03yuFI1T6+LV1cBvbI+qqrTFyMnFGF6BGOdc2ucIzS2o=,iv:EnYUwbqBqJjpyv+ZwJbYzJCovAkZt/MSmn9tUM/Nw98=,tag:i2vslwlOVuqriS6vT4QF2g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
