#ENC[AES256_GCM,data:DnSe3Agj8x7G1rpYoh7TUxzVbAQgCJXrrtI2KAfvyqjSQbZTjPGWk9pYCHwQVDEC6DGC0vyEah8=,iv:hdkVRukTlN3kn2G7WzWxPzTNMvSxw7tcCqIWqis+L8s=,tag:LtWnjLgHH4fhAbP29TzNUA==,type:comment]
#ENC[AES256_GCM,data:P+xSX0YxheVplNXXFtLpbt4izpvdTA8bYetgpbxNPJBNJxdf3CYLO6ELqRjr7r0O3KLq5Cd753Y7ZJJ4C6UsTSVQpZwCQ8NJqA==,iv:NGZvl0Wrb+U5WbO6H/3+0SoVikuI5JK+O2I87ezgE5M=,tag:y7UsjxNHxlX5XDhCZPOSMA==,type:comment]
apiVersion: ENC[AES256_GCM,data:04s=,iv:3ohAu0vN6ioAoznB9xL6xgaVDQKs4TFlyS3tIxm91AY=,tag:P+0o9c/JpvvOR75BaGR7bA==,type:str]
kind: ENC[AES256_GCM,data:xn/lrUnf,iv:K/SR9DIbZg9jwi5w1PiDIgPAC/2xV7blZ5nrU0Ueq+8=,tag:rjAL3v8hWJbN4ghb3o8q2w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yoCLzMlKbXofdj1GZnQVCRxaWMSOKesQUg==,iv:TmgnMQ0VcgUQHsHYLTqHT9HYvLwybQL1rQS9aZRmohw=,tag:kyboqGPaN5rRMtyqHhbuvA==,type:str]
    namespace: ENC[AES256_GCM,data:RUb19/5r8KAoPw==,iv:hoU/0fpnT02nXT6S54R9DgPSGvYPwNBdGEF/WVbVj08=,tag:sZLLX5RjppRu+3xZQSpm+A==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:GSZlvlVOFhO3VAN90bV9+rB++z9dbdMQ81stD/0KDKQY6Bzwm5o0Kw==,iv:5GHvnmSUrEQhqWFECf/Jfq8ahIHrAQmCqGdwbswpz0c=,tag:/Vy6OmAnxnwgUo/HTu9GaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZGxiajZ0SGhRTVd2a0dL
            MTh4aFdaVTYzamFoYVVTa2pNaDBnRmd3blE4CjVYNXJ3Q0RNTEFCTFlsSVlwQy9m
            eitRWnNmc2ZLazlsZ1diYkJVVzdDTkUKLS0tIG1VSy9FY0ZMLzVoQnZQVndoQVFW
            bmEvTVNhUEdEY2M0UFYvZEFXTmt5a1EKzvbudvBD5eYrHpA4JbLabZlUwfe/bmDw
            xdaOBuzPoALnD3Q1tMWPoY0Gl7HJDmz1IjfnLnF8cTni2+sK/ZBrgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQWtBa0U0MzcvVVNtQTZQ
            cVphNjJpOEVIRGtocENKSk1sK2IvSUZOK0ZrCkoyNXpKdWE3MUpwNzEwbmxJbDBa
            akhORWlMTmtuQ0VwQ0dRVEVQaVJlTkUKLS0tIGVqb0dvdmhWcGJCNzVqWjYrd1dh
            b1hCbU9TL1JPQlV1eGlPbS82bGdWKzQKt7BsnsxrkOnsZgbjfPvDX8usuxtw0KPB
            vnGfidHK35x+SseZBsGX9ZkD4wQ7nlqxPPvU5dOhEnBqDF4CWzJRZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-30T18:32:17Z"
    mac: ENC[AES256_GCM,data:xaSDJs0N30vTgt/Zn45Ycpq/DIP508mQAdMzPon1GYcDWksVkmCrEeWTT0SMhQSSPHu/NvT30ROERKgTO6zRjjwp/pN94e9HGO599FK0ewLLRS3J6BrZehk+HuGGZ5XMlM8WgrcU0Y+aXFI68kg+RZFEi+mb4SHpfs6WF68eico=,iv:3lE5/om8VEYwFxPjjO9Cj+ewvXkF8VPcbQk44iF/pTg=,tag:E/7WJt70Ccz0AG8tfw7hww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
