#ENC[AES256_GCM,data:qwD8zg8EN9lb06RZK8Lo09xhd+p+iojw1Zs5988y7IMGY3HtGv9VzYVu7ytIVAu+Oy+rD57yNCcsw40A9cXBnRq5YWuEUQ==,iv:a0VtDZRX5e8y0eru8xYYbFxoytOq8dqhZM2Pir+g1S4=,tag:tPhojkdF0S+KhQqugCmXGg==,type:comment]
apiVersion: ENC[AES256_GCM,data:tQ8=,iv:ScNN5eSJFkb7xeXFKR+NcVmGcggn0RWQ/N1nZmu+BTA=,tag:+rwcTP3eHfsjJvyjbT7dhw==,type:str]
kind: ENC[AES256_GCM,data:hMHt3x8l,iv:qgD3+dMnvj/VMsqM8GcmCDgO/7JZ5zTFaVc484NPPmY=,tag:GPDP9WaY2MvIknui/nbkDw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0MPmFr7Rair1kZq+NijZCYsa7nxtsr7PYg==,iv:Bkq521hIhn0hMIF2aBr48tCPY1iBAh7KklXeQ5ztV7c=,tag:w8GC9JYPn7DabgSjEn6KQw==,type:str]
    namespace: ENC[AES256_GCM,data:gZ6DMy41SQjwFQ==,iv:IeyLutqF5rNxmmQAx5pB89I8innRE/ISn6aMrbyoNoQ=,tag:5GjrKmrPNcSu4xg8KXGa0Q==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:oB1oC1s=,iv:KgXovd8lhGMpzJ2JoTH4nydIvNsjMbjTbAkrCnNDlxQ=,tag:q1ZKK7imCH7MP9Eaci6rkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQzAzdFZVZDNKTDlmTUtu
            M01MSndBK3BNSHhHN1p2WXdJdStoakdaVDBjCkdHN3R0R0tuQUVFQzhtaVJUbndl
            TGRQMUV4VDF6dVdTREE4aTdkTURpQzAKLS0tIENXQlo2MVdJL090VERyb1pVSTZ0
            YjVaQjJjQm5wWExwUkpSeUdBNFBPZEUKvbN38EUlNXHzPPH1J69fNbsYlzY11NcR
            orqAWLzCNxRiqB5npo0X5mRdhxAPAxkVR/dhs+j+YyPkjQzt6XoMQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-05-28T09:04:11Z"
    mac: ENC[AES256_GCM,data:yuvcjbVsTJVHPZ2auUmZ1AehI4M2vg67jlOB4qmLIetXqlPjrBxjdlrTDx4uUcOTeC4D9aOM+Zs/zZjkmrbm8H6QHMhnatypmEmsixdfb8Bgg2KCH9A+I+Vm2UVKrJIZ1lK0oUI/szx1LB0qClkiaFu8nlwV4apLMVsyT0quqtk=,iv:V89AC3uUo4bpW/JjJPGOb2DFdc8X8hrP7Z8JTBjji+0=,tag:Zr8hOmyBmDPQ1AvdA9jHnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
