apiVersion: ENC[AES256_GCM,data:tFU=,iv:vv5Oi9I8xYJNkAVa+3rdeWH8uVdQK2LqtZ/0/eIlj38=,tag:a7fl8Szqf+ub/Kg5a8xBWg==,type:str]
kind: ENC[AES256_GCM,data:1EjCjEVC,iv:p/8rmAgVJB80wkM6Yi04HZ8ecqZMb489Q2flC4s7FBs=,tag:NqzBbH/NEAxl1qyTXmKiBg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RelJCs6KiezjtQgqYgATXCVlfzU=,iv:vCsyMGpGq7DCjS+I1iLqMxNNknGrsQFkybKxPfFVFfw=,tag:gbN69em39GJgkM6pWytTAA==,type:str]
    namespace: ENC[AES256_GCM,data:r66zv717tQ==,iv:r4SosCXqCR8EGZXZns0+AZT2vx6uw9meRYe1LYip/xA=,tag:THDc0Wj5XLcw0w/KF5LlgA==,type:str]
type: ENC[AES256_GCM,data:f3M6G6B0,iv:7XzOKF7onLkq7yzZrNsIXsjswLFRyqMBFwDiBqhRAjU=,tag:U8PFySdaa37CZwh8omf7XQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:1osGLfY91zi4UmjWBKDsHJ6t8FPOTTJpzi8nEJJXfbidpNjJcfW2zlUtkFrvSB+vJFy1GqBDQ50Noeg8EqnoEWqb1ytr0nboVcjFMQb+MOU=,iv:tViq4DzrX2es7PNgS8lfI3cT7/VPjkC/pUb70oBGt/s=,tag:qb1L77JMchmwnESHYNQ5tA==,type:comment]
    NB_API_KEY: ENC[AES256_GCM,data:k+aS5z1NLzbbrxGBK2bZCck7xZVjUp8NuVsi/HhKqlT70vsTNObX6Q==,iv:SUZAIcu5fDbKHrkwxGF1hyruMF13DA6WNrLt+M1PTS4=,tag:JGLrRTROSTM2Q9aW27Y9bQ==,type:str]
    #ENC[AES256_GCM,data:nCf2YEw9hv62aUWXB3YD9hV4D8y/MfEaGIZTsOHYjZcjhxtbIc7h2HM688kmJbhW91eHPX43DkMPfLsrIRte1szC1c5SprKoAwORwQ==,iv:iGuQiw7N3iermlyTJiS8DF2Pk0RZbizz7qvsBr8SS3Y=,tag:3sM9DvL2m2yDji/FKC5tBQ==,type:comment]
    #ENC[AES256_GCM,data:x9JQyNos/cAY0GGk9dYh6nO6QjLytoOv0VgVDeVJcCMJ7t9PZLb+FsZMZcX7uHAPRu44xwtMwjVmbxDWMFxf2x+VQoCD,iv:jy6gCZ0J4/5BRYR6I9fb36odx/y9RgGCkKK7e+X2pBs=,tag:Y1FIntWrJfczMDY1RWU57w==,type:comment]
    setupKey: ENC[AES256_GCM,data:sSC4Y/069iY9LtlsiAN8fRwc4ApNp1qkxQHIVyUMhQoOM6Gj,iv:JTRGnUNTWPPaV26U/hUrwYKgwTopxFAyJHuUORkYbao=,tag:qUMjiRTg2FNMnYaEGXTzhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRUc3SEk3ZmVqai9JYUp5
            aXJzVHhNeDQrT1R0c28wL01Uc3M5WE5TK1RJCktUUFVuTUpGV2dXdk9oTnQzc2N0
            bFdjcGdkSHI4R25LQTVVbTdnZEhuZ00KLS0tIE45dVBleW1qbGFXTWhRWVJTOHlm
            MHB3SzA0bVRTYndjalIrR0lOd3F1Z0kKClYsT3dpwRrryzS2ja8VhyXYDQMzSNVQ
            UkRCheZPM+m3vo5IAF0a74cUfDJi7KLRtrmIiWKpn/nbLQtHGRjv+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVWJkV25mTGRtaWpUMndm
            NWJVeFd3bzVaTC82R1lSb05JMVgxUWdDVFdjClZIQ1lVaFhiZmVOVUdZZzh5cFEr
            YkttcjB2M1k4dnZiNXdrc0FWY0EwQVkKLS0tIDkvVHJ3K1JhQlRMMW1odUF6T3o1
            WlVsMGhBU0cxMFJhemNvL2hlUENkRDQKzH60jHYPBaRwJCUgqtCB4/LdhPS6FaiM
            UGgjjQJb7+OtGLI3Mtn6iTaxJBcuvKXrkmzjjYHIV/TIgKJYIl/jPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-03T09:03:36Z"
    mac: ENC[AES256_GCM,data:kQETNZWAuZFEPceNoa2X6otYjLMIbs6oNJRSZoSklubN1vKcPCT0oCkQxrLJbaW1faCZf6/l+8H+oWrceH0EF92y1Gtp55RSJWxnRzlc2WxPYfaZNNGb1GqKG/RvShlf/MbKoQCpfkYbbIH40FcmN9EyFPlysp8AGSXwJwb3G6o=,iv:5m296FUCiX26IKScP9o2BTDTJPpLcCzcczsBEIIFgMI=,tag:/R9pS1yJ4R4onjzV4vCTRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
