apiVersion: ENC[AES256_GCM,data:yeQ=,iv:x8oNBFZ6lwVS6WAshAwBm0A4XoP8WDN41J0LiHdkwkw=,tag:4ASJd0JnFNvfWm9aS9e9zQ==,type:str]
kind: ENC[AES256_GCM,data:mfcXjc0D,iv:frPl+uYO+1/ENqcsvSQP5kVHwd0CXHckX+eXtcEgrJM=,tag:UMpcaTafyFJKhhJTnfvYfA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tdj58N+2bXiPhNkqn4Xe0n1QsjU=,iv:bHW27uctacpeXk13pcyJ/MZHpE4Y7j6SyL3BDxrgZr0=,tag:0RkVa3MzfDagBKm3S3RBsA==,type:str]
    namespace: ENC[AES256_GCM,data:Fg2TSo9Jvw==,iv:9k1lhrYAOYhlxfReSstY72rZSgvcYj32TCPS0ZGL/qc=,tag:fd4SuFlbjArSyIKElyXQDQ==,type:str]
type: ENC[AES256_GCM,data:iAeRJJW6,iv:L1ZIF+dHs2CKs2uKI+1Nf4CeDThGuzIs/v27OUxz/SA=,tag:PPjdCeMyhSzM0EnHWPWEzA==,type:str]
stringData:
    #ENC[AES256_GCM,data:XTnzADNUUz5MN//eX02OWL3PsXfXJXeEJt4aHrv8+wTpO34r6TcVTLErlt/Agf5lt3thpKCoXztyHEWDvt8FaZ1B+21jHBsQt28vHEqRT0o=,iv:BHWGFGRf4FiWAU3r+6Sm/tioEO09clFuXbvYs26h+sY=,tag:TMca+gGgIxxBYNyMdckj1Q==,type:comment]
    NB_API_KEY: ENC[AES256_GCM,data:H7qhJV6ExtfUta/fCuTTWbvAtSb3azE1SZb4lNiOPZz4MYrkB82IXA==,iv:/RICb+wrDIXjU+qCJzDUpFX/kiGIIkK9y1O9i8EGfQg=,tag:2FmEUKQKH1vciCNaPkCOKQ==,type:str]
    #ENC[AES256_GCM,data:RGbgrbt9Q27qq+gCv7E7V8IuwJtFtbVi61TBTrFQ24kiInrOJWnItGtMk8PwiOk+/6qvL720xX23VufvjtDKzZWB8D/Z5vlAduXJbA==,iv:sFlKR5rYfUbzM57l6qMJVGvLpUVeB+Js7SDzTfKN19s=,tag:2vJ4SoN2c88C2kQf70cFHw==,type:comment]
    #ENC[AES256_GCM,data:2tDWQxzfCpHBAaKRFcQGhqx9RIRxtwZfU1UoY5v9q90dgTAbLeB8gBmGcuiB3+HdfZT4plzJr3s=,iv:LL78bkGCpULSUY/8n1+cvO+O9YjAjBr5WfRPvvjjZnw=,tag:vO/19Ikv9fTpCIPOQWt7OQ==,type:comment]
    #ENC[AES256_GCM,data:ez10zADUiZLReari/ZNGeguG8Y1gRMC6xUsT2bmwh6Muv/uO+2w7tJOn2mah/BFDYH2JdBSdp8bYwQ==,iv:NKmBJiGgxOeVDIqiI2e/bp4mrQ6JlJP6BWnmkW+QbXQ=,tag:4hzxP90P6+2HlSy8d8K7ng==,type:comment]
    setupKey: ENC[AES256_GCM,data:I+My5b0XECv3w/U8XfT9eTJolz2Hz1SpZqG3yPwn0yvydJp1,iv:xOUg5Hh7UORSgRJy93kqmAveUgLXgGGEuiCc+Eic5J4=,tag:cAreQLvbHO48U7N5wjJCag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcEJ5MWhjWmVxb3NsQUhh
            MFdSczVUd1loWGgycmtCcVhRRkdadTlqc24wCjRsWUw1Rkx4MkpOZmZjVjdNTDIx
            Zll0VDcreHhUbkVXUFNpZTNrQTRGZmsKLS0tIEZ2VTlNNEFuYUJ2U01jVDEvUDNZ
            NWo5UnNKVVBxd1A4RS9Ya0g4U1VxWHcKL9ihnUJVDAR8uXLqIP2x1A/K11iP+3iX
            hvj6qyCnIwzxIoY0ilwc6W9/IJxp1Jb8DjzuGix8uAv6OtZCxhyRHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T08:23:45Z"
    mac: ENC[AES256_GCM,data:EejalIV0J2KyAAUUMnC8/Hx1HTKwEpeprwX7St8gg2KEsPfOhn+zvPADrXR8jWZZJyB5y14WeylqStVdCJh8AVaUx2lomsnshhdXnkS+wUve4QsrjFuCHgueKbIrGv9fTaRcc9JN4Q/FN/o0ynrVjczQCKP2O8U3Mh4noEkKT1s=,iv:b+B+s9EDOkOqM8O3oIjiV02Qu2Mh+5Mj9QbI+w/A3yQ=,tag:V4RGMiN6ZmjaW5HYDikf+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
