apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: "v1.14.5"
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # Deploy cert-manager CRDs directly via Helm values
    installCRDs: true

    # Highly available replica config for homelab nodes
    replicaCount: 2

    # Enable Prometheus metrics gathering
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
