apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tenant-config.sops.yaml
  - tenant.yaml
  - provider.yaml
  - provider-credentials.sops.yaml
  - providerconfig.yaml
  - buckets.yaml
  - policies.yaml
  - users.yaml
  - gateway.yaml
