#ENC[AES256_GCM,data:BN8WDwvu0QS8gRyeSiwWKe1S8k+yCM8YsWjB0kRmHog40H0+3PHNkpjgjEfa2fx2MM5hbUgLx90UbMwtBn03eRmKK3LZ18tuGaA=,iv:ldlPimDK7OmKPXOKpmNifxF8IfzHqCCDAMjBL0TKfSQ=,tag:8IFHWEUy2may0duJZKFFkw==,type:comment]
#ENC[AES256_GCM,data:dlzkFxjvG/nllMsMoMO3BIuTfoB6GMWV87XwLN3WoUOntyMn+qHTlhYiVAhfBj/gYr/pO8mdHx6q8LWxr+wgnvQWnq/VRXzrpDwwUNLW,iv:3teDdKA0wzMJj2sVAGLNfjQtysRKBdpi8jVMZU0egTs=,tag:0Gt1kWyL0ocgwu79KPJTiw==,type:comment]
#ENC[AES256_GCM,data:gY1tPMY5hMaq87FSgR2Rg8iDTc/hsf/LLbmQXLIfbqkqu5e+tYee1lF3t9bPNU//14aKnBoTe4OWcdx9pLVex9XWP+vMnaEOYw9znu75eywb,iv:U7EkLoQhX4kTXjNyHJvlA5xoKjEadkc/6CVSyN4JLeU=,tag:eKy4HPtYdfz7TeZf2hVF+w==,type:comment]
apiVersion: ENC[AES256_GCM,data:3pI=,iv:0ZGGTDJMr0V5FMAGrvO4cbhTE88eOyTTAZP7EoesRb4=,tag:XM47qG2qsdJl2bqAXYcxSg==,type:str]
kind: ENC[AES256_GCM,data:BhXGoMz0,iv:g2D5ksvF3ORwyACEJ8+nUfq9NoUMw9h4ZVK2wQyoexE=,tag:G7FfvokysZc9KBoC90TyFg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4GLGQo70aoAup+UjnZcO6cmZKw0ZKCKuhZc=,iv:35AehAdZe4tHDpXFo3tHPmtkpueO77vYY6bGcC1pkAQ=,tag:Lg6A3oKljpMWyebCjQBPuw==,type:str]
    namespace: ENC[AES256_GCM,data:UfuOw3bsRxlk3WhPndez9tE=,iv:g+j/V4vgQvY2N98EoQzdO1LG8zO/0OS2xTLFIY6qLf0=,tag:hZod86RAiu6Q2oR9Ywh98w==,type:str]
type: ENC[AES256_GCM,data:DyknB41J,iv:DFNcCFMilMl72a3CVr6LPdOTR6h+DietW4CAtrRPEmU=,tag:bOruszNl+ddMk7shIwYxEw==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GZ2qJjjPvPiwk06u4YDGshMjluQ=,iv:HGYoPfR2nxYoZNL7DACTiB3zLi4ETfeRWqjYKRltRFw=,tag:l5k+ZGiQqqoSEH+tgYGMHg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jcDzrPhPiQUjbN+5n3ZSpurRYbtvcqCkgottWSJ5ZHiHV7VYErGKmQ==,iv:xBSz8uTpBc/Pi7gCFAZ8E75vTaW6UNz1UcJGhyTKN6Q=,tag:VUwa4B6k/qmuhzYdZzH69A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQalVHd1NTditMMTFleGha
            NXFnUWhuYi9wUFJqQ1g2VnJZV3YwN0pqRVd3Ck5aMGhpdkRZQWZ5T0VwUFgvUUJM
            a1V5U3NEdWdmM0FPazJzMFVCYUpCQTAKLS0tIEt3K3FiUitvdzhOZzNVNnZDT0RD
            ZHRaL25wb2xqSWxaR3h5N1cxaEFnQ1EK1h6YfSw5Fx20FJeFo/A7LafBTAUOakYr
            7BZdGWO8PRcOuU81d6RSuXMIpqrtKi+H1t7cM8Pt3l2s6SpzAglzFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVXNHd25uL1oyYzkzVHZB
            VVN4SVA1bFVrQ1NNc0E5SFB4ejZwZ1JFTXgwCnhBZkk3Z1ZMa040TW9GbjhYb0wy
            eGtvdENFK0FlV3Z2cWRUYWlCWlhyZ2sKLS0tIDM0bkZFcU5zQXIzYXNRNWljRHpD
            cVJuWk1sQnBWSDJXWXRSZ2R0Qy9wL1EKtBVigAWsKDQS/ibzYWBZJBKBh2Eheo6q
            jPyK3oNzl6vUS1asrZ1uDIUCNwtbArhxrtsk9ndYcx6TvRExLSIbKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-03T07:12:01Z"
    mac: ENC[AES256_GCM,data:3EKXy1o4SAr2zf9zNVc2ivi4MZYqQfxXpxMygpj9calb6OXF5L2pnlff4pq3OwuRPGcUhHX188TedowFo39UXwRMKXhWxpohoI4cEYNz0CZWNYfvTDaCQ9VKB999ANlKd/ObycV/RJt9ND/liVj6zYdabGGPtj3p4MMpT/V2h9I=,iv:HjYmReZCgHuCLGIqICroUz0+mVYS8ZanP9M8MwYW3FY=,tag:DCP4WSrKTw+VGM8S3OpGsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
