apiVersion: valkey.io/v1alpha1
kind: Valkey
metadata:
  name: vllm-lmcache-valkey
  namespace: vllm
spec:
  replicas: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: tns-csi-medium-nfs
        resources:
          requests:
            storage: 10Gi