kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local-dev
nodes:
- role: control-plane
  # Expose ports 80/443 directly on your macOS localhost so your browser can hit ingress resources
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
