#ENC[AES256_GCM,data:3lyHomwyKAWUUw1QP3USw7Xm1kToKCL8uo4mot3a2VaT18st2z8CA8g8Jv6IczmBOEdRtBTVLEztFI2dTmcPxrdWomy4HwTWlUE=,iv:NgE0g3q4/49DeC7FYHEjYv/SFY4Rnq+GBL4jaM7uogc=,tag:BXWRvA8x863xl8RBVTkIyw==,type:comment]
#ENC[AES256_GCM,data:y2TWWYrMCVy11H1D7uwYnJy953Y+Fn7f3YwgiZEoAcw97J7qS3dZa91OEnPvm6m3NT4MZLsfGKAKdzNDSNvmf9x5,iv:2uPPMIuLyJguGYdZDLARaSjswQBJi5/GVFDZi+cs2FU=,tag:ijRDgV4LEhF0T0zp5GdoYw==,type:comment]
#ENC[AES256_GCM,data:tjhnM5Tm4poIjFSIOiYWvJJptb3yV8xixzULspSQ3195m06Z5Z8CvQ3CG5vrjUDqBh/zwLydme9EUrTa88STkjolN2CBXh/CDoP9CA==,iv:Wk/X9YzSYcpCXu+mAsA7wWtGuo12RsvuXhOC/1e3hog=,tag:2LEQqGIUloGFhEPh1h8gtA==,type:comment]
#ENC[AES256_GCM,data:BG2XxkebB5cSylhCMqLCTghK6GEvId4kmCt7lvoBkvA+Gyf0Me2w7kySQrpnpgDBOhCVg+GJisskqvnVuwM3h+c+JtrWqttkybsr,iv:ZHIdf8akygoayi2mWiwgk9pINY+e99YrpCSiKyoe9Qg=,tag:phLa7nNgbYu1kPcCPD3JgA==,type:comment]
#ENC[AES256_GCM,data:NyNPEiCusFIluHM7UQqDNqDr8URvkKVFAU5Oe19P/MLHMvX6eK6X3BgZt5OYCa3tpLVnznnx/qpSPCmvqHQptBgEcA==,iv:fY4Pihowo6DmZuSpEmwzncwcmknfL4awzhLgbw+MQxI=,tag:edq6XdrEL4SMmbrBmkP2Fw==,type:comment]
#ENC[AES256_GCM,data:Uad7q608ZJyA7Dcb9ELDJPugNJIYJ6v/DqCP62fbVq/w1/GmLlbUiCCn49QkzPICs3YN/w39ZOph7iJEqukeYZiuLllJlVwKqtlJBw==,iv:F/gnRpsGy016KjDNyNpmzpBXdvKq9/G6XaW5qPxIDs8=,tag:FNB0tYT25qaFWoU4CzHP/g==,type:comment]
#ENC[AES256_GCM,data:DHhi4UD4CFEnohZQtHf0xIm69Cx/5RBzzufUR60L8tcVLRJoBskffAG/G3BDT3gmpgG+NsRskJsG7llrUQ4cb7Mf4OftFQ==,iv:oJQYu1XY80uHjSPzFrja1z2tRyAPlLszzCsuETfzTF8=,tag:h58p+2t884EEUdrK1saQ4A==,type:comment]
#ENC[AES256_GCM,data:GnX6HaNxIJpvqeOmaQ15WtT3ju/qQp4CEdFm/tI1GbYG+HlOE6k7FV/bSIjdg7PLVKovyMFyJmuJoebQY6bk9+2la/+8hZ7X,iv:fdSTvLmD9Eus3wQ1D9nVZjVpiHqXcNtz+Ejr3UH5tys=,tag:DZgraADkm25dDAztOerMIw==,type:comment]
#ENC[AES256_GCM,data:YwcPgQGAo7LWLhKFIr0oVnIk7azC4enO324wtNt2nCBcRpXepVsbWiokQ6Xif4Hs0XeXMsMoA/YAayRHALqWmA==,iv:qTWbsFTLZEH7UKLKThH6tif2jiQbB9VonBwDohQCvEg=,tag:xbGS+b5DxstdHjLeKzE40A==,type:comment]
apiVersion: ENC[AES256_GCM,data:mx0=,iv:lnv0ioa2jG1B8IKyoy2KnfGLpuItP42yy8UWmygKyPc=,tag:28gf11OPQA9aGB6W/gGGEQ==,type:str]
kind: ENC[AES256_GCM,data:WpiIpyh8,iv:bNbAWa1TgQlGCjl2Pke+wP0frUZgfkw9ESFyDawOJBQ=,tag:LrXoLv/SsfEE+LbKPezQpA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:b+DqKeD02KfMBAV8ZVSqwUVrihu9,iv:IjlCVeWMnlCJcv4vNHSxfY2E+EcVzdXLQZ5dn7hmOBs=,tag:lvUTiJzph6UuUmRlNTg77A==,type:str]
    namespace: ENC[AES256_GCM,data:ouyXdhrFeFd3,iv:U9Tw8Wou8uoC0ZAJ/LPhhrA+WBXTQyEcwhCs0oOfVOU=,tag:7RrD/S/CmQuqHoXhgu3rmA==,type:str]
type: ENC[AES256_GCM,data:9KymWHip,iv:F+DLM/e9nIOJ3phMPji8wORlS97qKiNWsF6A5yYN4wg=,tag:owzAxokTal4yp9NGNR66aA==,type:str]
stringData:
    AUTHENTIK_HOST: ENC[AES256_GCM,data:4VKV9Xivnt99s65zAZrqyY2dJKMqlRIB6KwK6iGrz93sypVxMD3Uewbgg8fqf22tcRQN,iv:gQUtlJTYHPvttP8SqCqqmro87o1v0e5RFMnoQrpQDHY=,tag:hJN8/TXVOgqnA39bRsHzAQ==,type:str]
    AUTHENTIK_HOST_BROWSER: ENC[AES256_GCM,data:cPnM3vHoD9x8o/1c2WHGdkdV/4DZV+9Hey89qxM=,iv:1ELbF08W2hTZTFRZuBdap8uVH1tdRJ1f4UNgFq4FnUo=,tag:uw2HMOCq0WKJAPe4Y6ORoA==,type:str]
    AUTHENTIK_INSECURE: ENC[AES256_GCM,data:CUSuPs4=,iv:Y9X7EjnpeUH8rSq3hEWds3TnPziMDY/FAUgYNh4j9uk=,tag:3SjcgOQj+SZE4O4Oy3//Og==,type:str]
    AUTHENTIK_TOKEN: ENC[AES256_GCM,data:kWCBr3AUMhYIadiJ407G4RQE91fzekjuJcS6lRvcNnvSF1D45BFWeg50mLKBQRD5zp/HfHD1YSu0qkhr6dkXnw==,iv:YEhRRmpAXMaFar41QGMWGNSLBIorjdX9sZyZS+6EBBs=,tag:YDhWydoahJnu7yG3Xx0QDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ3JKc09MRXpSVS9GWTNi
            b2syT2JRMnVZNisrYW1JMWsxQ1lhN0dwazFzCnNwenUvVW5uM0I0bUNjbEpISlRj
            RVlyVnQ3Ry9LUXVaUHVuNzk2Qk5yOVkKLS0tIGtEajh5SFFrTHpSSStXNkluWWhs
            ZTIydHhRdGZDVjVZUmh2RlhqVWN5RE0K+96nxNoYY8KhDp3aaipZJXgXlCrKd/lK
            xhGDqrrknJU8F9XpOf/fv9BNwh2KnXXJGUk4hBvi0szzA0ivm4ixxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYnhJcEorSFZydFdVYTlO
            WmJNWE9WaVBscjVKdHBaWnN5TGtSN3FiRUZBCmNFL3BpajN3dmFPNS91b2d1R0M4
            ajhIUC9hME5NV3pvUVg0dUpmeGVOZlUKLS0tIFNqeWxUYXgzQ0pzQ3BPNDRYRVB2
            Vk0wTFVmZlhCdGZGa1ZQY1U2Q2Z0R3cKMuwfpXPKaukV4f9OqG4x9aigsw0ENkco
            hl1ZxcvwFYv1Y6V/q3LF+Q6MAcJVXHHpt655NChs7Ux0trT24W+u8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRlg1Q0RFYW93ZTU0K09Q
            SSt2OHZ3TnllZm55SUorWFZEZzdWd09VRXhBClJuZENXbmpJZFpDaVI3Qk5OdWVT
            UHhEaWcvS3Q4Wlo5eWhPSUNiRjBaQU0KLS0tIEVrelIyLyt4Z0dZcFhNUFFzeGt4
            SkdsSXRrWGdXRVNsYllnT1BXY0RmdDAKv/uomHZsGOzzEXTym+nuVxC9Urdzgviq
            DIk7v1KTHU1KPuPzTk8xWaYgGphV4+K8YkmrRV1t0vKUnX4DVi5P9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-12T19:10:59Z"
    mac: ENC[AES256_GCM,data:RGHwSNrVVxpI9Y2wi+744+ZWzSfU4jjUy8kSEbd63cMEl20TjvRibFqhPcZMMCY5lJTPLeQJZWHTTpQ9D34lA95XSK8s7fxnNKdtqffad3rmQYO8ty0xOhBZIvz6ERYXflQ639YAuYDgW0fgud2MNR7PfsBgIqZXcuJf2/w9buc=,iv:vYlv8qaT6n8+PjvWQR+18I5L80RW9/wrNDed2b/Nw6M=,tag:InhlbegYd3rSkSzk6BsT2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
