#ENC[AES256_GCM,data:LOiVq30XCjZTa4vYOb7CnG28IaOylr95UR35fx/GxKiLnLQy2M0P9FX7dRktKDQdUhgCSTIi91HeL2YKZfT33BHbi/7iXGjp,iv:YJqTMNHssM4b4tf8cqBDEX7ujatUbjH76FhiQK33Os8=,tag:8QGfitPw0LS39OKUp4EmYQ==,type:comment]
#ENC[AES256_GCM,data:FER+xZaezHRw8WkQEqLBqURhRIH2rF8hkZRdMpItyTTbKzD1xsWvCwCOPx0BhcStqUWqXaFWlV7P6g==,iv:Lht4vB4pzJNyllXodRWmvXBLRfAX3AMrG3HijtrTRBE=,tag:oY32pB0PAsXiANTJBAHnNA==,type:comment]
#ENC[AES256_GCM,data:J3jKkt4nutWbM1E5uksE+xVsGuTRv8M1NwE2dl0jlqYw5BUkZQKH1YRl7uyyeVtnaIRF8Beo9lJBrRaLIsmHf7KF,iv:/ebOIjGavXh2a0aSdpT4vL/UeLS5/14he1aVNiU6ieY=,tag:n9BTq5LcOmUqr5akeO5zgQ==,type:comment]
#ENC[AES256_GCM,data:wU6d36iu1F28y3rCCBAh6x5U1SWA7rkWJPtAgYyYMIxZOQjJWbauStmYq0ljwO3CVbJu89FXP961GwqeNw==,iv:8hCPFMUPCq9dycISc6r9CQrLiK6lFhjqmV4XK2PNErA=,tag:R42ll5JyrNmMA4WqY4UmrQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:GQY=,iv:QD2KCkFr8VAm0CpRpauenjkohT2WVUOylnyeFRewI6E=,tag:nUdmcFfwEZxZZZHsCf7uVw==,type:str]
kind: ENC[AES256_GCM,data:OuaL2tUq,iv:pVnnkahRSo3ThomK/mdH3oeICqfjyTd8j/XRSpEA0ac=,tag:EqrU4+w6LLOCTgJSpwJzlg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IonVIbnEDx8QsvYUQ6lUb2zho5AxmhoxUVhHkAbw,iv:V4WaG4t9sNAey7KG8LP0mNW1jbWbf1tbf8yON0P66fw=,tag:Mjpd9+jKOj2HBZC6wRLebA==,type:str]
    namespace: ENC[AES256_GCM,data:XUs/JCmh4eZ6,iv:S5Tey6O23ZY6nY3AncZtMcabmW1Y6X8P3FBrEPqPv2M=,tag:rFNngIT/kpMmp5W8E0btGg==,type:str]
type: ENC[AES256_GCM,data:KzjuGOesa0djEuWj9NSDDcAXwcsA2ihV,iv:rUzQVehNqhNhw1cRU5RdQCR/LAJaB1DUhqtwrYxR9uk=,tag:+sjKeOYz9MTEak61XM+2CA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:0Tsd3RHAgPjg,iv:DYOxnuGk75CfFjwFCr4MgxWo7zwGCtXhRARh2muQIT0=,tag:wI0PoG+0DxBItErUKUm2ZQ==,type:str]
    password: ENC[AES256_GCM,data:/L+w1DKW/CB09ydgyj4EMoJxaNG7lP6+yOmfDlr1lEg=,iv:zeHFjBBlD3jDQLht9s5Rm20m/63r5pep5jHCxT1osLk=,tag:BMckYJ78IXDWKVh4ylgEkw==,type:str]
    database: ENC[AES256_GCM,data:M8c/E1zMWXA6,iv:mGJnoR4I2Ou1VcpnjD3dU5w09F/67IfOuBGuBNJ8234=,tag:ubCggIDZs0BDf/PiKs+AwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN2h1MUdqd1RjOHdtT2wy
            eENDY0h4a1hxZHJOSnBNWmpxTGlJLzE2L2lzClNoNEFOUXFlMHR0SWxUbTdlU3V4
            SkE0ZDNPQ1pTUnBKS1ZVYnJvZm1WYU0KLS0tIFAzOTg0alpZa3BlVFhOaDBzM2xL
            QjFtWjBJenh5NXFxUUV0SWVtMUFDTFEKyNr34JfOO1U2QIoaeLmoUqcLp3SdjChP
            iaVJnZwCvAtpe0ef4QzD2k0xsd2XI7HILVkXFee7eh5rH5/DWfU5Hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWVV5TFk2Q1lhdmxJLzhL
            aW9yK1ZicjhXY0w1dnEzcTdTQ2UzREhQQzBJCjhsUzNBaVFrWVRvMnRYakhTaEhE
            U0E4bHVuNklVK2VsbXZ2ejZhRVpwWlUKLS0tIHQ4R0dzUEFSQVlYKzZ0Vm8zRXhl
            ZEFFdjRKR3RHTnNGVjN5cmVnbGg4UDQK40wpwPTIYWxlbVeRMOjIimqm7LN4vtTO
            33L8V7UvPOJkmxr+LUrDm8Q56kLTwxjuWpSsPACz6rdz2KPzLlDuHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaWltOUkvaWRlbU1LQTdz
            M2JheDR1N2QyYkVad1Bwb0RkWTdOQjFVV3h3CkZqaUxxQ1BpVHNjMGo1KzhUVkxs
            UmNCL3NDTk9UeTRYNFhhU0x1ZENmSFkKLS0tIEhVQ0xrRnU4dWJGcWh5L1ZVM0xX
            c3NKb2dGdk1BYXpyNm5JYW5vbWdnUXcKQlLQva38snGj5p1fa0zGjaivHiCO+ivv
            OeV3gZo2XxPZyjgNKmm7h+xL2D680MA1/9E7rlIGFW0wDczcysGykw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-12T18:54:35Z"
    mac: ENC[AES256_GCM,data:7SIkdg2bMwkyLaNg4jypl2TMElvcuU5IxKs4dIzLrg2QyVb5nN3hkuK1AzuUrmcGQgOFYrTN3WorQ7jbaW+JZwyWpg6oRMoI1gQ/p8JRv3IZiKM5VKuuFIbHtuxBKge2PClCZ+tuYodjUh62qIg18m7+xJT9AH+DvP03hAOz/Ds=,iv:riaXtBQwqMS7mgnVnpH6bwlSa6YbQmqVY/EBHMjw/Ss=,tag:DC/dJWFjHczMW5Q3IylJ3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
