apiVersion: ENC[AES256_GCM,data:dWo=,iv:L64wDb4NeijaQRE2oZQ4vUMuUQiqqpcsdSbTs/jnIQc=,tag:jniZ2a6+J5a9MMrOe3hlZA==,type:str]
kind: ENC[AES256_GCM,data:9Aw0CQly,iv:p3ccjmRPLEhbIBi637yCg4C7UX4u4gMPB3xP/2cfc40=,tag:Hz1CszHDU28baZ0RWfdayw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ykYbjGHjc08FhDNzwo5a9g==,iv:+K+WKRXmS8Y1ehUdrwwucxfNzPQ6rlSFeVOkqfLCOCI=,tag:OYuTXGZ/bicJv+Ta1xPDWQ==,type:str]
    namespace: ENC[AES256_GCM,data:lNCf6IiIyTJk,iv:RgD9yn3xAd2RtMR4exHlm3sqSUAN5YXFgAuRPclvsKI=,tag:zObYLLAqRocwoIUtrbRwyg==,type:str]
type: ENC[AES256_GCM,data:5GnGIa0l,iv:Qf4/qdco4D7/KhgX07wZBgYSxKZ4ccuHQPQ5wN01Q1Q=,tag:9L1ecEkZSVQq24bGfZciWw==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:4LSMkBBvksbh29JUdtFmflt1fC4fl744OUTp4XxDPS8qFpBbzhKzI6hQALtE2TBfac/+O8GUXl7F0zbUYtkY1Q==,iv:wSe4nJlvqwMATFs/qNLa86QnVYaSM6lYw/BPDntb5b8=,tag:jdOx0coQAV+9HmO1HVHtdA==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:B++a0QyLAJ+ctdjofAXCg638vrFn,iv:KN7L3KUoSZcv/PUtteZZNwB2s82qacPUmOHgRETJrT0=,tag:0gOCUSQhFWdR8q+6ixra2g==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:22M5TA==,iv:SRaX9MbOtCsiiKarmzwShj1B4wPeHs9Uftt8HByNc3c=,tag:e68jCfbOAgqpOcuvOHqU+g==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:MFMzx7zxPgDk,iv:/Y3UlZifWNH98YyJGs4pKx+/x3cZEq3fHNjrNbl89oc=,tag:9wo7oZeMOKYF+6ZIoyyz2Q==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:eDQlcgXPCdB9,iv:WC8nQ8P03pfpkWB7z8ISnTdzqE+gnWFEXn2fg/Ci5ig=,tag:Mw7oyw08nC7z8IxAZtIs7g==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:/aR1OGbrCFv4fzIvTej9MIOJvmQcDB9p8r+9QWOmvOY=,iv:jC08LwtiQ9oi6geJnGZG0SdSnwVvHxO0lKc9ajdRmEw=,tag:U5YEOt+qDHfyW4FTXzaQuQ==,type:str]
    AUTHENTIK_POSTGRESQL__SSLMODE: ENC[AES256_GCM,data:ZhAcO+ay,iv:VVixBnf1iof4uZMDDVoXa93nLwPrnnq450MUYn/27cQ=,tag:NMzmkHpsKEg+LtdCmP9bYQ==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:ihRetsQN0zxEo157,iv:ZOt01iJUjXbM74nLujw6Y3lX6e6FhkukN6s41cteY2U=,tag:IyDWCpMajC51+ocxxuV4lw==,type:str]
    AUTHENTIK_REDIS__PORT: ENC[AES256_GCM,data:+P7fsw==,iv:CepRQglGjbwer09E7w7AzTLGm/4FbDVeBgFbwRxrn6A=,tag:xMxmDkmWz/HSH4CAvDBPlg==,type:str]
    AUTHENTIK_REDIS__DB: ENC[AES256_GCM,data:Kw==,iv:3bKvLT62YDgZlE1CQH1xHe+KQ4cog9KwR9XgUMwRv98=,tag:VQFPgAzav/1gQ/Wb1wUn5A==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:eFuk3ko=,iv:2h7/OOVDNdSe8KfC0s3pGEGMoEsH7+xh8yyVEhPzDu8=,tag:iOezmkDcp4cxRN31Wdxgbg==,type:str]
    AUTHENTIK_LOG_LEVEL: ENC[AES256_GCM,data:tvHo7g==,iv:mt8sGLe4gt9j5iRNT65d4csdIN8IfMvjA5+TjoBd0n0=,tag:qOpMAwzQ3JFceaBvWm1sUA==,type:str]
    AUTHENTIK_ADMIN_PASSWORD: ENC[AES256_GCM,data:Ex8iDLmxZdyZl6sQ7xHhYGLJZ/pFqZ++,iv:Cg8oaZZk+VBj8kJGMRE5uj8vhkuJxcViP9btPGMl10Y=,tag:UCAr0QY5QX+hrZtVLcgJlw==,type:str]
    EMAIL__HOST: ENC[AES256_GCM,data:hRDq1uk2049qZo1XCYTATFOF,iv:1v1qh6Uhdm5SAqcJcSpLKhZs+g/WdXMucZedOStJq/Y=,tag:aHRnxG+cPY8sRlBpEQzTNg==,type:str]
    EMAIL__PORT: ENC[AES256_GCM,data:G9Dt,iv:rbNOh3dWcv9BfFB8AniTmCqlq+uBdLVvmU9VhXD7Fu0=,tag:pERA+TLLb7u8KM4x3aM9tg==,type:str]
    EMAIL__USERNAME: ENC[AES256_GCM,data:bj07LY542LEaCv073YsnjaubLQ==,iv:i+o9hsZczbr6CfY0jyiMO26qvpBC1gSjVzS2yMhYbWI=,tag:G8F13cyZRW/D2nkoIQTtOw==,type:str]
    EMAIL__PASSWORD: ENC[AES256_GCM,data:IbHp4FygDnd7JpLshTlnMQ==,iv:/+zz978NSHwwj0VRfQe94adyFOT+vy1bBIZheHR72iI=,tag:D9gJCGJp1vDAxdf/WQufsA==,type:str]
    EMAIL__USE_TLS: ENC[AES256_GCM,data:E++XJA==,iv:UPaLFkED0a5wDrWQkYGcufoOAbgB2ED3zfso3zxItMU=,tag:SM3P6ksInq+VO8OeXYKXqw==,type:str]
    EMAIL__FROM: ENC[AES256_GCM,data:8B7EfMYwL8V/Bzvyc++ccu/Ryg==,iv:zcd24+TosWP76hVigphBs9VblUKr/2/JEw6CORwSKA8=,tag:lidTyTqXB4oFvyGesqRVjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUjI2dWYwZFpLRmQyUGxn
            bUEyenpHREJmL2NFMkZqK2RKdDQzUW55dkFzCjJBVTVkQktvRng5d3lPdEsxY0Jt
            WUZPbnV0dmZRajlObjVGZWRMd2VjNEUKLS0tIE5CeWhQMGNDWFp3LzRZenVFZWhI
            RXN0bFhvYXFMUlZIRkViUVU1dnhCY1UKQk0C0Xv10oKXVcKUr6/I+6VtPSyjTcny
            YvifppL3QlFLT9s9YUUamRzOnEv+pc5lRDdFupKHqI2oz8QllAxkug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucHFidUtnMmRjOVlEdURV
            RWpjVUYrbDBvKzk4WGE3T2tOMGlTL24yT1FnCm16aUJHa0NCQUpWdmhTQVJyM2Yy
            WkpxWGgzdkI0TjgzT2E4ejhVL2pBTk0KLS0tIEF4SGFLYlpCa043UnRHSWFjelNh
            YmsreVdNWkxXaWJ1WWlkcWtCS0RCRE0K2B/5/fJcmfz2jtukm9/j9KyDayLmCrlY
            13rucMteRa81aiKQxU7eVSpxTPoWsxOCN8IhEYlKK4HpBI4g5zSEPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWnQvUTJnS09tVG5QN1BB
            ZFIveUxUVnhkbFk4cEtOWHMrS3JFUmxBa1NnCmFlc2hObGQ0cFgxTTloWTVoanFw
            V2ExR1g3L2lyV2x2ZDUzZmRzMTJXM28KLS0tIFVVSDAwYVZOdHRYcXBBMlpaSDEw
            MDBhOVVTbFJ5OWZEbFRRY3o0K1JpdUUKlWciZGcb6fM/rxVd7xznDX5nz2mNQJ9d
            qRZTnjbj0FihcyzOLOnLQh8uNSasa8dWVPZJeE9TuN0LIvODO42yFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-16T09:52:53Z"
    mac: ENC[AES256_GCM,data:oCIQlekWSt5nUjURwre2kkusLNJU/1mgeUFnG+iPR5kgBNHYeCpK1pkDHm/kyRRVMBmYQM7i/PhLeFKLZcl6AoS/mGnx+HhTYl134Cj5w1+Cl+hZj1qPdcSEa4aKkMOfao9JcVEQTTs8oLJKuY+GGShid/knHVqSpOKWRFVMrU4=,iv:DXaP5VRVZxXGDpB1Q6X5XOCBhibGYoim2LGdpDvWqlE=,tag:mwk+/ZHI6ZhqH882FPUn6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
