#ENC[AES256_GCM,data:jjM7/ZrGPaYhVYvTQqKxqoG82GJb/mmk9LQdiRN8aerLo7WetJNlXIFz6qRVG174+4DTjobNmb0P+EY6HScxnj/H3MFBmqJY,iv:k1WKjbPh2UMBB7C27/LilER7xfn1ACan6eHBA2J3r9E=,tag:Be1wduSmN6yOWIagSmsvsQ==,type:comment]
#ENC[AES256_GCM,data:UIneSsGbfj0HZt2LvP7ULIyarfcxV1Y1suRCtjr8XCChlg0NpiFqTy1+fJXrV6C2fX6tu20=,iv:4ZwExI6Y5tYovtmRCo01uRXGQfu5hvcFnq9ExBb4QCU=,tag:0j5mteL+StgjH5xr38OG9g==,type:comment]
#
#ENC[AES256_GCM,data:KfKgU/kbfHROfJg1gLjkPdm4nSxZY0sVn6iZ9OhIgiOtfU08Fm7Lqp6C+uJcQGAjtOGfCBSsBb2MHPK0cQ==,iv:vQF6LpBJwPNZIfFBYn81RGdInlQxbmnfk9KT6hBvNXE=,tag:R0Oib4cn6EerbbT8vf2HSw==,type:comment]
#ENC[AES256_GCM,data:fSNHl7mpugqegn26Pw/UashxQlgk24/Zz+r0rt/oFOEJi8FGIubaUb1dYuyvl5oehpC59OUPOlwXGPFaxndvj+k/m+Lhnr3AqYHB,iv:hEQDeA35Q34xQEYbSlkzn5YHBDiQ1fG1NCIh/ytxvH0=,tag:JG/4QWJzn5xYPB7EY/ajpw==,type:comment]
#ENC[AES256_GCM,data:iUT5JfFfd6sFyEmElh/D5PCzqQlZ/RRsirHMbA==,iv:7KHD1u5M1vAb3x3EXWUxzFa8HZff/2XjyZQ4Hpom+IQ=,tag:1pHcDwM9M0bc0J+3EDV7ag==,type:comment]
#ENC[AES256_GCM,data:xWT5BXx/l4/N52Pb7p4tRHIItYvQQkukEEwhCP5o7l0kciAYtXNJpS5zw4kVmS6Oxi/aXisAYc3Z6jp+EVAnP5EAzajIbJbKCY9TZbI=,iv:KR4qvFXgE17+gpjzLa6qrmaocHOF3OQ+VYbjXsW2Q9c=,tag:ShTQ6C0WSH4HbxJvwh2j4A==,type:comment]
#ENC[AES256_GCM,data:eA24A+qAaIo89AOmoD5foyiSCEk1LTMX0riZfZqnr9wjYRQ0J6qmiDsnyuHbPWIYTNXLv1y4MvX1epzJvWgMVBx+XRGjBCRP,iv:TYz+D9UvrlM6B8FMZHnbxsSivMjRpLrlfl/rSoN9QBQ=,tag:d7xZThQoTrLOI/pz4GeIsQ==,type:comment]
#ENC[AES256_GCM,data:UA8d4oa/s9GULLMfwTc=,iv:CjrVOyaO+yLestn7lPp5qrhIGXC564LcIoTeL6GtlrQ=,tag:8Gu2SEQEIGKdIuBadYlOVA==,type:comment]
#ENC[AES256_GCM,data:wFgD9hbwQOYpJIncR5BYRgS6D/86hFMFUq05oTumBiA8VlpDiJDMOh6Djh+8D00qZlvgVbcR1cJsvu6LrS+CtO5h9kWrtJxHg2bQuA==,iv:uVhafuIMYfIZ5+694BohTpDXB7xEM0feradU+yRSiU8=,tag:8iQ6k5dRmE6j+cZhIosi5g==,type:comment]
#ENC[AES256_GCM,data:QVfXiue9KIiYLFfluHI2PJUd57JLygrPsLIG7anvmvj+XgFCPbX7cXasKww+PYqZH3OgH4rQ+9enUz5VTYbt/Vsq4dfkYqFFl98=,iv:dQvqsySOgoaXauDN3m5LLqH0w8N7nyIyTPZp2FwLefU=,tag:yvYCvEM2HfDBoU5WxyW9Cg==,type:comment]
#ENC[AES256_GCM,data:WBcVEiqvcLfyBLRiMzkubU54hQRFlLhZ6EuRYFrd2dYJbBM2NifWeXh1WhTCUimlzV5UgMP59SB5IIAiZ8fmamA8nFqfFObTqg==,iv:5+8nmtKnButz1K/Xps8wW3fo98yHCsYdcuPzwGvcu74=,tag:T5N4KWwY7X9NP5c0Ch7oxA==,type:comment]
#ENC[AES256_GCM,data:JQEm7JyNYZo5dVsBmWcF2lm8mZSI0763b0C41fbrA+lxwspXavEd+sQJXaM1e/3EI5OV//w2VoiA2J4ZyywnHeuDor7E9Quq+D5tOhk=,iv:M3G1hwxD0//JdJwuzuW/JcPNnpLQmKzZUZuIQLaRLcU=,tag:crxo15vfFY5IAYhLSGz7gA==,type:comment]
apiVersion: ENC[AES256_GCM,data:7Fg=,iv:VM2GZLJgEGX8I3GAu/6PAojjKisvrkrbakvtbBiY1bo=,tag:BG0+GFBvSzW5025BXOQVZg==,type:str]
kind: ENC[AES256_GCM,data:/G+MZO83,iv:sCy+zAXfoKV7rpT6CYLKhYwTs55E95QJhTrBCTkefTY=,tag:ShQIZh3NxQaR553FwljYWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HY9RNnQN86/shpTAPQ==,iv:4Kk3jzLuqONuV0UoWm9ru5hIvOJAKjXQ1uQjv+0w+FU=,tag:MT2ETeD19Lk28tiwa4q0Hw==,type:str]
    namespace: ENC[AES256_GCM,data:rkhXWBU0,iv:ZI2dG6e+T1Yx4xRu7PfXKQPjrzChMUrsj1/fOM1fAfI=,tag:2K7fcRz5MGkE1Lw6s/RwwQ==,type:str]
type: ENC[AES256_GCM,data:1H2CZgCm,iv:6rNoYIIjQvnpyuoaZMCtroC4+oGuvsafAo6m0VENHMU=,tag:1m3aaz16JihU+5nDfuCg1Q==,type:str]
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:yRSi5qoWXQkKD5AIsK6EdcOunjm2FJu5N8bltrGDuhDeV31fbU+za8RHjY/M1V7KA7ksn30zOW1F3V0R1LY37QuVjOEpoinKlQ==,iv:1XN9FzbZwRx6q/csEWrV2Ax/f6FzCyCTIHoct7InGRw=,tag:0ylvpTfIL2v3vWVjOt6Afg==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:DEipnkKlycHAxyn2vvIAmOn2By8akRjwlBVqXBOTXUeWc1VL36FIk5w+EFce7OIqDJJ9xObATjAlen1C0X0gXA==,iv:zsoIW/Iar6AzAHWQ/6yRJQgY0QRDMDVVK8vX456ukMo=,tag:IacNLlerIeiathCOzIq6Gw==,type:str]
    #ENC[AES256_GCM,data:rmJIckNVFkhL3HMr12ai86pnkcU4armHeXdmXYv4vUN/OzJqoanPFW0KV51vrd8d190Qw5XJm9dqz3rESzte2toCig==,iv:XWsYqTCGTUvCrQbRAkIvZGfhZCeoTq3TgAeCVQNFZjw=,tag:Nzhuy4sv5EQNeHQFn0AbSg==,type:comment]
    #ENC[AES256_GCM,data:Ib8hdTHjuQk8ekHfmkmMBsK57K4FP6nF2J22ZwEopXLquubOWHuq0QiQ4JTImYUZbV24a57t3rX1LwxY8j7P5ztKxAMX,iv:fGkMBh+IMeE5zy0a6QGuWED5QwOcrjH1mxRENL4kXyI=,tag:LrnwnUc6WFDd1Bi5nZj6+A==,type:comment]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:EAEdYms=,iv:uQc0P/7Oyp8q7A+KvzU57GZWqeEiwDdTGKvalcbu+gs=,tag:suIu/JvbBhb5hmtGY09QbA==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:21vKT14UccRfjDdJT7BkO/0tCNz4v/A=,iv:piKgVYUsrgt0tYvNU+wZOOZA2fYMqKlr6jG5/Rf6SqY=,tag:dmOfvrR5VlvQoSUtjwqNqw==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:7oBbeFSn82aghlDKd5uPMt99EkDyQAyLNnUjzkPT2KlZLQdBhCoDxDNpPVw=,iv:jGH8l1YYT8QmoDV7a7k7nEzs+fXfhnA6+SUNtrMHt3U=,tag:YfY0oacUhIN+gpiK265deA==,type:str]
data:
    AGENT_SANDBOX_ROUTER_TOKEN: ENC[AES256_GCM,data:G6oFKOhjKutGLCB+5B6q8PChEEux9DhY5KSKgi6RcSRndo59MBEP2DPGJXg=,iv:DlSlcsbFgat4InjwR4+sEdz8YmL7FrJTOIClXc39Nww=,tag:duNHYg728HFUlpFykcU6DQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M3Z6TEdFNTJHVVV6MCtl
            WXRuNDlTaWhNUkV2emJhWUJNVkw5eXZlSlNFCmM0S3RRQ1E1Vi96S0VIcFc3Mnlv
            VGJDU2RaVCtRdllPODRmMUhqUnVjQTAKLS0tIHVRd1QvbzEyeHpSOU5sTUV5c3ZG
            b1lhYjQ5eDI1SE9zN2FrVjAxbmJuMVEKbd0Y5gWFJEyoEETmnS1l7CW/Rk76eb02
            3PYREIipRrzeAsxzOAepOsGjhPVfJe7G0/XHMJ2C+GoD46DITt5izg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOGVKTjZwQ1lrTHlQaE1H
            SG9wZ0taWURvQUtJS1lwMWEyTDgzRjkvL2pBCnlRdWRLd0puZE9aOXYzckRYV1RT
            MFowVmJ2djREdkViRThxMFpJYzlZWDAKLS0tIDB3SEFrMThGRmpnZTRiMkYvSm1p
            WXJhdUdmZVFydXBrdDY2RC95VGJpaGsKCY/tv8vIk69IxvOpUtN2V5Xd68i8chfl
            ZpJkarN1qW6F/vG3i5/7Jms9Rq3aBdnpYzGfMW2xrOCeXhw9slMm2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeXB6M2FteUp1anhKL0lH
            M3YwV2tWeUlkWTYwa2l2SnZRNXVoajE1SkRzCmdhVzlOVTc3eXZhSEg4by9WaXI3
            UUZZeGt1aGsrZFJaS2RMcnRIUEFyUzgKLS0tIHpRSm5KYmlNRlpndXVOY3JaU0g3
            YjljTFc5eDk4T2JGcjh6QlAvV2lKcE0KxBhvZkwgBU/q4k7dDZc66IobKGw8wNu7
            SVHsDOmpDRIAQr2NVn3IlMLN06NPCgYjOAUsJTRTXHpimYQbH051Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-14T13:17:17Z"
    mac: ENC[AES256_GCM,data:iToPv4UE5yrOTaz/Gq54K4S9bRMaSDgxLVJZeXgNC85Na/X+UFgKjx4IwUFaR2EDcjqA+g3Y6cFNCXyJODe0VloZxIklklKSGYOcQkw0qFEpjgv4UfIWuGNUQ0KWwO75P7nTkGcow+IPEsW5dJtdLN3cmdxlKNO9ecN7o1OwcLs=,iv:Od6oziYj14bKEMSIQGLK1nXwz74W9W2/JuiA7Ukujfo=,tag:uILsQjp1JX1NIKOlj0NKcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
