apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: ">=30.0.0"
    helm:
      valueFiles:
        - values.yaml         # if you want to use a values file from a second source
      valuesObject:           # or inline values directly here
        service:
          type: ClusterIP
        deployment:
          replicas: 2
        ingressClass:
          enabled: true
          isDefaultClass: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
