apiVersion: ENC[AES256_GCM,data:iFY=,iv:GJ15EzEb3IlvNe79FXYTt83s8GPZd2+7WJay0egvvck=,tag:8JoaUugRjS2IJ7fzJ911wg==,type:str]
kind: ENC[AES256_GCM,data:CbKdXieU,iv:GUqR3SUdAhW1vCsp8Yz7H/QRDJg1vqKcP0LTaVWMiao=,tag:vWsqLuwHtWT0YhRVAD0bRw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bJPkR7wxuSeFOitVMUQ=,iv:m2Zdirj9Ndey87sUqUr/aOoXg9V183dj4//3OlfX9vw=,tag:H4WviIeuf3Od8PmVmyrXhg==,type:str]
    namespace: ENC[AES256_GCM,data:cT3wcQ==,iv:ZKQueenswwoIQiclKzrp4ERZfmXhJ4JeKXqCDYQ8f9M=,tag:C+2tDFyXrfyaTFGuIXbLYQ==,type:str]
type: ENC[AES256_GCM,data:Xvx5CCax,iv:MdfFCyf8CPZHxsgCjNLhLYNdQj0aJN/UG26mu0JShcQ=,tag:wXmmcq2bYBivdw7brrBUUw==,type:str]
stringData:
    #ENC[AES256_GCM,data:y5tYvMHD9EY2Y28UZsaasM8zpsWM2aXpw2Z3AG19+Iz89O5Mf1VKz1PBLXAP8lKAoapwl8k6bdhk3zHHssYQMj4=,iv:NMXGAeZbn/VD7R67LocwXEK6SN7dY5AbqJ6vK5AsYLM=,tag:f7nmCbTTpyOm/VyWEoRPsA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RMKxCWQ1l9oT6nMKPyXsd6oXgFw=,iv:P+b/YbhgYwMEDmVW2G3Hw2FEd2mUAPDr9I6gN/938RU=,tag:/aCo9IfrwTAZHENFX1ouow==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Jqp3DgwnR5l6Dy89LpXjpD9E8U1dLII1HCMAkmWx/G2KR6x1aGqQDg==,iv:5Bg83JreZSBUmRPkgZiSKfYc/M8X3y02M0ojKOpim/4=,tag:gvng0cGaX5L46QluMehTAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQL3VqTW96OVZMQmpRYU1s
            YzBjOHFtdVprOEFzd0xySjJFRzhzcWxGTVZFCjlWczRMb0ZsK0VxZDdCa0U1NjFT
            Skw4eTZ4elM1b2FLa01rbFNTbkE1T2MKLS0tIDRMbU5XMGJudUt1aEc5RjJya3p3
            eWNKcWFsNHNJTEpJaEtaRXJGQzArRUUKsz4AlsUuKvIacURlbyUuNaxtoGUxhioG
            a2zQry9iAXW25kcz4wAxH1levSIVCTHEVVAnZxg+pXYXuRVD2/bp0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T06:21:57Z"
    mac: ENC[AES256_GCM,data:j+S58Rf70qPseqt6/P9TCKXQn3nZKyq9K/6wfKf4OjtW67gNpjuO75mBCZXVbwykPAO7NVgHyiTQzqGLpmc6k+N1jR9vaOOvnPwthGAck/LvtAebia4RIewkPx6PfxcyTIFz6iP8jreQKGMYdfG5PJy1nSgMdUNjzlpnmjSGg58=,iv:ZxfYwc9t23tuU/2QcFR31TysV+uokKrMvXp9Qu5N6Xs=,tag:gcz9AoSvafIrFEtwdh6R3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
