apiVersion: ENC[AES256_GCM,data:FCo=,iv:0cO4OQl4gB22Ff0q/Nzo8zluYnPbhg57pKpIz0Flb1M=,tag:v0gjilCYxPZmTShYGBOSpQ==,type:str]
kind: ENC[AES256_GCM,data:3UbEK0SY,iv:7hnLn4H+QMY77Szk9g7FmUoLtzTepRHUVxhbH33CaMw=,tag:fyzxxk7rdjic4LNj5rkl9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TcjqtI9z0V3BEHq8Ys0=,iv:0PbQmJHeVlxA/LWBOms+XgEpPb7+wiOlgIHFKzOvEeo=,tag:H0sEuGK51Cz+B4fgrDpAGQ==,type:str]
    namespace: ENC[AES256_GCM,data:cRvU6w==,iv:rvcPB/JUfVD/PO3AEeHOW8b9cxcn8fhGD4X3nZNM2Ss=,tag:gYmrFfBhlg/2kpT4M1FmbA==,type:str]
type: ENC[AES256_GCM,data:po/v6Rx3,iv:EyxgE1J6/Kw3xrDDCBD1h38ZqNStDcsoEQBSydvGvJY=,tag:m2AA9X1HhWmaQN8n1Xr6yw==,type:str]
stringData:
    #ENC[AES256_GCM,data:ii8nA5apin8qlYpIDDN5ftFyCelyeNxvaiTg4/4VN5vBg4G0a7i9o/vAGMzFzs1lTSo+HLnvfc8npPqJ7qI2/iOKgatSlNp288zQQA==,iv:L0hUJ6ZMscCGZBWZ16teg+SStbUBp28uCcJp2suT8FI=,tag:dBw27LqsSMZwaLQgCf+f7w==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:iWhfeJ/V95I=,iv:PZV/FYHuF9a64i6XznkePCUYNFVqzBvN1r2ES6oMGNM=,tag:sZwHXrzNaYUUUI2BRobXvw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cJnybCh34Xc=,iv:/mmnDKiTL4r4Au3NzZpYxi8U7smEuqq0F16aLIacUGc=,tag:h4TiYpSA3FiE7OC9pJ8TiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdFI2R29CcXltM1haTFQy
            OCs1V1YxNjRHdFFIblVUeCtGZnJLTERBVlQ4ClNZbGJYL25va1phaG1zQ2lXOExw
            SW53Z0VnMFNuMTkzb0h0UjFYU3VET0UKLS0tIEwvS3N2SnZZY3ZiUDMzK0ZQTis3
            SUl2QXV1T1hTL20zOEJVem53YXppTGcKf36VUBLRJfBvKOrPVSsPugVt9mMuTF36
            /eoLU7RPPe/leQoz8QRmC9xFVCOFdGA2R/nldDkRh6vS1nVj0YePWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T08:00:15Z"
    mac: ENC[AES256_GCM,data:njyCnbv5RDv0qcUAJ0NnbI85FsXkzCaTTf/sl7jZ750Talj3/Fb6hlRz0ATBI7Ol/zpBBapjX1pJs7bDD0XI5HSgPOirdT4tGASKRRNvff2fDfrwQUixIxDTVRUvCn4cgA5ADu2dS/95nTTu2poiCKN6B2N9foW0+yBrLHLUK7U=,iv:ajXarv4lQnxu1BNqwAgLN/7Q6AsxYL33zvyqW1hu1nY=,tag:+s3pYMi2FnaTOFf2Hv/wPA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
