apiVersion: ENC[AES256_GCM,data:24E=,iv:tNhq1LkmULgLU+J4bqqjpsq9Lny6QoBuxPA1kP0+nWk=,tag:J+0j95vWgrpOWvboZxHisw==,type:str]
kind: ENC[AES256_GCM,data:DlHwTy3p,iv:OlOjvb4pU1j7HYkp5dql3z/DhO6c9JcA2tFcG9/208k=,tag:SzbKQdQoiKSNr4AYu+w7hg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1Vp9r7671vgSNQX0,iv:geX8jGr5G0gZUZcujJpyz7VAC08km7rSJTjEiPbS+BE=,tag:NSucB+ob1mssFe4iHX37Gw==,type:str]
    namespace: ENC[AES256_GCM,data:vynocA==,iv:FEZ5i/Af/F+4GVX8scmw8SjPUXMG1fAxbBz3QyLbdEY=,tag:YUtXzP0NHDNMx2eZYhpD5w==,type:str]
type: ENC[AES256_GCM,data:OFaM1x4K,iv:rzj3jH7NOaGjO/bnYL26yUxToqylWJKsWqrQucjGg6I=,tag:fAag+LWKFU57zJpALIvbSA==,type:str]
stringData:
    #ENC[AES256_GCM,data:rGMjk0l5uKuBgy1sy5qLdPc610J7JI+naJvKI3WyuKKGRipvv+vkSWjFc7jpvJWqatatlqx0AaJdQQ==,iv:Xe8hTIjoUlURnGuPv/t4DUlZI0puwwTP7zL6oF6Z93s=,tag:oz8FyhALqyG0Cez8Jt071Q==,type:comment]
    django-secret-key: ENC[AES256_GCM,data:Y/GLRv+t/kgVwUmg3XYxIPsk9dbBsDFWJoM4u0V/jg==,iv:xpxkcsleITgjHl81FaXDqN2a+F4zlqOnRwLG5ffHrwU=,tag:8MGb0gP9qUVPan+L1CWKAA==,type:str]
    #ENC[AES256_GCM,data:tDPyRS+MbPFBjGRpRyxa11zfDApxAnBwVUE9krfwFCt0ORQMou5IKzLtAg6PHzWYTLDq,iv:5oc7hZ2PG68zYCtXv/w+uXakHFdh2MnaVoa0dVho1q0=,tag:Kyc1m8b0AQzwUcuJs5pdeg==,type:comment]
    admin-email: ENC[AES256_GCM,data:RI5yI47scSfWhr2w67qohNY=,iv:vEusqsxLwxxjqcOZqruaNkpxismCatXj+auWqVmhPtY=,tag:rvPN79swYKv2azAW6ljGZw==,type:str]
    admin-password: ENC[AES256_GCM,data:jyNtQb3SPi6mm4fYo8Cn99PcmVUalSOTUnqjJA==,iv:YAL0ZhJajMXVHaMtbnwE57CS+j69DWtcDNmtZtFbkIc=,tag:sesrsWaJoKG32G54AP9Nxg==,type:str]
    #ENC[AES256_GCM,data:LpFEteaY151I/OJ4m98NBeJ9YdJbSPCh/SCHMZYYXOqOvGcphJE6XqV2Dv/P0tlzhRlHXoHCk2OimmbWEcHfsLFalH1bJyYAXQJ4LQ==,iv:Ceq0MrZJnmznrWNCO/zeUsfsSuZT+j+/tV/XKtCtP0Y=,tag:Mb2pX8M2RgWOjHKIoEe6mA==,type:comment]
    #ENC[AES256_GCM,data:+4yS8N/Nf5puz99sdq0xMl19FGgaOyaQIKiVbrVcEJH9hq4syfaECM/EORbtI6pamAKLFJH8,iv:UV1cAFzzgZCNzQ5lunrt0JERbPPxb915jOhSjzR8zws=,tag:ksAxDGPHduhCTvaBSCiX+Q==,type:comment]
    openai-api-key: ENC[AES256_GCM,data:70kxkWQYM+oSla+VMBnAgtvGI/PxsNbnl2nHmU5eQC+cZd3O60sEhfQslGk=,iv:tG0rtig+DqVPs6tqdc5X43JHNEL1BViydOoMYzH8njQ=,tag:NNcf8LQrpX0OGLYfF4/NZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSENMYVUyc25CWE1aaHFQ
            WGtwZkxTMEtwUUJSVEt2dDE5dmNQQmgvcFU0CkdsMjREZlNxOTRKbW10cFpXZXUy
            REd5NkRJM1NRMHhOVjVRek1QdkZrU28KLS0tIFQ1bFRiMUNoOUVCOUNkWTAwWXpk
            eklJRFJDZlNLMG1sMDhuN0k4VlIweFEK7Y/IruJT+HqBfVE7gZg1PiOL4YIWQ7Yn
            2ieiE5D4t0zJLBlnLYhe5wXwS7efww+jQon86+K1srdeWqZ6FTmb9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-02T21:10:06Z"
    mac: ENC[AES256_GCM,data:hLilv4xJf/o5OohFz7BmpizKtNBeOFp0NaIV0n0FK+Jdrz+HnxoEs49ld1NJnQUxoltIQgKsP83w7KB80+sy6Jaq2XwEM/y1GLStdSCbMSNbiGltTkNcOu28x88Bp6w3QYuDDGMlZXHup7O6biizwAqKjo/mtHhEWGyhXfe5JEs=,iv:gsuDxfRDcNtmBqkT2+YEJeDl6sFf9G5vT+fJse1t2ns=,tag:8DnKLT9cuD9FVTaNzg0bMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
