apiVersion: ENC[AES256_GCM,data:ncg=,iv:xzPwbihcnruo3HHNNmVZsT7+mrBmM4tBadYgmCDM05g=,tag:vH6SsRFY3A9So84VswW+Kg==,type:str]
kind: ENC[AES256_GCM,data:plj3+Btb,iv:ifXSc9xtAXkgBdHSC2EJoyjiPGnYKY8JAonfeQ2HyYM=,tag:oG6At0Fhi8HgcadDqEwz8A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VDAd18tXq2GuVsrq,iv:qENLFtC4V3hRs7YqPOrRRRqBrKFxcF+lijQqFid7e/o=,tag:BN97g9OYv/dhm0PYgzq6eg==,type:str]
    namespace: ENC[AES256_GCM,data:tq/PVA==,iv:/lj4R0zAqG14FpHbY4f2Wym674mJ07mlbT1vbvYh3ws=,tag:rPl9Tau+JsNMxhhaOQcCOQ==,type:str]
type: ENC[AES256_GCM,data:YeWADVpc,iv:Ht22O938drEkcyYJB87BS+vKqOizYJQDpB0Xn7nMvuk=,tag:g7cwogjGMQb/u1oHeqgyQw==,type:str]
stringData:
    #ENC[AES256_GCM,data:EvyizisHqvG6KNIzlErXzGzsGeeTxyjEi3TGzOXhVTGUDFJFbSzxMCctFgURb9q4/RPnO/BzWlWd5A==,iv:+uKr/vbnvUcTZGMjKeSvmPCgBd2TM73UVYcZQ4/igSY=,tag:2KSqtlFpoBoQkSHpngHmQQ==,type:comment]
    django-secret-key: ENC[AES256_GCM,data:iYxnh/+OL4bjKWC6woXLLN4ZGpDTfLgf07CtJyFxMDAltTu1sKp2GRFMt1uE7EKjzg+7U1pyn2qWClqEntqQdg==,iv:P/1Wu4qEzCZTVLkGiF0XZTG+/mmAqksneY5l3HLjz9k=,tag:KAmPa0uWeXIweatQywk67g==,type:str]
    #ENC[AES256_GCM,data:ScmnES/KKDn7zut1PlsW/kDUENiDMqPkgCNIRA9wwWNazC1MZtJFROJoiHpSf5ehI0J7,iv:OPtVvCwl5lqlJlMdftLl2XSkfSC4YbfShSInf/4EQWc=,tag:CIrTFQjLjEWnXCVSbanYpw==,type:comment]
    admin-email: ENC[AES256_GCM,data:h8Dp6nUF6M6ifRvjiKPKS8HeQPsfSBqNHw==,iv:ayK8hDcKc/d7Qt4udfYCT63EHkpc0EX29ZLu+r1g8oo=,tag:5gNPL/KhMXAIokjMMaXVAQ==,type:str]
    admin-password: ENC[AES256_GCM,data:RLURNY0dbBSs4Hl+PNeR9GGA/1W3C7ST2fAcMc8nTAM=,iv:SaF1syr00XimuENKQgP66QdXErGReLkhiKWrazzgAZA=,tag:YPa1JF354aNbBdT4BYKItQ==,type:str]
    #ENC[AES256_GCM,data:qPneIFGwnlWBqKF2vwBg/0uFZltfqQhQpnKWueCcGTJjekp2jszP/Aam+TSiRDTyPZGrQ+2bpyA8xBQSuhmLJWJCZF2Qu3RXt99e5Q==,iv:eHTxwNOytykxVZJQseayxpG5PrcOWB7ZMnG/HhICeqM=,tag:WtF+4FULv+YuPaL7Nd2+Lg==,type:comment]
    #ENC[AES256_GCM,data:Q8TXvRi+tGg4dII8u6RzNFD9irzHYJYczdHcnJ1MI4YtphvL1IlSLDdOmUGf6Vhk++P2izhd,iv:/QFm93pPPB3Ye+oAAZ4OopbbapdqqzXuYGATpr4jH4E=,tag:Mz1Pi9A6BE2Ktas5uyjrEA==,type:comment]
    openai-api-key: ENC[AES256_GCM,data:TbOggS70GWrN94+W7AJ7ZjirCJj4F7O/lM9fyqbZ2pwfflPRcMqbMLvPWJRBJhPgA5JNeH0cSd28k6mUflLPZRpxKA==,iv:yW8xF3QaQUFGBMLZC0b31iaFaCxTc8UneA1k/lnXj7U=,tag:4l1h1U/B7TzewyDPByGu9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUY1d6dXdsc1k5NEk4d0NB
            Rnc1YmZpbHBpWjhWeGJIZTBQYjhLbXdtR2tvCm95OWd5My9QL1RQb0JDVG1CZXBo
            OWQrdzlPTEFVQTdaSFlnQ2xqbFJXbHcKLS0tIDJhOVFqWGVVUC92UThNNjRDSzJx
            N0FKamNLM1plTzd4Z1lYUWtaYm8xdnMKYT36juwhta2tGpKAnJwHB6nNAJ0NJqZf
            YK3ppq5xnKFd3snP9hZI8OPBYim9H+pL0Q3yC37PTpH8WHJR6wJm0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcjZNWDZYN2RpS2hYTVBi
            UnpvdFpweERtbytVdUp2U0dMbjVnVFpCNGlFCnhiVzAvZGltSmNVaXdpZnl1NGJ5
            VHpNTVE0NFhpOUM2ZVA1QXExa1ZsZXcKLS0tIElSSGJLUklvTnFmRmNOSk95eEJE
            NUY4a3EvUTIzNmJGczBmMmg2Nm9xVmsKIHud0+2ldbKf982EAdTrBFmMtDLQZPK+
            YollqnLYaMDdwUcFD6wSRKMfKzHUc7kQCCrUI3K3DX2NmU1TiCzYQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-03T08:28:51Z"
    mac: ENC[AES256_GCM,data:OiGA8Xq2W/6U8+zDtdToqycAhrI0JUxzcamReeuYd/riaXGbBWTlhE6LYJtWGHb86+nNx6tZFjUTLlGZrYCFo2ikS5+Hxe5d2DTdTgHCr6GNyZSj1/Tbl3whoknXAXH8OzTo98edoRBYhtbtbBg/++ogSBm48S1krz6tEvsAHwc=,iv:WkhrzfYUQYPEFauKN5hfQb2KDSS3LiatUb899bz5X7A=,tag:E36Z/ixqVI9+NTixO5GXpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
