#ENC[AES256_GCM,data:IRK55dao6EwgElP9nKH/iCNatpaFhTwIXoG8WD90QKDSpZpNes7GQ9fe4fQk/zH8cxFRSkBUPkDuEQjaQ8ZUGkbv,iv:XHLvktK908ESS6TlDnKUX2xZfrRI734VLjKZ0cX3WMk=,tag:t7S+rQtQ/yYxrHBgLkLdhA==,type:comment]
#ENC[AES256_GCM,data:S3Em9AJDGaGwpWLZsDr/GMzQK27UQcgloLhYWQ6OBNkUISud9RSbTfDTOLe9qjQxtfxgdrnsMThHS4nbCXxaqO+zdFLa5e3d,iv:HPMCi3CE2eexptVX3/eolsYU/oQGK/htvV5Q+xoxTRQ=,tag:p0qOalKJtaALJJp1k95ylw==,type:comment]
#ENC[AES256_GCM,data:TcEaazpjtMvTV5U0aqCBDqULfR5cyo4tSa8I9b3sojSN293mYCszWCAfUmdJWYdgSEuSe5rYCWpmPDgiGzPNXzPKvpoviWjT8g4E1HaR,iv:yHffqGTV4+HvoXHOhRr/k/nm60yEQJXTY+8cHhlrb6s=,tag:uDr/6axKuVmdO6pJivKY/g==,type:comment]
#ENC[AES256_GCM,data:QqunwQP6F/nfgooDbKwYtcDMuQaYRi6e,iv:NAPX7vxSjfMZIGmh0aS2ifqTuiENWIERQOjnr1huDAA=,tag:yQn74W2G6nQuq4Q3oduazw==,type:comment]
apiVersion: ENC[AES256_GCM,data:Ug0=,iv:zIbAAvPvLnw29gnWU+RNx3rGfq+qztQ4U7eU6qhHhng=,tag:4PbXtLnvDO/sFPVDg5Te8g==,type:str]
kind: ENC[AES256_GCM,data:ORNQ8jB1,iv:9N25rXBc8nqhuzpL3DgISNUASLBjT23wMl19t6etHVs=,tag:S7jEse5U1kVen4clfYMJtg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sAQjDbw7cNYj0TQUTEE=,iv:XkHmfcDwuz47kAyU1937sv7x6XQva/0GeZ+NvDXKRto=,tag:2xmAvwfaR4mt9sVk7rbO6g==,type:str]
    namespace: ENC[AES256_GCM,data:dI98BLP6,iv:WE/Nt00/QSMgxZT0LMTwxVLYXswYgBLsgXMaWV8Ad2A=,tag:VpaMO+jQBlWvlrpX7wuGzw==,type:str]
type: ENC[AES256_GCM,data:0Bu8h8Nr,iv:ircYECiOxiFMgIUuqdcS9gY/udHCsyDsCPAXdmKhXZE=,tag:8g9v9OO58wj4D+LRYbHMBw==,type:str]
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:Oqujm2eqV05IAJAV8D1gGz5IxdcfgaR3x4Qbh7bhN3PAfW+cKqeKwnn+F97JZbnW9uUUgrnTYFmS+J2TI1QCzkFMIQ==,iv:ovzK4jn0wy2WEfea2TFdi2bOnhuUQ+imvaUOCpb10xE=,tag:oZQzieqcMUiG6cM1IxbDTQ==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:6z8BUy5+7vrLZ4LQSn93WPouA7g/VjnD6SlSYRlAbmnVy7ODBWAgfspW/reVs1T4B1tWfez7ww==,iv:b0cDbxqbQv9BMSb91CJ0axHC5bPBxvV/qzGvKmlgm6Q=,tag:MKHo5HJJYzb1+P/lhvn3cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMHNVTitKcDdtRzRsS1JF
            b2FhcDlZS1ZobzJHa1dLeCtsdDhwWlpzVWdZCjJPNGl4WXpPRzRTVG5uK3lvNDIz
            ZGtJQ2JoMXRTVVEwWkNaYzJiWnZNdncKLS0tIGV3ZlYzYnFpYzQ5dWwxUk95Y0dk
            cEFnVFNqYXFneDl5MkZmMER4Y0E2WVkKPvjPBsae8Ihwl8LLYDNX9y10WAPUiAEE
            bRvDrZ58bEb8HXLKmGkQGPVLkVkVwKBx+r39n7/p7GOTQnFnemZg1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZTFHVWxncGlkOHpOTHNm
            MDlDUG01R1lRTENVMjlDQ3NKNXFHS0xCSkhrCmxHYXNCQUtRdjE4eGdKeUlIb2xr
            SFBQejhnZDdDeUt1Z0xscFR2T2NTeEUKLS0tIE5vTERvMXF1czIybXNjSFNUdnBQ
            L1NPMHpUb1Z0bktqcVpvWUlWQ2J4NlEKjdDtGDx3pKYDsPgiSrrM74MAx8at46Wo
            jdMgE3tPC1XK8k8IkWVbRGeH2FZQAHZtUtEpjIZuhWw1gg7H5gSAmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-12T10:17:44Z"
    mac: ENC[AES256_GCM,data:ClyGmRggDDWnTdlsxENDQ2ta0zsCMnQqhtw+OCyQZkEcSo2SbrmjMBiGF4WsqFZY3yRWQtzJA+igTENIqXOH3DOKCy/i73yxmVa6eePkEXcgW2xhN22NJSjB2HvRjcaIHjsI1CNdxKNtE7jkrsfME47b8O4WPesJ8zNe78kmNTc=,iv:jqIQS7/vP27PybWaHp0bvkkI+6rjynTfRmgmirObHFk=,tag:I9YiP2SuuHvIz2nB9iKFQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
