#ENC[AES256_GCM,data:i96vch84j3AYMZKFCVPOhrU5YBG3jeCVHECdoYc+ILqSipYFPxHcPpflswyMBcqG+z/Lgcu/e7KvnHjDatFJAT5T9s18saDlaWkg,iv:yr+U5zcyKSPDqZdXCwNmxTjNs8ark2jXiHNnm43nwhI=,tag:NZ1EoR4c5P1G2TUT36dUBA==,type:comment]
#ENC[AES256_GCM,data:MHbup+kdU0g8wKrgAzTIcvmKhSLQU3hdJuTwRQzvxJ/zaz1fydV4jFqCBAT+w2HzKI+yjOJ6TZMY0e9sPuzRdO+cWwUMcvqqHvRT7Ds=,iv:GyiPR5M1g2rq6w9aBV8otBhuWc3OyJXU39jYD1O/qZ4=,tag:VxEJCSVuCxmvqw761pcaEw==,type:comment]
#ENC[AES256_GCM,data:vRuhrEUXswkQK43nf0ngnO03mPQAJmtyQqFgRsJSpz6znApd9gU8HZV8jHB9qiY=,iv:qovBsh8Vr+UKXlK4Ofpf2WKQQup8QY6fLMKLebEb5gs=,tag:9gKeXXpss2P/jKs1NMRbdw==,type:comment]
apiVersion: ENC[AES256_GCM,data:wbU=,iv:kMBcvJ4PIh2RJ4do9kEvAspZ1uD0tAskAWYl6jpBCSU=,tag:Q6TXs3dRiQNBx3bh0Cu9cw==,type:str]
kind: ENC[AES256_GCM,data:conciL6O,iv:/6troY7qBp01/iawShQ8zKRxOx5Nk/bo5I3PgGUv6uY=,tag:F7pHIjwgJzgVjVsYJBpjFw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UjOrmu4xak49X4o=,iv:tv78ngr3/z7Kht0MZIH6eIl7r3KY+nv8Dy76SGBhXEM=,tag:NuSmwgxHZvtkLUZ7YUcUpQ==,type:str]
    namespace: ENC[AES256_GCM,data:t9K9KNKK,iv:SfYESz+ixwRfmA7XVHnfJA5knL1q3ydMZb6anOqzCrQ=,tag:AFZMWFKxiLdVTA6Y16nmgA==,type:str]
type: ENC[AES256_GCM,data:aEOBYnSG,iv:JagygzLV6jMcwLTiMNRxGhwIYvtDT5wveVKmttL2l+o=,tag:n2rjWLNrF1K74zXJkJqfBw==,type:str]
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:wEoz6nUBG82w3lUB,iv:8vCva+zI4LXMkEAuvUkSNyDLE8tTUAD/91x5Bl4rJBY=,tag:cj/4arm3ojyhVE9MOSdhcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SVVjck80ejRDeTZwSW1L
            V0dqblZKM0pxaTk2VjEveVJQVy9FeVFYbkJRCkZPTi9YUkxwOGpkcEJNUG8zckRs
            Um1SWjRlNU80TEw1WnhzbGdrUHZSZG8KLS0tIHd2aDR1bWZxL3Y2cm5neUw4bWVQ
            Q3JLclA2bE90RnVKeWtRbC9yRXNielUKSnCHz6bQ+/rvjgVVhs2bygRLVcY5WZPB
            L8ABWYfNvK/YI0rUG6W7namVLYxe2lEkruu1dkuQENSCB2E88RDdxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNUluL0w4WS93c2srNmQ2
            a3VvbTA4ZitMaEd4YTduQmFTMjZtcUI0aFM4CnB1K3FndWswU2U5ZlE5VUxCSEZB
            K3NTMFVSZXpvb3NIRnJaWkZGZkwrNFUKLS0tIGtPOFpMc25sakJTdkdaelpHeWNV
            a1JiVWd4K3NhN3VBVmVkL1Nmc0t4Y2cKCgGrwQwr8wZcKYPfffsQwPzG1etK3o4Z
            twjfajVUvfjLiOcerwj1fUmcGRuoLs187hNUmS2w1a+ZHw+h8aRv0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-13T18:20:28Z"
    mac: ENC[AES256_GCM,data:dCZLhWSjTCjorBwJzi3pad54vhPaFHh8H9doy5CeK+3S5KZ6gSc4OJX8pJKVVOazSJ1VCfTbWEbLKsBxMncaNLh3A7Jrq2kD0vJrYUCJL3LdAcjhM1CEHew4iTEND8GY32t3s5113ryQT5gvvIW169jfURjR3nbvrjYaVk3VYfA=,iv:4SfPDArMwUYL/qmhKbguoZo0n8sim5pjSBXq9H+XIYA=,tag:e5UR38FrHboT9PLC/aUazQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
