apiVersion: k8sgpt.ai/v1alpha1
kind: K8sgpt
metadata:
  name: k8sgpt-vllm
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    model: fast
    backend: openai
    baseUrl: http://llama-3-2-3b-predictor.vllm.svc.cluster.local/v1
  noCache: false
  filters:
    - Pod
    - Service
    - Ingress
    - ReplicaSet
    - PersistentVolumeClaim
