apiVersion: ENC[AES256_GCM,data:M5g=,iv:qStPZ23/tTvu0MCf6ENgauroNtgMImXYc3N97n+lbg8=,tag:uS1Tkjm7NU0zHxbdsWLvcg==,type:str]
kind: ENC[AES256_GCM,data:9Yf3GNOB,iv:+sDQAjsFSEr3IlBesVU0ndPxZr103WzqKBQkuEH7n5I=,tag:MsaYKOy8+a5yOLydZiXUAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PHB+hELTX29fg9XjrxyJcTN+9OLFaDjJiA==,iv:oUKlCSQxeCkcwwdO2WoLAsjilS2cLPfp4HL/XGLmHZ8=,tag:MBXICDZBAN8RZ3/HhHDiDw==,type:str]
    namespace: ENC[AES256_GCM,data:3XJJMxUh5Rvt,iv:zYVWzaTcfvTQDdFhBv9LL8QvKPjhn1cHNzklClSjcUI=,tag:FHLCTOt4P3B/sHLOZzWrPQ==,type:str]
type: ENC[AES256_GCM,data:tPYShCq4,iv:aOgTBROqMLyQiJKHhvRfnL5w7J45Yr28AohfjMYxwEI=,tag:xN6HfggquEZgksv+z0GNKQ==,type:str]
stringData:
    CREDS_KEY: ENC[AES256_GCM,data:oaYn/a/iOBSEnqpp2IL99oWTsSVK6u+l1/2P96faSjEH5eMEiCb/mdHqFR3Xv27OKV7CMP54MmFO/vAXpyIz8w==,iv:O8SaSrNvP1lqhEl93a62l9EWb3awgJdzRX+Q9hMkelM=,tag:sc4DdnRzFZeq/InKdYOX0A==,type:str]
    CREDS_IV: ENC[AES256_GCM,data:HyP0o0GBexnnswzQQJn2QCYjpUkVs8PW+H4BvBDsCF4=,iv:56EjiSWBlRONy6SEjKBghpNYuS6pbHpXr0oGz+3HW2s=,tag:NjDcEwsIWF+dg3oLgXtxBg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:v2H4MsKhTfXPtU63haCfpKVC0myTixQOvzmkEn0hUExW0/f5FyaeDbnLuMkqIeO+/Quoj3vS9qQvDtIu8/Tp4A==,iv:dLC4vNj8AHXUbKejm+q7+maGYNCpmA+JGw2mQITLYTI=,tag:Z17jQwJEzPJqE6eawMJzyw==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:ZvzNcaAeZL21NEs0LvaFxVEiqGEA8Rms3FEi3TU4GeNwcz/NJCNIujewW7FNtbPhJrokhogPBx0aQDNA44QCig==,iv:yopsQku36qdQDGDqQXakSvyDUAVLdllT4nqinXBbbsg=,tag:CsuFm6fB/ENNilMQDYfzmQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:DDVCagC1u5Qj2WyQs/ApP9jw1KZTxdYgO90gBe75dbwxB8HxzNZhjJLQjDfFFPyz,iv:dVpHSPDJK4U0JtNC0/ILFznEy/VhaJtw+UNIN4dT6G0=,tag:HqhsVS6AE4agCzEfSyFShw==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:FON0vwQ6fgkPtZmAyaLqsZCUrgsldhIE6wDo5OKZVjLSWV0h8QFJfC615u2GCbLbPEM/8qVPTZODNB8Og0rO1A==,iv:TMBv6DLyymFDHBsjnAW4kSV8kgYIJuny+R/1FBoKCfQ=,tag:Zedb9OBDRWy65KwOpuccpw==,type:str]
    OPENID_SESSION_SECRET: ENC[AES256_GCM,data:G6OKYTf8piiouS+CI7I4HKaIYnkvLof08Vr/pqbCXaITobSSMlVMCMP7+/eXRerXP4+N891CIybPR+W9nWrMVA==,iv:vkcrKQKnhx0z1doCTOIjV2bRTnE6P5ZppuA9CQdVP4Y=,tag:S2MoevBt1Em46gvNBNjRgw==,type:str]
    AGENTGATEWAY_API_KEY: ENC[AES256_GCM,data:e2Z7sEw807jBndEJt/YIgL6LJGctRuJ4hfImsktw/sbPFQwiZ6n7wDP7vTVRORtud3orbf15xvlEptj+Gkpevg==,iv:EUiz2jEM1ecvnp4Qume8PEOMDOaYkJs2DP6K7Htb0Hg=,tag:X7A6OTHHXCMojnahZCqnJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UXcvN1pLWHBSSXpJdksr
            dmdGVytIb0NnYkZjQXg2NnFGR3o1UU9NTjFRCjdvNitnY1FNT1kyRDhmUHI3MXdl
            Zm1aN24wdFpmdWY2SDhic3pWcUduaWsKLS0tIEczNWdOREhNSjkrazFIejlFd0V2
            UElpVi9nT09oUk44YWhRUVpYL1k0OXcKHcURr2NZZA1fWNKOHl7Hx7xGwbirlYcl
            S7ku3BPmJUGBWh9N9WtemY1WT2RGEzQNwbVRbdJ6XrRxJ55xZ8acmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTjJ2S0d1VTcyOU1EalBG
            UWtlelB3MkZDTkY5T2laTUcxM3pCME5OTGp3ClhmSmJqMEIxWm9OamZwRmlzM0x0
            ZjliMUVaS3U5MVBXcUVYc29raDJPbk0KLS0tIFNXMzZXOVplNVFHZ2dzTDhuVnBW
            Wk5oblJqWWRDeTdMMWpDNERmY21xOWcKIKocX/QBIEIsj8g1RpfOzf3RfCtv6p5B
            NqNrYLm8Zl6BjoIaL2gDSTgBC/tyXBUTvjqPPAyACQKKKHPyz5XoIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV1phUlFxYUQrMGg5R1pq
            QURSSEtJZGVhMTQvSVFFV1R5QU04NTk3U3hVCkgxSVNHU3IvWHU3a3R3QTh3cStP
            YWJVK0RIWGVMTVFhUVR4T1BocGdLdWsKLS0tIHJjMEprSUxtS0poWmFWd2NTQzVm
            QVhOUjljclZGY0lpbXRnRk5VRDRFeDAKdx31UW/M8cEmrAUUSVom41xeFfzondkj
            z6IODWEG4hwoQ7lvHIPsY0VyZgAGEpwLwcrHBfiRkst14lhlVHFrrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw89zltkg52p3s5qw5ejwzg3tusat0vth9aumcj2m5pwuyz9zyjq69kwf0
    lastmodified: "2026-09-20T15:01:04Z"
    mac: ENC[AES256_GCM,data:juZbxVkMVmd0/qgMGG7oFxXBHo6IcEAot4tMZN0Mm41bmFrMfpEAMVpuUQ1sYefjBSuijTFsiCgeE2OEhiQmjw5Pyoij72ZdY8PgYmoEP0q2LmYv8pr9PPesyX/EmwMwvHaHaxM7Ta+aagZq6/ySh1CI8j8nzTTrWi02XjXqsFc=,iv:69Q5KR0+e2yecW/jN56xHzFrgMLMe5a+mjPFcszY+Gg=,tag:Mkpcx4TZgIROekTNfq/eJw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
