#ENC[AES256_GCM,data:jeHuxNrF5FxFOPnBP+iv/E9mwtNh/8uqBHQyropBc7p1DXQpX488xbJiVVS0hbfyqQZQ/s8IrWgbFOcAfzuWVARXUg==,iv:MhHZQeYFZzFR3T1fvwhHsFCYBuG26uuV18lROO2mnUQ=,tag:40vQwvKvhJUuRb5K73Eeeg==,type:comment]
#ENC[AES256_GCM,data:MVjWncYdgbc7wvA9l1xgs0OkBASU3SSxrxuOUADeCzeuECR6ccie2He1eiycVcDKIJ0xFs1yULpyxLXN+NG2WcBt4mcVfzNr1FOvDWdKWHQmPg==,iv:t5XhN/Jm9jUH889W5TTAs5/tlwSfjAjab28e7nycCuA=,tag:DlYhqOJhWxVrbeWmOGkgxA==,type:comment]
#ENC[AES256_GCM,data:70mcupsvBuUUvGN85Zm1gDxRKwnbL64/xWIJ5Ux8zAgZ58SCj8KQGAMWbdlmeiYTPxji461yi9DU8kZoVcnhbBnEuZ0dOUn3JJIdk+jfPrH0wQ==,iv:kQtC1X9prlY6ZLkx1t1bafsluLA7jF6xZo/s9Rt5hS8=,tag:O7f7Vd3AFSMFFy+7G+A6IA==,type:comment]
#ENC[AES256_GCM,data:nB6PVXBDyVsmZSQGrt/dIJBzvq/SgiBVHOtvKA1PtwrCamFDhMxGe7RaDvI=,iv:J4mbJ7EiAGfM/Xmosi8pts1cw+l+v0pFpvWC42vDNAI=,tag:aSeG0ts53QB3+7Loxww19g==,type:comment]
apiVersion: ENC[AES256_GCM,data:TGY=,iv:4aQxcZmsOVWB9q5Yh7I6kA63n4ZnTFvFnW/afsNIx60=,tag:rSMeopC3+oZOq0YdsxBs8w==,type:str]
kind: ENC[AES256_GCM,data:RRT43BSW,iv:Woc0R0RA7TB5SiZztkNf2HkGvcttUn2nDPFGT/ru+ms=,tag:N8ge68WWd04O4W91HBy1aw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8b5SraxssEApDEMFYQIm,iv:Y+eVlRdF5o5OSn/sV5dZ3A/TIz04GT2dGU2d+3utZns=,tag:Q/nRTSp3NEL6n12ioJEJLg==,type:str]
    namespace: ENC[AES256_GCM,data:/YQdzZDMYt/VUiY=,iv:E3mtePyRyLXseI2lFWTa3HylQ9ODQVYsZ/JaimJ1+t4=,tag:g7WTnnwuGWEPS1lgY4SOiA==,type:str]
type: ENC[AES256_GCM,data:rAy+DIBG,iv:Mnmx1knS1HWZD5h13ZeDXiTV3xGonhzDd0o7KZ3Vq7A=,tag:1jRep3LzQCz/vVquovWcEQ==,type:str]
stringData:
    DOMAIN: ENC[AES256_GCM,data:YNglgALOnEcE3zUi,iv:V0kGjGEPkmct4r1jRN9MNZYQnHdcAsWxClAllc4a52k=,tag:M25/1vnlaFOEZf87mW1O/A==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:z+ruDpNwTvWqsqHqqSCazAcLTAvUyTKZSg==,iv:txH0XqGyGNCm3sWNRsDnOqOd3O5f88faPBIdy3kBeUI=,tag:DTm0lP4dLmpcSa7wcBAEvw==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:aiGtxy+nryYLSUuuf2bNh/oaWyPwAnAwsg==,iv:nuHYDsCZfIxQNn2D4fd0IAVwlF67WAzggZSn4cCHMIw=,tag:GtOy1F3x8iF72ze3BiaJzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYkkzZE5iQW9KUi82T3JO
            S2ZQUlVzTFgzNUpHRXZVVnBRS0UzTnNBUGxrCklvVVZ4clArK1JmSGp1OG1WQks3
            aXkwQzNvbEZndk50RXd5OHc4MVdEaE0KLS0tIFBuVUtSSWNqLzhYODFwY2lOY1NF
            Y2JNM0V1MXNCdDdseGUzd0tFNVVTZkkKrFvZmMgtCsRgjdE3urNFZiLsitBxDqJQ
            GhkalTydd85+byLLmsbfmbXBNt1ghEzjt9izgZI9TtWMVIQChRCn/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZWNJQmRlODdaQmFJNi9I
            b1ZER2FISHI5blVRcHhGVEdlTGZ6QTNJYWpRCkd5TGl6dkNaN3c3RE5wcUk5S1Nv
            S3hSbVA2aGpUYnQxeWIxMERZQ2hKamMKLS0tIHhCdDgwd1hZRGVTakEzMEM4RDg0
            UXdCR1NJODYyOGRoSFJkY0IrbXBUalEKPfUhKTVRMMsCR4ed++NouTQ/ZwYLxRLd
            mwvpqabRlScP2Y/002sk7L67piVIOqpFI4PU1cgVhIubl8iNCwakBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eqnl3ytjeeav32yzpypjahxhr0s2xrlclyj5sfyyflp4w9huf32s0t660k
    lastmodified: "2026-06-03T08:28:51Z"
    mac: ENC[AES256_GCM,data:1xlz1a4MFWbBauCg9KOEL40INZt7gzGIg42TraNqAl6YRN2QZhtPYfY0DtgLQ59NeWhnEZamOZvaUnsEBpQbQaSHNI2zwNhEz12ey4VevV016Sq/J6QNaXShck3vjgaTmzZ+08WCrm56KWGm6uodNmP26iX3flQTK4qE81iCBMA=,iv:9oPFVOWm3hOWkUwLsKLTjx405WkEkKSlHtBHlI4IOMU=,tag:gn9akQ/cXdARpdFMJuE1bg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
