apiVersion: ENC[AES256_GCM,data:d30=,iv:J1EywZPk5xpELo7m/bw5VwnQEAN29blocxiG6W+irEw=,tag:xzObw6KLadZJjMkEAgPAgQ==,type:str]
kind: ENC[AES256_GCM,data:AshmRgLU,iv:cgWNRLosJUkaDENDYfGQDBCxvc8urKw7NWSnrrNcXTA=,tag:TGtFPx/YtzFv0Ly0ujxllg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oHUrL9YO6cPoq/5dJlA7,iv:7dg4eguF90jFyM2YpXAWbACh1Otq+5hHJmlPRUs1Myg=,tag:LjRr5Zel7t84Gm6WTIwyWw==,type:str]
    namespace: ENC[AES256_GCM,data:Clf8yNBPLQ==,iv:5fJP6L9uFCBJq/IUwSFug/oXSG+2M99pEP0zpPHxK44=,tag:kKfJu0/vMSpFh64xmdf7Bw==,type:str]
type: ENC[AES256_GCM,data:5yQ7pOH/,iv:5Q5Yju/MWWU7v6+Sco/YmrKJOWnKKusOoOC6d9MFiv4=,tag:WqbNgJbNeJEwqKywUogg5g==,type:str]
stringData:
    #ENC[AES256_GCM,data:AT24oeMEsh45+dLgbr3wiLNUBoDJH9cU8i2z2KSKvU0jOaDm5YdVEepN/e+jNpfIZeSN9F2xnx3ohPnb0hE4hj+bx7EEOdFnsng=,iv:l1jM2QoqwqiBr6OmHNv8eo58g7cGerDhqX6CZ/Ws/x0=,tag:Bz0VoukxUHe8L7U1EuUAzQ==,type:comment]
    #ENC[AES256_GCM,data:VGXW1LodCSahhBPLIVF/lnXfhirT6aQke9wK5fwVLOKsbaf8iTCbgJDYMxg48PPvPvZWfq9pVBmC24CmGeWv0jNGpRL7YZxQNoPXfSFq,iv:YjorN9uD4DGJH6jWmQovXXwMcj07wYVR7XoVU9V5a9g=,tag:jEQ40WDzkw9/K85w5HhLLw==,type:comment]
    #ENC[AES256_GCM,data:uyRVvBoFtDbln1hDSZ3PSqHRoFch7dtziE+NcGJ11c5tS4VMS36Jk2NNNPajEb7IcGydGzXP7C9Q8gwkDQ==,iv:jMDLQ3YF1JlW6U0866lv9pT6DM3kRB1zUMlujSYDhuY=,tag:i5ps/Q0ZBqj2OrOQeiYUCA==,type:comment]
    master-key: ENC[AES256_GCM,data:HMnF/L3J2Jr6BmsPML9IWokXwTwYjYByBL475vKdKDOOndYR3DKmH7KLZtyy2bZR1vzHHq2GzgDSote3OAb/wjx5MA==,iv:aaot4KXdrJYlZzkcdsl/sTScUNtHFK6mSSjK34w/dKI=,tag:4n2sZGJBo/ibPcyoEw9nPQ==,type:str]
    #ENC[AES256_GCM,data:E63HXvLpmFfcZqVKyyiFU3lbV9goWTz1spLLdEJSxtpo7HJv7MKzjWe3Cvtq/lE+4hDYhnzVvbYHL09eSAAPJnLRJAx1HLE=,iv:5nMQgejacyXf/IMaBDr5zlXMNNVorsLTiOxdSHcscdQ=,tag:tKtp1qZC/PJ9MdyXu95xTQ==,type:comment]
    #ENC[AES256_GCM,data:QapPtaeDbJ4mpii5vMazzE+RBBGKiQZ4dv3UzO6lV4mhj4lbuIukJqOGyLL0RRchvATTSsn1QgsuxE4WYAgmdg==,iv:TXw4U1c1qe+byLJRb300F8DDwhrsnbjqDQZTyt0LfQg=,tag:j6+ZdRz3CNthSgu5fDKSPA==,type:comment]
    #ENC[AES256_GCM,data:SRXZ7XVSOZ23/20JGALrgbKLgK/E02LscaaFO48Zp3QkNgDteaKrXsJgCpmrZZI=,iv:O+DqkM3T01622QgNdSejWKI8bPFl+ojWSWs6fWAzaH8=,tag:lFLTwPT7j320Xe1vw9IIdA==,type:comment]
    sso-client-secret: ENC[AES256_GCM,data:49pZ0ZZ1l1kAtQSqCKVm140Aj727soMri6A5cfzUBEnlRyE+e0RFp+vAFMeYfgyn3OefoyGozA/3Vtll304CMA==,iv:mDaXxuqQFMTkZAvFAuCuJ3NNpl8qNK/bTK5Xt3XXHko=,tag:gT5yJ2Rys1BzEp76CNWfQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZC9NYmxxRnFMSENrRTZW
            UEx6UEdiNk4wWDh5dUVHTGhDcUMxSDNTNmxFClIrS0NUY2tjOEE3VUx5RkRlK0Yz
            OXdtUzVnbFdGeTlmQ2h0L3A4bFdUVTQKLS0tIE04ZWtPWDU5MlczL2d2SkZ6aVcz
            VHJuS3RjT2oxVmNTVjRLNStjMGl2QTgK5FHj9WapZi5By2G8ifnrrQPCijaJouXd
            UrE7+iHIP0QgBh9DAGQi4cXodwLFi1B+66GoScBDRf0wYmLS/52OcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3lgj5t47k5vx67ck9gztwa7kr8pafzlnk725p82nvlvhn8z9g0qze7alf
    lastmodified: "2026-06-03T08:53:28Z"
    mac: ENC[AES256_GCM,data:eeI5CkPu9Sn/ptobJ71+my/ftZdiQwMYZxtqWw0wc1L1vQUyEmacwDTS3mcIrnJ7bnrt1IR0RAlpmiyy/PPUBpSO9P+DV6BPBDI7xo3SkOJkrRWEHbXwxLr7UxqfwZyGa60iK0ow/U0MNafPwNKKjk7NTeyOIEf7KA5d5mAgoQg=,iv:3NihG9l0ROuWDRFigpUPFkASr1gKYg1ld8jOHusfeRY=,tag:p/5R36rq4QW89B+r8z4Skw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
